### ISSUE TITLE
Continuous deployment of Data.gov Platform and Applications

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1004]
As a Data.gov operator, I want the deployment of the Platform and Applications to be done in an automated way so that changes that have been reviewed and validated are consistently applied to all of our environments.

- [x] changes to datagov-deploy trigger a deployment of the entire platform (and applications)
- [x] changes to an application repo triggers a deployment of the application
- [x] target environments are determined based on the GH branch

**Comment by adborden** [comment]
This is the rough Idea I had in mind https://docs.google.com/document/d/1Oj-qR70utoFpi7-NFcoBgW7XAsGy9g58iMjgxhDqhMI/edit
