### ISSUE TITLE
Modernize development environments for applications*

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1005]
As a Data.gov developer, I want to develop our applications in a modern local environment so that I can quickly get setup for development, testing, and debugging without requiring a remote environment for the majority of my work.

- [ ] docker-compose based development environment
- [ ] unit test framework exists
- [ ] automated tests are run as part of continuous integration

**Comment by adborden** [comment]
Meeting notes https://docs.google.com/document/d/1IHYyFjI5vKyMd2Ch-eKAewDKdmeOCTWF9jF9l0iVXAs/edit#

**Comment by hkdctol** [comment]
This epic has been entered into GitHub Projects https://github.com/orgs/GSA/projects/11/views/4
