### ISSUE TITLE
Update our log auditing process*

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1085]
## User Story

As a data.gov operator, I want an updated log auditing process so that I have a high chance of catching anomalies with as little effort as possible and captured in a process that can be incrementally improved over time.

## Details

Our existing [weekly log auditing process](https://github.com/GSA/datagov-deploy/wiki/Compliance-responsibilities#au--log-auditing-weekly) is completely manual, time consuming, and has a low probability of actually catching an anomaly.

## Acceptance Criteria

- [ ] Capture what "normal" looks like for the system within configuration as code
- [ ] Employ automated tools to remove manual tasks
- [ ] Update the SSP with new process

**Comment by mogul** [comment]
Reference: [Using aureport to interpret auditd logs](https://www.tecmint.com/create-reports-from-audit-logs-using-aureport-on-centos-rhel/)

**Comment by hkdctol** [comment]
This epic has been entered into Github projects https://github.com/orgs/GSA/projects/11/views/4
