### ISSUE TITLE
Automated CRM facilitation for agency data contacts*

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1128]
## Feature/what we're after
As an agency data contact, I want to receive customer support requests for my agency's datasets integrated with my existing CRM workflow so that requests all the information I need, are routed appropriately, and I can quickly respond to requests with high degree of customer service.

## Anticipated/hypothesized benefits
- [benefit A]
- [benefit B]

## Measurements/metrics
- [description of a thing that can be monitored or tested to measure and validate when the outcome has been achieved]

## References/background

[CRM](https://github.com/GSA/open311-simple-crm) as it exists, is no longer being used. We want a blue sky re-design of the project. Generally, the system should...

- Work for the Data.gov use case
- Have light integration into the agency's existing workflows
- Emulate our transparent and open government principles

## Action Items
- [ ] Review and update our Digital Identity Acceptance Statement and IAL
- [ ] Schedule demo/overview of other solutions in office, e.g. ZenDesk
- [ ] Review other CRM-like comms channels and workflows, e.g. review all of our GSA Google Groups

**Comment by adborden** [comment]
Switched to the Feature template.

Just adding a note here that adding a CRM would bring PII back into the Data.gov system and might require us to reevaluate our Identity Assurance Level, and any relevant controls.

**Comment by hkdctol** [comment]
Entered into GitHub projects https://github.com/orgs/GSA/projects/11/views/4 but could not add #1127
