### ISSUE TITLE
Upgrade ckanext-saml2

### ISSUE THREAD

**Issue by avdata99** [GSA/data.gov#1403]
## Description

As a part of a [plan to upgrade CKAN extensions](https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit?ts=5e50447f#gid=0) in use, and in order to improve the way that GSA [manages forks](https://github.com/GSA/datagov-deploy/wiki/Managing-Forks) we need to upgrade the [saml2 extension in use](https://github.com/GSA/ckanext-saml2). ([This is part of the reduce/simplify fork epics](https://github.com/GSA/datagov-deploy/issues/1343).)

## Acceptance Criteria

 - [x] When there's a new release upstream, we can get onto it in under an hour
 - [ ] When there's a new release upstream, we see a notification in a Slack channel
 - [x] If the upstream maintainers don't already use versioning, there's an issue in their tracker requesting they do and publish their package to pypi.
 - [x] If the upstream maintainers don't already have tests, there's an issue in their tracker requesting they add them.
 - [ ] We have tests for this extension running in CI

## Task-list
 - [x] Define if we are going to use GSA repo or the official Link Digital Version (based on PR analysis with our changes). 
 - [x] Send PR with prelim analysis to Aaron
 -  [x] Aaron approve PR
 - [x] Do some basic and manual tests with Catalog and Inventory apps (We have a Docker-based environment for testing [inventory](https://github.com/GSA/inventory-app) and [catalog](https://github.com/GSA/catalog-app).)
     - [x] Add service provider
 - [x] Ask for test at usptream: [Done  here:#115](https://github.com/DataShades/ckanext-saml2/issues/115)
   - [ ] Develop tests for ckanext-saml2
 - [ ] Connect our Slack channel with new release news in upstream
 - [x] Analyze the [OKF version](https://github.com/okfn/ckanext-saml2) to pick its improvemnents.
 - [ ] Apply this new URL in requirement files
   - [ ] Catalog
   - [x] Inventory
 - [x] Forward new service provider metadata to Max.gov

## Analysis & notes

We need to define which fork is the _upstream_ version. We have 2 candidates: 
 - We have [the Link Digital version](https://github.com/DataShades/ckanext-saml2/blob/link-master/CHANGES.md#040)
 - We have the [OKF version](https://github.com/okfn/ckanext-saml2/blob/link-master/CHANGES.md#040)

**Both repos add support from CKAN 2.8** (and fix some issues). Link Digital did this first. We let LinkDigital know that we're going to start using their version as upstream ([#116](https://github.com/DataShades/ckanext-saml2/issues/116) is the discussion issue). 

We [discussed treating LinkDigital fork as the "official" fork with OKF](https://github.com/DataShades/ckanext-saml2/issues/114). OKF folks are open to that but their own fork has changes that should probably be reconciled in.
**Note:** The LinkDigital repository has several unresolved issues and PRs, so it may not be getting a lot of attention.

### Starting analysis for reconciliation
As a test environment for ckanext-saml2 we created [a fork of GSA/ckanext-saml2]((https://github.com/avdata99/ckanext-saml2):

```
git checkout max
# Add Link Digital repo as remote
git remote add ld git@github.com:DataShades/ckanext-saml2.git
git checkout -b datagov/ld-link-master
git fetch ld
# Rebase from "link-master" branch at Link Digital fork
git rebase ld/link-master
# fix all conflict by using link digital code
git push 
```
 - This new branch `datagov/ld-link-master` could be used as a GSA new version to continue from.
 - A [potential PR from this new branch to link digital repo](https://github.com/DataShades/ckanext-saml2/compare/link-master...avdata99:datagov/ld-link-master) could be sent to integrate GSA's changes to upstream.
 - Ensure we have tests (asked [here](https://github.com/DataShades/ckanext-saml2/issues/115)). We may need to develop these tests. **Neither Link Digital, OKF or GSA fork have tests**, it seems it's not easy to have a SAML2 service provider running locally.

## Recommendation

Wait for the analysis on #1416 about the main library used here (pysaml2)
We recommend moving to Link digital version and ensure to add a local test environment

### Catalog 2.3 -> 2.8

* Update GSA pysaml2 fork with upstream (finished) [0d]
* Get saml2 working with updated forks at current catalog-app 2.3 [1-2d]
* Port ckanext-saml2 from 2.3 -> 2.8 extension syntax and interface syntax [1-2d]
* _OPTIONAL_ Monkey-patch upstream pysaml 2 with required changes (diff `GSA..IdentityPython`) [2-3d]
* QA / Test [1-2d]

**Comment by kimwdavidson** [comment]
Aaron recommends Link Digital for upstream. Bret agrees.

**Comment by avdata99** [comment]
Related to: 
 - https://github.com/GSA/datagov-deploy/issues/414
 - https://github.com/GSA/catalog-app/issues/78

**Comment by avdata99** [comment]
Added [PR](https://github.com/GSA/inventory-app/pull/25/files) as a work in progress for this ext

**Comment by avdata99** [comment]
I left this [work in progress PR](https://github.com/GSA/inventory-app/pull/25/files) to continue from there.

**Comment by avdata99** [comment]
We need to have a conversation with @FuhuXia to discuss how to continue with this. We need to config and test this extension.

**Comment by estebanruseler** [comment]
@adborden didn't get the chance to mention this on the call. Andres has sent you a [PR](https://github.com/GSA/inventory-app/pull/25/files). Our idea here is doing work in progress PR that we discussed in one of the previous retros. 

As you'll see the [PR](https://github.com/GSA/inventory-app/pull/25/files) is to upstream your fork to the Linked Digital extension as you considered it as the "official" version.  

Once you've reviewed the PR the next steps are:
 - Start the service provider and test --> After being able to test this we'll have a clearer understanding on whether better to use the Linked Digital or to improve your fork (maybe combine the best of both worlds with Linked D and OKF). The main idea is to move to Linked Digital but testing will validate this. 
 - Analyzing the OKF extension to see if there are any improvements that should be taken from that. If we do it in your fork then update it, if we're upstreaming to Linked Digital then we can open an issue for them to improve the extension (but there are open issues there for a month... maybe they'd be happy for Datopian or GSA to be the maintainers)
 - Anyway this is TL;DR, the main point is this PR is not us saying we've finished this... can you look at what we've done so far so we'd like your input mid-way and then we can continue.

**Comment by adborden** [comment]
Looks good so far.

I want to remind folks that I'm not a fan of large PRs, so if this is not done done but still working, compatible, and a complete piece of work, we should go ahead and merge it.

**Comment by estebanruseler** [comment]
@adborden great. @avdata99  ⬆️

**Comment by avdata99** [comment]
We need to assign to @starsinmypockets to continue here

**Comment by adborden** [comment]
Quoting Andres Vazquez (2020-03-23 06:44:18)
> We need to assign to @starsinmypockets to continue here

@avdata99, maybe you should pair during the handoff.

--
Aaron D Borden
Human and hacker

**Comment by estebanruseler** [comment]
Re-assigned to Paul... and yes they will need to pair quite a bit over the next week(s).

**Comment by starsinmypockets** [comment]
I agree with the analysis presented in the issue description above. I think we should rebase datagov's `ckanext-saml2/max` branch onto the current upstream (datashades) `link-master`, keep code added to upstream, fix conflicts, and tag the result of the rebase with the same tag as the upstream. Our fork, which we will maintain while we use max.gov, will track closely to the upstream with a few necessary changes specific to max.gov. Upon release to upstream `link-master` we will receive a notification via Slack, pull the new branch, and rebase `max` to the new branch. We tag our rebased branch with the same tag as the upstream, and rebuild / run ci. This should meet the <1h criteria, though I don't know how long CI takes to run :) This should be infrequent -- we'll document the process but will not automate it.

**Comment by starsinmypockets** [comment]
@adborden @FuhuXia https://github.com/GSA/ckanext-saml2/pull/8

**Comment by starsinmypockets** [comment]
@adborden A couple fields in `sp.xml` need real-world values:

```
    'organization': {
        'name': 'Exempel AB',
        'display_name': [('Exempel AB','se'),('Example Co.','en')],
        'url':'http://www.example.com/ckan',
    },
    'contact_person': [{
        'given_name':'John',
        'sur_name': 'Smith',
        'email_address': ['john.smith@example.com'],
        'contact_type': 'technical',
        },
    ],
```

Thoughts? Feelings?

**Comment by adborden** [comment]
@starsinmypockets have you looked at https://github.com/GSA/datagov-ckan-multi/issues/346? Since the catalog-web instances are already configured with the correct configuration, they should 🤞  generate complete metadata when running the make_metadata.py from those hosts.

**Comment by kimwdavidson** [comment]
Duplicate. closing
