### ISSUE TITLE
Upgrade analytics CKAN extension

### ISSUE THREAD

**Issue by avdata99** [GSA/data.gov#1406]
## Description

As a part of a [plan to upgrade CKAN extensions](https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit?ts=5e50447f#gid=0) in use, and in order to improve the way that we [manage forks](https://github.com/GSA/datagov-deploy/wiki/Managing-Forks) we need to upgrade the [Analytics extension in use](https://github.com/GSA/ckanext-googleanalyticsbasic). ([This is part of the reduce/simplify fork epics](https://github.com/GSA/datagov-deploy/issues/1343).)

## Acceptance Criteria

 - [ ] We remove the fork(ie copy) and upgrade extension for catalog & inventory and we have tested environment (needs to be signed off by GSA before proceeding)
 - [ ] When there's a new release upstream, we can get onto it in under an hour
 - [ ] When there's a new release upstream, we see a notification in a Slack channel
 - [ ] If the upstream maintainers don't already use versioning, there's an issue in their tracker requesting they do.
 - [ ] If the upstream maintainers don't already have tests, there's an issue in their tracker requesting they add them. 
 - [ ] We have tests for this extension running in CI (upstream [have tests](https://github.com/ckan/ckanext-googleanalytics#testing) but no CI)

## Tasks
 - [ ] Define if we really need multiple tracker IDs. If we need this should be added as a new feature to upstream and create a PR for it.
 - [ ] If the [US Digital Analytics Program](https://analytics.usa.gov) requires to use the [Universal-Federated-Analytics-Min.js](https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?agency=GSA) file, it should be added as extra code in a different HTML file or maybe it should live in a new CKAN extension.
 - [x] Create an issue in upstream to add CI to run tests in each commit and PR: [here](https://github.com/ckan/ckanext-googleanalytics/issues/44)
 - [ ] Make a recommendation to GSA to re analytics CKAN extension 
 - [ ] Connect our Slack channel with new release news in upstream
 - [ ] Apply this new URL in requirement files
   - [ ] Catalog
   - [ ] Inventory

## Analysis & notes

We're using a copy-based (not a fork) [Google Analytics extension](https://github.com/GSA/ckanext-googleanalyticsbasic)
We consider as upstream the [ckan/ckanext-googleanalytics](https://github.com/ckan/ckanext-googleanalytics) repo

`GSA/ckanext-googleanalyticsbasic` is a simple implementation of a single feature from `ckan/ckanext-googleanalytics`. It adds Google Analytics asynchronous tracking code to your page headers for page tracking. 

It looks like most of the code in `plugin.py` from `ckanext-googleanalyticsbasic` (a good portion of the code) is identical to what's found in `ckanext-googleanalytics`. If it doesn't work out of the box, it shouldn't take much work to migrate to `ckan/ckanext-googleanalytics`, and it will add a lot of optional functionality. The extra functionality would include resource download tracking, some API usage tracking, custom event tracking for extensions, and editing user profiles.

More detailed code analysis is [here](https://hackmd.io/0M_LRxtrTm2VRM77FEeIYg)

Two key points:
1)  Is to understand if they need multiple tracking ids... Main point of the fork/copy is to manage multiple ids but that doesn't seem in use
2) There is a small script for the Open Analytics 

## Recommendation

Recomendation is to use the community version with an GSA extension to customise (eg apply google analytics id(s)). In theory it could be handled with a GSA fork but would be better to upstream this. 

This extension would be a super small script if 1 tracking id is needed. If multiple tracking ids are needed would send a PR to upstream to include this ability... if not we'd need to include this in the extension (needs further analysis).
