### ISSUE TITLE
Upgrade ckanext-ga-report

### ISSUE THREAD

**Issue by thejuliekramer** [GSA/data.gov#1407]
## Feature

As a part of a [plan to upgrade CKAN extensions](https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit?ts=5e50447f#gid=0) in use, and in order to improve the way that we manage forks we need to upgrade the [reporting extension](https://github.com/GSA/ckanext-ga-report) in use

The upstream fork is [here](https://github.com/datagovuk/ckanext-ga-report), and the version being used is only 3 commits behind.

The datagov version here is 57 commits ahead of upstream, so it is possible to see if we can move those commits upstream.

## Anticipated/hypothesized benefits

- We are going to solve compatibility issues. We are using old repos
- We are going to use a community supported version.

## Tasks

- [ ] Add CI to ckanext-ga-report
- [ ] Catch up with upstream branch (3 commits)
- [ ] Talk to owners of upstream repository if we can move our 57 commits upstream
- [ ] Do some basic and manual tests with Catalog and Inventory apps
- [ ] Apply this new URL in requirement files
  - [ ] Catalog
  - [ ] Inventory
