### ISSUE TITLE
Upgrade ckanext-harvest in the catalog-app

### ISSUE THREAD

**Issue by avdata99** [GSA/data.gov#1408]
## Description

In the [catalog-app](https://github.com/GSA/catalog-app) we are using [a fork](https://github.com/GSA/ckanext-harvest) of the [official ckanext-harvest](https://github.com/ckan/ckanext-harvest) extension (on the datagov branch). 

As a part of a [plan to upgrade CKAN extensions](https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit?ts=5e50447f#gid=0) in use, and in order to improve the way that we [manage forks](https://github.com/GSA/datagov-deploy/wiki/Managing-Forks) we need to upgrade this [ckanext-harvest extension](https://github.com/GSA/ckanext-harvest). ([This is part of the reduce/simplify fork epics](https://github.com/GSA/datagov-deploy/issues/1343).)

## Acceptance Criteria

 - [ ] When there's a new release upstream, we can get onto it in under an hour
 - [ ] When there's a new release upstream, we see a notification in a Slack channel
 - [ ] If the upstream maintainers don't already use versioning, there's an issue in their tracker requesting they do.
 - [ ] If the upstream maintainers don't already have tests, there's an issue in their tracker requesting they add them. 
 - [x] We have tests for this extension running in CI. Done [here](https://travis-ci.org/github/ckan/ckanext-harvest) if we use upstream

## Tasks

 - [ ] Create a test environment with the catalog-app
 - [ ] Test this extension and other depending extensions
 - [ ] Make recommendation to GSA team
 - [ ] Measure the effort to move the catalog-app to this official harvest version.
 - [ ] Connect our Slack channel with new release news in upstream

## Analysis & notes

Our fork is Ahead in 184 commits and Behind 498 commits. These versions have diverged a lot. This [potential PR](https://github.com/GSA/ckanext-harvest/compare/datagov...ckan:v1.2.0) show us the changes between our `datagov` branch and [harvest v1.2](https://github.com/ckan/ckanext-harvest/tree/v1.2.0) (which works with python 2 and CKAN 2.8).  

### Commit dif list

Created a list of commits that are in **gsa/datagov** but not in **ckan/master**
```
git log gsa/datagov --not origin/master --pretty=format:"%an|%ad|%s|%H" 
```
Results [here](https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit?ts=5e4177f8#gid=1639967021)

## Recommendation

The official repo has [tests and CI](https://travis-ci.org/ckan/ckanext-harvest). It is a very active, well documented and widely used version in the CKAN community. **We recommend to move to this version**

TODO This needs more detail...

**Comment by avdata99** [comment]
Created a list of commits that are in **gsa/datagov** but not in **ckan/master**
```
git log gsa/datagov --not origin/master --pretty=format:"%an|%ad|%s|%H" 
```
Results [here](https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit?ts=5e4177f8#gid=1639967021)

**Comment by kimwdavidson** [comment]
Closing. Taking new approach
