### ISSUE TITLE
Upgrade ckanext-harvest in the inventory-app

### ISSUE THREAD

**Issue by avdata99** [GSA/data.gov#1414]
## Description

In the [inventory-app](https://github.com/GSA/inventory-app) we are using [an especific commit](https://github.com/ckan/ckanext-harvest/commit/13dbb1eea428e6b274f98c36bf29d42e62a70af7) (and old one, from Jul 30, 2014) of the [official ckanext-harvest](https://github.com/ckan/ckanext-harvest) extension. 

As a part of a [plan to upgrade CKAN extensions](https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit?ts=5e50447f#gid=0) in use, and in order to improve the way that we [manage forks](https://github.com/GSA/datagov-deploy/wiki/Managing-Forks) we need to upgrade this extension in the Inventory app.

## Acceptance Criteria

 - [ ] When there's a new release upstream, we can get onto it in under an hour
 - [ ] When there's a new release upstream, we see a notification in a Slack channel
 - [ ] If the upstream maintainers don't already use versioning, there's an issue in their tracker requesting they do.
 - [x] If the upstream maintainers don't already have tests, there's an issue in their tracker requesting they add them. 
 - [x] We have tests for this extension running in CI. Done [in upstream](https://travis-ci.org/github/ckan/ckanext-harvest)

## Tasks

 - [ ] Analyze (@jbrown-xentity showed this in a comment) why this ext is not added as a plugin in the [config](https://github.com/GSA/datagov-deploy/blob/master/ansible/roles/software/ckan/inventory/templates/etc/ckan/production.ini#L106).
 - [ ] Create a test environment with the inventory-app
 - [ ] Test this extension and other depending extensions
 - [ ] Measure the effort to move the inventory-app to this official harvest version.
 - [ ] Connect our Slack channel with new release news in upstream

## Analysis & notes

The official repo has [tests and CI](https://travis-ci.org/ckan/ckanext-harvest). It is a very active, well documented and widely used version in the CKAN community. **We recommend to update to 1.2.0 version** (in 2014 version 0.0.1 did not yet exist)

This commit is Behind 510 commits. Like at #1408, these versions have diverged a lot. This [potential PR](https://github.com/ckan/ckanext-harvest/compare/13dbb1e...v1.2.0) show us the changes between our commit and [harvest v1.2](https://github.com/ckan/ckanext-harvest/tree/v1.2.0) (which works with python 2 and CKAN 2.8).  

**v1.2 version have tests and CI and 6 years of improvements and bugfixes**

It's a good idea to define an environment with the inventory-app and just change harvest to the official version and run tests for this ext and other harvest extensions.  

## Recommendation

Analyze #1408 and then move to upstream.

**Comment by jbrown-xentity** [comment]
Actually, this has been downloaded but never utilized in Inventory. Currently the extension is not enabled (see current [deployed config](https://github.com/GSA/datagov-deploy/blob/master/ansible/roles/software/ckan/inventory/templates/etc/ckan/production.ini#L106)) for confirmation.
Harvester is used on catalog, however... @avdata99

**Comment by avdata99** [comment]
I think [datajson ext is in use](https://github.com/GSA/datagov-deploy/blob/master/ansible/roles/software/ckan/inventory/templates/etc/ckan/production.ini#L106) and [requires harvest ext](https://github.com/GSA/ckanext-datajson/blob/master/ckanext/datajson/harvester_base.py#L11-L13)
I think we need to upgrade this config file to add harvest ext.

**Comment by nickumia-reisys** [comment]
Inventory never had `ckanext-harvest` ... at least as long as I've been around and from the searchable history of inventory repository...

**Comment by jbrown-xentity** [comment]
Initially it was a "requirement" for ckanext-datajson, as the harvester part of ckanext-datajson needed ckanext-harvest. It was a purely code dependency thing, inventory hasn't harvested DCAT-US files in my time with data.gov.
