### ISSUE TITLE
Upgrade ckanex-qa in catalog-app

### ISSUE THREAD

**Issue by avdata99** [GSA/data.gov#1415]
## Description

In the [catalog-app](https://github.com/GSA/catalog-app) we are using [a fork](https://github.com/GSA/ckanext-qa) of the [official ckanext-qa](https://github.com/ckan/ckanext-qa) extension (on the datagov branch). 

As a part of a [plan to upgrade CKAN extensions](https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit?ts=5e50447f#gid=0) in use, and in order to improve the way that we [manage forks](https://github.com/GSA/datagov-deploy/wiki/Managing-Forks) we need to upgrade this extension.

## Acceptance Criteria

 - [ ] When there's a new release upstream, we can get onto it in under an hour
 - [ ] When there's a new release upstream, we see a notification in a Slack channel
 - [ ] If the upstream maintainers don't already use versioning, there's an issue in their tracker requesting they do.
 - [ ] If the upstream maintainers don't already have tests, there's an issue in their tracker requesting they add them. 
 - [x] We have tests for this extension running in CI. Done [in upstream](https://travis-ci.org/github/ckan/ckanext-qa)

## Tasks

 - [ ] Create a test environment with the catalog-app
 - [ ] Test this extension in this environment
 - [ ] Measure the effort to move the catalog-app to this upstream version.
 - [x] Upstream do not use tags for versions, do not have a change log file and version is 2.0 since 4 years. Create an issue to start versioning. [Issue created at usptream](https://github.com/ckan/ckanext-qa/issues/69)
 - [ ] Connect our Slack channel with new release news in upstream

## Analysis & notes

The official repo already has [tests and CI](https://travis-ci.org/ckan/ckanext-qa). It is active.
GSA version last updated: November 10, 2017
Upstream version last updated: November 22, 2019

Our fork is Ahead in 81 commits and Behind 40 commits but these versions **have not diverged a lot**. This [potential PR](https://github.com/GSA/ckanext-qa/compare/datagov...ckan:master) show us the changes between our `datagov` branch and upstream. **The changes do not seem significant**. It should not require much effort updating to this version.  

## Recommendations

We recommend moving to upstream version

**Comment by nickumia-reisys** [comment]
We are no longer on a fork and this ticket is superseded by
- https://github.com/GSA/data.gov/issues/3986
