### ISSUE TITLE
Upgrade ckanext-report in catalog-app

### ISSUE THREAD

**Issue by avdata99** [GSA/data.gov#1417]
## Description

In the [catalog-app](https://github.com/GSA/catalog-app) we are using [a fork](https://github.com/GSA/ckanext-report) of the [ckanext-qa](https://github.com/davidread/ckanext-report) extension (on the datagov branch). We are not sure about which repo should be consider upstream.

As a part of a [plan to upgrade CKAN extensions](https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit?ts=5e50447f#gid=0) in use, and in order to improve the way that we [manage forks](https://github.com/GSA/datagov-deploy/wiki/Managing-Forks) we need to upgrade this extension.

## Acceptance Criteria

 - [ ] When there's a new release upstream, we can get onto it in under an hour
 - [ ] When there's a new release upstream, we see a notification in a Slack channel
 - [ ] If the upstream maintainers don't already use versioning, there's an issue in their tracker requesting they do.
 - [ ] If the upstream maintainers don't already have tests, there's an issue in their tracker requesting they add them. 
 - [ ] We have tests for this extension running in CI (upstream have no tests or CI)

## Tasks

 - [ ] Create a test environment with the catalog-app
 - [ ] Ask upstream for tests and CI
 - [ ] Test (by now) manually this extension in this environment.
 - [ ] Measure the effort to move the catalog-app to this upstream version.
 - [ ] Upstream do not use tags for versions, do not have a change log file and version is 0.1 from the begining (6 years ago). Ask upstream for improve versioning.
 - [ ] If we consider this extension as an important one, do a deep analysis on [forks](https://github.com/davidread/ckanext-report/network) to check for bug fixes or improvements.
 - [ ] Connect our Slack channel with new release news in upstream

## Analysis & notes

DavidRead version starts this repo (we consider this repo upstream by now). Last update: Mar 22, 2017
GSA version last update: March 9, 2016

Other repos continue working on it until today. **They just work to upgrade to py3 and add translation capabilities**
![forks](https://i.imgur.com/UCOSjA7.png)

Our fork is Ahead in 36 commits and Behind 49 commits but these versions **have not diverged a lot**. This [potential PR](https://github.com/GSA/ckanext-report/compare/datagov...davidread:master) show us the changes between our `datagov` branch and upstream. **The changes do not seem significant**. It should not require much effort updating to this version.  

It's a good idea to define an environment with the catalog-app and just change ckanext-report to the official version and run tests.

## Recommendation

Define the upstream version and move to it

**Comment by nickumia-reisys** [comment]
https://github.com/ckan/ckanext-report/ is the upstream version and we have it integrated on current catalog,
- https://github.com/GSA/data.gov/issues/3957
