### ISSUE TITLE
Upgrade ckanext-spatial in the catalog-app

### ISSUE THREAD

**Issue by avdata99** [GSA/data.gov#1420]
## Description

In the [catalog-app](https://github.com/GSA/catalog-app) we are using [a fork](https://github.com/GSA/ckanext-spatial) of the [official ckanext-spatial](https://github.com/ckan/ckanext-spatial) extension (on the datagov branch). 

As a part of a [plan to upgrade CKAN extensions](https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit?ts=5e50447f#gid=0) in use, and in order to improve the way that we [manage forks](https://github.com/GSA/datagov-deploy/wiki/Managing-Forks) we need to upgrade this extension.

## Acceptance Criteria

 - [ ] When there's a new release upstream, we can get onto it in under an hour
 - [ ] When there's a new release upstream, we see a notification in a Slack channel
 - [ ] If the upstream maintainers don't already use versioning, there's an issue in their tracker requesting they do.
 - [x] If the upstream maintainers don't already have tests, there's an issue in their tracker requesting they add them. 
 - [x] We have tests for this extension running in CI. Done [in upstream](https://travis-ci.org/github/ckan/ckanext-spatia)

## Tasks

 - [ ] Create a test environment with the catalog-app
 - [ ] Upstream CI [fails on CKAN <2.8](https://travis-ci.org/ckan/ckanext-spatial). Fix it for the version we need.
 - [x] Upstream do not use tags for versions, do not have a change log file and version is 0.2 since 9 years ago. Ask upstream for improve versioning: [Done](https://github.com/ckan/ckanext-spatial/issues/242)
 - [ ] Test this extension
     - [ ] Test geodatagov in catalog-app with spatial using upstream
 - [ ] Measure the effort to move the catalog-app to this official spatial version.

## Analysis & notes

The official repo has [tests and CI](https://travis-ci.org/ckan/ckanext-spatial). It is a very active, well documented and widely used version in the CKAN community. 

Our fork is Ahead in 167 commits and Behind 120 commits. This [potential PR](https://github.com/GSA/ckanext-spatial/compare/datagov...ckan:master) show us the changes between our `datagov` branch and master at upstream

In a first analysis, we can see that in the GSA version we have a plugin cswserver/CatalogueServiceWeb with tests. This plugin was removed from upstream. 

It's a good idea to define an environment with the catalog-app and just change spatial ext to the official version and run tests for this ext and GeoDataGov extensions.  

## Recommendation

We recommend moving to upstream version

**Comment by jbrown-xentity** [comment]
I know for the CSW feature, there are discussions about pushing that necessity onto the geoplatform group, as that is a specific geospatial feature and not a core part of data.gov. It may still be necessary long term, but it is an ongoing discussion.

**Comment by avdata99** [comment]
This is [done in catalog-next](https://github.com/GSA/catalog.data.gov/blob/master/requirements/pyproject.toml#L20:L20) and probably should be closed

**Comment by jbrown-xentity** [comment]
We are still on a fork, and still need to merge upstream and/or move work to a different extension in order to remove this fork.

**Comment by nickumia-reisys** [comment]
Superseded by
- https://github.com/GSA/data.gov/issues/3938
