### ISSUE TITLE
Upgrade OWSlib is spatial CKA extension

### ISSUE THREAD

**Issue by avdata99** [GSA/data.gov#1421]
## Description

In the [catalog-app](https://github.com/GSA/catalog-app) we are using [a fork](https://github.com/GSA/ckanext-spatial) of the [official ckanext-spatial](https://github.com/ckan/ckanext-spatial) extension. Our extension uses a [custom OWSLib version](https://github.com/GSA/OWSLib). 

The official repo has [tests](https://github.com/geopython/OWSLib/tree/master/tests). It is a very active, well documented and widely used version. **We recommend to move to this version**

## Acceptance Criteria

 - [ ] When there's a new release upstream, we can get onto it in under an hour
 - [ ] When there's a new release upstream, we see a notification in a Slack channel
 - [ ] If the upstream maintainers don't already use versioning, there's an issue in their tracker requesting they do.
 - [ ] If the upstream maintainers don't already have tests, there's an issue in their tracker requesting they add them. 
 - [ ] We have a test environment for this extension

## Tasks

 - [ ] Analyze [our 4 changes](https://github.com/geopython/OWSLib/compare/master...GSA:catalog-0.8.6) and define if they are important.
 - [ ] Connect our Slack channel with new release news in upstream

## Analysis & notes

Using upstream in spatial ext is (#1420), in fact, [an upgrade to OWSLib](https://github.com/ckan/ckanext-spatial/blob/master/pip-requirements.txt#L4).  

Our fork is Ahead in 4 commits and Behind 792 commits. This [potential PR](https://github.com/geopython/OWSLib/compare/master...GSA:catalog-0.8.6) show us the changes of this 4 commits that we changed (years ago)

If the upgrade at #1420 works maybe we can just close this.

## Recommendation

Finish #1420 and the move to upstream

**Comment by jbrown-xentity** [comment]
Moving away from OWSlib and CKAN harvesting, closing.
