### ISSUE TITLE
Upgrade datapusher in inventory app

### ISSUE THREAD

**Issue by avdata99** [GSA/data.gov#1422]
## Description

In the [inventory-app](https://github.com/GSA/inventory-app) we are using [a fork](https://github.com/GSA/datapusher/) of the [official datapusher](https://github.com/ckan/datapusher) extension. 

As a part of a [plan to upgrade CKAN extensions](https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit?ts=5e50447f#gid=0) in use, and in order to improve the way that we [manage forks](https://github.com/GSA/datagov-deploy/wiki/Managing-Forks) we need to upgrade this extension.

## Acceptance Criteria

 - [x] When there's a new release upstream, we can get onto it in under an hour
 - [x] When there's a new release upstream, we see a notification in a Slack channel
 - [x] If the upstream maintainers don't already use versioning, there's an issue in their tracker requesting they do.
 - [x] If the upstream maintainers don't already have tests, there's an issue in their tracker requesting they add them. 
 - [x] We have a test environment for this extension

## Tasks

 - [x] Analyze which of the tagged versions are the last for CKAN 2.8. Avoid using CKAN 2.9 changes if they exist.
 - [x] Create a test environment with the inventory-app
 - [x] Test this extension
 - [x] Measure the effort to move the inventory-app to this official version.
 - [x] Connect our Slack channel with new release news in upstream

## Analysis & notes

The official repo has [tests and CI](https://travis-ci.org/ckan/datapusher). It is a very active, well documented and widely used version in the CKAN community.

Our fork is Ahead in 11 commits and Behind 85 commits. This [potential PR](https://github.com/ckan/datapusher/compare/master...GSA:master) show us the changes of our 11 commits. 

[Lasts commit from Dec 2019](https://github.com/GSA/datapusher/commit/0d3c34768c1fb6e876d085f3795e87fbc2906664) seems a kind of custom hotfix that maybe should be fixed in a different way and sent changes to upstream.

It's a good idea to define an environment with the inventory-app and just change the datapusher to the official version and run tests.  

## Recommendation

We recommend moving to upstream.
Analyze to move to [xloader](https://github.com/ckan/ckanext-xloader) (a new extension designed as a replacement for DataPusher)

**Comment by adborden** [comment]
One of the patches on datapusher is a switch from using application/json to application/x-www-form-urlencoded. I _think_ this is because inventory [ckan is using the wrong version of repoze.who==1.0.18](https://github.com/GSA/catalog-app/issues/78). I think this means we'll want to address Inventory ckan before taking on datapusher (and then we can drop those patches).

**Comment by avdata99** [comment]
> One of the patches on datapusher is a switch from using application/json to application/x-www-form-urlencoded. I _think_ this is because inventory [ckan is using the wrong version of repoze.who==1.0.18](https://github.com/GSA/catalog-app/issues/78). I think this means we'll want to address Inventory ckan before taking on datapusher (and then we can drop those patches).

The inventory-app, at the new branch inventory_ckan_2.8, [we already are using repoze.who==2.3](https://github.com/GSA/inventory-app/blob/inventory_ckan_2.8/requirements.txt#L49).

**Comment by avdata99** [comment]
Work in progress [PR](https://github.com/GSA/inventory-app/pull/28/files). Not ready yet.

**Comment by avdata99** [comment]
We have 3 option here:
 - Move to XLoader: This new [PR](https://github.com/GSA/inventory-app/pull/29) uses [XLoader](https://github.com/ckan/ckanext-xloader) which is better for this.
 - Include Datapusher with code: This [PR](https://github.com/GSA/inventory-app/pull/28) to use datapusher from code.
 - Include a buit image of datapusher: [PR (ready to go)](https://github.com/GSA/inventory-app/compare/inventory_ckan_2.8...avdata99:inventory_ckan_2.8_builded_datapusher?expand=1)

The 3 options are working. The XLoader seems to be the best option here

**Comment by kimwdavidson** [comment]
Andres to connect 3rd PR and close other two

**Comment by adborden** [comment]
I captured the recommendation to use ckanext-xloader in https://github.com/GSA/datagov-deploy/issues/1486, feel free to add additional details.

**Comment by avdata99** [comment]
Closed PR for XLoader and datapusher with code.
Added a [final PR](https://github.com/GSA/inventory-app/pull/31/)
If approved, we can continue with the missing tasks

**Comment by avdata99** [comment]
They usually change version numbers
![image](https://user-images.githubusercontent.com/3237309/77542960-bedbc100-6e85-11ea-8300-f25d1f4ea15c.png)

**Comment by estebanruseler** [comment]
Synced with Andres so we move this from 90% done to 100% done. Agreed:
 - Double-check that we have requested semantic versioning and testing.Task-list to be updated. 
 - The other o/s items are the Slack notifications. We will create a ticket for this to be considered as part of next sprint

**Comment by avdata99** [comment]
We have tests [at upstream](https://github.com/ckan/datapusher#development) and they work fine.

![image](https://user-images.githubusercontent.com/3237309/77543524-96a09200-6e86-11ea-8823-f0935861176c.png)

We also add a [test in docker](https://github.com/avdata99/inventory-app/blob/inventory_ckan_2.8_builded_datapusher/tests/test.bats#L108-L116)

**Comment by estebanruseler** [comment]
Blocked by slack notifications. This should be easy and we just need to sync with Bret/Aaron on the scrum call.

**Comment by avdata99** [comment]
Added to releases RSS to datagov-notifications slack channel
```
/feed suscribe https://github.com/ckan/datapusher/releases.atom
```

**Comment by avdata99** [comment]
Closing since is done
