### ISSUE TITLE
Upgrade s3 filestore ext in inventory app

### ISSUE THREAD

**Issue by avdata99** [GSA/data.gov#1423]
## Description

In the [inventory-app](https://github.com/GSA/inventory-app) we are using [a fork](https://github.com/GSA/ckanext-s3filestore/) of the [official extension](https://github.com/okfn/ckanext-s3filestore). 

As a part of a [plan to upgrade CKAN extensions](https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit?ts=5e50447f#gid=0) in use, and in order to improve the way that we [manage forks](https://github.com/GSA/datagov-deploy/wiki/Managing-Forks) we need to upgrade this extension.

## Acceptance Criteria 

 - [x] We define the upstream version and add our changes if they are important. **OKF is upstream**
 - [ ] When there's a new release upstream, we can get onto it in under an hour
 - [ ] When there's a new release upstream, we see a notification in a Slack channel
 - [ ] If the upstream maintainers don't already use versioning, there's an issue in their tracker requesting they do.
 - [ ] There's an issue requesting versioning.
 - [ ] We have a test environment for test this updated extension

## Tasks

 - [ ] [Analyze Datopian, LinkDigital and other forks](https://github.com/okfn/ckanext-s3filestore/network) for last updates or to change upstream.
 - [ ] Create a test environment with upstream in the inventory-app
 - [ ] Test this extension
 - [ ] Measure the effort to move the inventory-app to this official version.
 - [ ] Connect our Slack channel with new release news in upstream
 - [ ] Write an issue in the upstream repo to start versioning (e are in 0.0.5 from 3 years)

## Analysis & notes

The official repo has [tests and CI](https://travis-ci.org/okfn/ckanext-s3filestore) but is failing. We have ~1 year without updates. 

Our fork is Ahead in just 2 commits and Behind 46 commits. This [comparison](https://github.com/okfn/ckanext-s3filestore/compare/master...GSA:master) show us the changes in our 2 commits. [Here](https://github.com/GSA/ckanext-s3filestore/compare/master...okfn:master) we can see the changes of the 46 commits in upstream.
GSA last version is from September 2016, Upstream is from March 2019

GSA version just adds an option to use _aws_use_ami_role_. We can just select a new upstream and create a fork with this change (and send it to upstream)

### Recommendations

We recommend using the OKF version as upstream. If we really need this _ami role_ functionality we should create a fork, add this functionality and send a PR to upstream.
If this is an important extension for GSA it's a good idea to analyze last commits on Datopian, LinkDigital and other forks to ensure we have selected the correct upstream.
