### ISSUE TITLE
Upgrade USMetadata at inventory app

### ISSUE THREAD

**Issue by avdata99** [GSA/data.gov#1424]
## Description

In the [inventory-app](https://github.com/GSA/inventory-app) we are using [a fork](https://github.com/GSA/USMetadata) of an abandoned repo.

As a part of a [plan to upgrade CKAN extensions](https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit?ts=5e50447f#gid=0) in use, and in order to improve the way that we [manage forks](https://github.com/GSA/datagov-deploy/wiki/Managing-Forks) we need to analyze if an upgrade here is needed.

## Acceptance Criteria

 - [ ] This extension includes the best updates for other forks.
 - [ ] There's an issue requesting versioning.
 - [ ] We have a test environment for test this updated extension

## Tasks
 - [ ] Analyze [Adam's changes](https://github.com/GSA/USMetadata/compare/master...akariv:master) and define if we should use them.
 - [ ] Analyze [Ljupka's changes](https://github.com/GSA/USMetadata/compare/master...ljpetrova:master) and define if we should use them.
 - [ ] Fix errors at [CI](https://travis-ci.org/GSA/USMetadata)
 - [ ] Create a test environment with the inventory-app
 - [ ] Improve tests in this extension
 - [ ] Measure the effort to move the inventory-app to a new official version.
 - [ ] Write an issue to start versioning (e are in 0.2.1 from 7 years)

## Analysis & notes

Our repo [has test and CI](https://travis-ci.org/GSA/USMetadata) but are failing.
We can consider our fork as the upstream version but some forks continue working here:
 - @akariv [version](https://github.com/akariv/USMetadata): do some work in backend. We are 24 commits behind
 - @ljpetrova [version](https://github.com/ljpetrova/USMetadata): do some work in frontend. We are 29 commits behind

Note: Adam starts working from Ljupka repo. Maybe that repo was considered upstream at that time.
See [the network graph](https://github.com/GSA/USMetadata/network):

![](https://i.imgur.com/o4RInCO.png)

## Recommendation

Analyze the changes in this forks and upgrade our version if needed.

**Comment by adborden** [comment]
Seems there is some confusion here. We've unassigned @pjsharpe07 who is not working on this. He was focused on only making sure USMetadata was working on the inventory CKAN 2.8 fork. I'm going to move this back to the sprint backlog and someone from ckan-multi team should pick this up.

**Comment by starsinmypockets** [comment]
@adborden Looks like in terms of forks there is very little to do here until we are upgrading to 2.8

Complete analysis here:
https://gist.github.com/starsinmypockets/306f372141e95a3d8325bdd43a041be5

**Comment by adborden** [comment]
@starsinmypockets 2.8 is in progress here https://github.com/GSA/inventory-app/tree/inventory_ckan_2.8, is there something else you need in order to continue this work?

**Comment by starsinmypockets** [comment]
@adborden should I continue the work against 2.8 in progress?

**Comment by adborden** [comment]
Yes, why don't you pull in @avdata99 as a pair.

One thing I want to call out: the Inventory 2.8 branch is using the [datopian fork](https://github.com/GSA/inventory-app/blob/inventory_ckan_2.8/requirements.txt#L3), so whatever fixes are necessary for USMetadata should be made so that we can switch back to using the GSA version.

**Comment by nickumia-reisys** [comment]
Superseded by
- https://github.com/GSA/datagov-ckan-multi/issues/581
