### ISSUE TITLE
Upgrade Archiver extension

### ISSUE THREAD

**Issue by avdata99** [GSA/data.gov#1426]
## Description

In the [catalog-app](https://github.com/GSA/catalog-app) we are using [a fork](https://github.com/GSA/ckanext-archiver) of the [official ckanext-archiver](https://github.com/ckan/ckanext-archiver) extension (on the datagov branch). 

As a part of a [plan to upgrade CKAN extensions](https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit?ts=5e50447f#gid=0) in use, and in order to improve the way that we [manage forks](https://github.com/GSA/datagov-deploy/wiki/Managing-Forks) we need to upgrade this extension.

## Acceptance Criteria

 - [ ] When there's a new release upstream, we can get onto it in under an hour
 - [ ] When there's a new release upstream, we see a notification in a Slack channel
 - [x] If the upstream maintainers don't already use versioning, there's an issue in their tracker requesting they do.
 - [ ] If the upstream maintainers don't already have tests, there's an issue in their tracker requesting they add them. 
 - [x] We have tests for this extension running in CI. Done [here](https://travis-ci.org/github/ckan/ckanext-archiver) if we use upstream

## Tasks

 - [ ] Create a test environment with the catalog-app
 - [ ] Test this extension
 - [x] Upstream do not use tags for versions, do not have a change log file and version is 2.0.0 since 4 years ago. Ask upstream for improve versioning: [Done](https://github.com/ckan/ckanext-archiver/issues/76)
 - [ ] Measure the effort to move the catalog-app to this official archiver version.
 - [ ] Check if the custom broken link functionality is required. If it is, look into pulling some, or all, of the **GSA** code related to this **upstream**.
- [ ] Check if the bulk update code is required. If it is, look into pulling some, or all, of the **GSA** code related to this **upstream**.

The official repo has [tests and CI](https://travis-ci.org/ckan/ckanext-archiver). It is an active repo.

## Analysis & notes

There are 2 main differences between the GSA fork and upstream. The first is a custom implementation of displaying whether a link is broken, on the package page itself. This is something that’s listed as TODO upstream, so we might be able to use some of this code there. The second change is a custom bulk resource update function. Some of this might also be useful upstream.

Our fork is [Ahead in 43 commits](https://github.com/ckan/ckanext-archiver/compare/master...GSA:datagov) and [behind 69 commits](https://github.com/GSA/ckanext-archiver/compare/datagov...ckan:master). These links show us the changes between our `datagov` branch and master at upstream.

### Recommendations

We recommend to move to the community version.

**Comment by nickumia-reisys** [comment]
We are using the upstream version of archiver, but there are some issues with production,
- https://github.com/GSA/data.gov/issues/3957
- https://github.com/GSA/data.gov/issues/3986
