### ISSUE TITLE
cloud.gov-based SSP for dashboard

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1428]
## User Story

In order for the data.gov dashboard to enter the GSA Assessment and Authorization (A&A) process, the GSA OCISO representatives require a complete System Security Plan (SSP) that covers the data.gov dashboard under the [Moderate NIST requirements](https://nvd.nist.gov/800-53/Rev4/impact/moderate).

### Acceptance Criteria
- [x] GSA OCISO has an SSP for the dashboard application with reasonable content in all sections.

## Details

This will involve writing the SSP and spawning issues to generate any necessary monitoring, testing, or missing policies. We can use the LATO materials generated for another TTS app running on cloud.gov, eg TouchPoints, as a starting point.

Reference materials:
- TTS' [Before You Ship](https://before-you-ship.18f.gov/) guide
- [GSA LATO template for cloud.gov-hosted apps](https://docs.google.com/document/d/1tVbH39TFfvSaBbjWfLaR3GLOuvsLuhLFJ75xKowEV5c/edit)
- [SSP for Touchpoints, with which our ISSO will be familiar](https://docs.google.com/document/d/1RtMfKUOSPvYtG0XLIusYU-CJv4UM7Lv5UaBzhV6fzzo/edit?ts=5e459a17)
- [Source-of-truth for compliance docs](https://drive.google.com/drive/folders/0B5Pp9m0GlZnvNnRiWEpCZGZFQnM)

## Tasks/stories:
- [x] Fill out all control narratives (by June)
  - [x] Carry over relevant [P1+LATO control narratives](https://docs.google.com/spreadsheets/d/1hnDH3DSbRMBsi6SFpQb0ZvJTlDRC57hGT1RtXQb_aZA/edit#gid=1843719707&fvid=1294579545) from [the Touchpoints example](https://docs.google.com/document/d/1RtMfKUOSPvYtG0XLIusYU-CJv4UM7Lv5UaBzhV6fzzo/edit#heading=h.1v1yuxt)
  - [x] Ensure all [P1 (non-LATO) controls](https://docs.google.com/spreadsheets/d/1hnDH3DSbRMBsi6SFpQb0ZvJTlDRC57hGT1RtXQb_aZA/edit#gid=1843719707&fvid=2107946104) have a narrative
  - [x] Ensure all [P2 controls](https://docs.google.com/spreadsheets/d/1hnDH3DSbRMBsi6SFpQb0ZvJTlDRC57hGT1RtXQb_aZA/edit#gid=1843719707&fvid=1861982652) have a narrative

**Comment by mogul** [comment]
Met to discuss how to tackle document revisions. Jason needs GDrive access to be able to add new folders and files.

**Comment by mogul** [comment]
AC control pairing planned for later today.

**Comment by mogul** [comment]
Planning to break this up into one issue per control-family for better flow control.
