### ISSUE TITLE
Upgrade datajson ext in catalog and inventory app

### ISSUE THREAD

**Issue by avdata99** [GSA/data.gov#1429]
## Description

In catalog and inventory apps we are using [a fork](https://github.com/GSA/ckanext-datajson) of the Data.json extension. We use branch `master` in inventory and `datagov` in the catalog app.

As a part of a [plan to upgrade CKAN extensions](https://docs.google.com/spreadsheets/d/1LgVvgiUC5Vc-OQaSmtvQNlTFLhs3Mho65ekggYEiYh4/edit?ts=5e50447f#gid=0) in use, and in order to improve the way that we [manage forks](https://github.com/GSA/datagov-deploy/wiki/Managing-Forks) we need to upgrade this extension.

## Acceptance Criteria

 - [ ] We have an upstream version defined
 - [ ] If we define to use Datopian version
     - [ ] When there's a new release upstream, we can get onto it in under an hour
     - [ ] When there's a new release upstream, we see a notification in a Slack channel
 - [ ] We have tagged versions and clear policy about it
 - [ ] We have tests for this extension running in CI

## Tasks

 - [ ] Define if GSA wants to continue its own repo as upstream.
 - [ ] If we define to use Datopian version
     - [ ] Create a test environment with the catalog-app
     - [ ] Test this extension
     - [ ] Measure the effort to move the catalog-app to this official archiver version.
 - [ ] If we use GSA version
     - [ ] Measure the effort to merge branches to use the same version in both apps.
 - [ ] We have tagged versions. We must define a clear policy for this and create a changelog file to clarify.

## Analysis & notes

**There is no version that can be considered upstream**. Datopian also has [a version](https://github.com/datopian/ckanext-datajson) based on a previous [forks analysis](https://github.com/datopian/ckanext-datajson/blob/e32760dde6825d48bb796a446e65eebe046893ed/cherry-picking-from-other-forks.md). Datopian added some functionality to allow different schemas.

Both repos have tests and CI ([datopian](https://circleci.com/gh/datopian/ckanext-datajson) and [GSA](https://circleci.com/gh/gsa/ckanext-datajson)). 

GSA's fork is [Ahead in 22 commits](https://github.com/datopian/ckanext-datajson/compare/datagov...GSA:datagov) and [behind 171 commits](https://github.com/GSA/ckanext-datajson/compare/datagov...datopian:datagov). 

Both repos have modifications in pasts weeks. 
Some differences:

 - GSA version includes a Docker container and tests with docker
 - Datopian version includes the ability to work with different schemas. This could allow the same branch to be used for both applications (the Inventory app requires USMetadata which uses a different schema for datasets).

None of them is in active development

## Recommendation

Define an upstream version who can be used in Catalog and Inventory apps. If we need to use USMetadata extension while harvesting at the Inventory app then Datopian version could be a good upstream.

**Comment by kimwdavidson** [comment]
Closing. Taking new approach
