### ISSUE TITLE
Prepare cloud.gov-based data.gov SSP for ISE review

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1433]
## User Story

In order for cloud.gov-based data.gov apps to enter the GSA ISE architecture review process, the GSA OCISO representatives require completion of **the first 12 sections** of the System Security Plan (SSP) that covers data.gov apps under the [Moderate NIST requirements](https://nvd.nist.gov/800-53/Rev4/impact/moderate).

### Acceptance Criteria
- [x] GSA OCISO has an SSP for the data.gov applications with reasonable content in **the first 12 sections**.
- [x] The data.gov team completes the [ISE submission form](https://docs.google.com/forms/d/e/1FAIpQLSc-sIA2-7nQ8ZBR-HXLFNfYNQteSIqtGNY2rVO6m_34rjXSDQ/viewform?pli=1).

## Tasks
- [x] Fill in SSP through section 12
- [x] Create a system/boundary diagram

**Comment by mogul** [comment]
From Lynnette:
> sharing some preliminary feedback from ISE review....
" The SSP looks great. My only comment is can the diagrams be updated to detail or note that all the connections are encrypted. A single sentence or tag in Figure 9-1 and 10-1 will do the trick. I'll start writing the report for Chris and yourself but I see no showstoppers or further comments."

🥳

**Comment by mogul** [comment]
The Markdown+PlantUML source used for this activity now lives in [our compliance repository](https://github.com/GSA/datagov-compliance/blob/master/codimd-scratchpad.md). Load it into CodiMD to preview and edit it!

**Comment by mogul** [comment]
In the time since we completed this work (April!) and have been waiting for our assessment slot, GSA IT has mandated new sub-sections in 10.g (10.7, 10.8, 10.9) that must be included in all SSPs. We were told this week that until we filled in those sections and got another ISE approval, we would not be considered for any open assessment slot. 

So we're reopening this long-closed issue to continue tracking the work. Here's a [direct link to the relevant sections in our SSP](https://docs.google.com/document/d/1WuoO419OV-SHiQU5k_IWZYsWbjPE_VXmj-jNMH0KDDI/edit#heading=h.yik0ptk9zj2l).

**Comment by mogul** [comment]
The new template added 32 sub-sections for us to fill out. 

I've completed the first three (listed below) and will note further progress in additional comments as I go.
- 10.7.1 Code Version Control and Code Management
- 10.7.2 Infrastructure-As-Code (IAC) Implementation
- 10.7.3 Pipeline Design

**Comment by mogul** [comment]
Completed three more sections today:
- 10.7.5     Dependency Scanning (asked Aaron for feedback)
- 10.7.6     Image Management (easy since N/A)
- 10.7.10     Serverless Design (easy since N/A)

**Comment by mogul** [comment]
Completed three more sections today:
- 10.7.4 Code Scanning (Not much to say since we don't currently do it... We should be turning on GitHub.com code-scanning, and then figuring something out for PHP as well since it's not covered. 😬 )
- 10.7.7 Secret and Key Management
- 10.7.8 Artifact Management

**Comment by mogul** [comment]
Completed these sections today:
- 10.7.9 Code Change and Release Management (which finishes section 10.7)
- 10.8.1 Container Image Build and Management
- 10.8.2 Container Image Scanning
- 10.8.3 Container Image Registry
- 10.8.4 Dockerfile Usage
- 10.8.5 Logs and Log Integration from Containers
- 10.8.6 Hardening of Container Infrastructure
- 10.8.9 Container Orchestration
- 10.9.1 List of AWS Services Used
- 10.9.2  Identity and Access Control Management

13 more to go...

**Comment by mogul** [comment]
Tonight I did 

* 10.8.7 Privilege Management in Cluster and Containers
* 10.8.8 Container Network Security
* 10.8.10 Monitoring and Alerting (which finishes section 10.8)
* 10.9.3 Separation of Workloads
* 10.9.4 Cloud Network Design
* 10.9.5 Network Security and Microsegmentation
* 10.9.6 Data Encryption in Transit
* 10.9.7 Data Encryption at Rest
* 10.9.8 S3 Bucket Security
* 10.9.9 Key Management Service (KMS) Key Monitoring and Governance
* 10.9.10 Governance and Management of AWS Accounts
* 10.9.11 Use of Cloud Native Security Services
* 10.9.12 Continuous Monitoring and Assessment of AWS Security Posture

That's all the sections! Woohoo!

**Comment by mogul** [comment]
I'm consolidating the remaining tasks from https://github.com/gsa/datagov-deploy/issues/2436 here since we can't submit for ISE review until both issues are done. I'll also close that issue now as it's duplicative.

---
- [-] In Section 10: Add management space/backup app to diagram and description. (@mogul)
- [x] Data flow section: Expand for each of www, catalog and inventory components. 
- [x] Data nature: Expand for each of www, catalog and inventory components. 
- [x]  Table 10-4: Expand for each of www, catalog and inventory components.

**Comment by mogul** [comment]
>  In Section 10: Add management space/backup app to diagram and description.

I amended the description, but I'm choosing not to add the management space diagram until someone asks for it.

**Comment by mogul** [comment]
Jason and I did go ahead and create/insert the management space diagram.
