### ISSUE TITLE
[Onboard] Paul Walker

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1490]
Welcome! [The Onboarding wiki](https://github.com/GSA/datagov-deploy/wiki/Onboarding-Offboarding) describes the onboarding process for new team members on Data.gov. You’ll learn mostly from pairing and interaction with your teammates but these are some handy resources to get you started.

Below are the tasks that will drive the onboarding process.

### Tasks for admin or onboarding buddy

- [x] Add team member to [TTS Slack](https://handbook.18f.gov/slack/#tts-staff) and #datagov-devsecops
- [x] Invite team member to [Data.gov calendar](https://calendar.google.com/calendar/r/settings/calendar/Z3NhLmdvdl9zcjZ0NG52YjRhOTNjNnNzdHRxYXAzbjZtMEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t) and events
  - Daily sync
  - Sprint planning
  - Retro
- [x] Add team member to Google Drive
  - [Data.gov](https://drive.google.com/drive/folders/0AMRwhrSyJ5R4Uk9PVA)
  - [DevSecOps](https://drive.google.com/drive/folders/1Ac1dUmzTLTsDv8A8TSyLzrXo1a7hm4NF)
- [-] Add team member to email lists
  - [Data.gov team list](https://groups.google.com/a/gsa.gov/forum/#!forum/datagovhelp)
  - [Inventory help list](https://groups.google.com/a/gsa.gov/forum/#!forum/inventory-help)
- [x] Make sure team member has 2FA enabled for their GitHub account and [request](https://github.com/GSA/GitHub-Administration/blob/master/README.md#requesting-access-to-the-gsa-organization) membership to GSA GitHub org
- [x] Add team member to [data-gov-support](https://github.com/orgs/GSA/teams/data-gov-support/members) GitHub team
- [-] Request TTS Bug Bounty access [#bug-bounty-partners](https://gsa-tts.slack.com/messages/C5JQCD9PH)
- [-] Add team member to Uptrends via [email](https://docs.google.com/spreadsheets/d/1Z9Zpr1mpx-65i_fH2VTbVofPtidpLZs5cnkO0Jz53Vc/edit#gid=0)
- [x] Add team member to [New Relic](https://newrelic.com)
- [x] Add team member to [Docker Hub](https://cloud.docker.com/orgs/datagov/teams)
- [x] Add team member to [Snyk](https://app.snyk.io/org/data.gov/manage/members)

### Tasks for new team member

- [x] Read through the [required reading list](https://github.com/GSA/datagov-deploy/wiki/Onboarding-Offboarding#required-reading-list)
- [x] Join the international [CKAN Government Working Group](https://docs.google.com/document/d/1d04ZmvSCjb3zhsIZW01wSkoRSzIiLyWen5Z8iwfzhIU/edit)
- [x] Join [Open Data](https://digital.gov/communities/open-data/) community list
- [x] Ensure your GitHub account meets the criteria for [GSA GitHub org](https://github.com/GSA/GitHub-Administration/blob/master/README.md) (setup 2FA)
- [x] [Request access](https://docs.google.com/forms/d/e/1FAIpQLSetStmwqrbMWDz_WIlh1trjhP0PFCjKXHzshsJveYmtIvlG2Q/viewform) to Data.gov systems; select “Catalog Admin” for the system, and “Data.gov team member” for justification
- [x] Add yourself for [AWS sandbox access](https://github.com/GSA/datagov-infrastructure-live/tree/master/iam#new-users)
- [x] Add your public SSH key to the Ansible vault
  - Request the Ansible Vault keys from team member
  - Clone the [datagov-deploy](https://github.com/GSA/datagov-deploy) repo
    locally
  - Follow the setup instructions for [development](https://github.com/GSA/datagov-deploy/blob/develop/README.md#development)
  - Follow the [ansible-vault instructions](https://github.com/GSA/datagov-deploy#editing-vault-secrets)
  - Checkout the `master` branch to make this change as a [hotfix](https://github.com/GSA/datagov-deploy/blob/develop/CONTRIBUTING.md#hotfixes)
  - Edit the vault file `pipenv run ansible-vault edit ansible/group_vars/all/vault.yml` and add your public SSH key
- [x] Request access to AWS OPP account from team member

**Comment by adborden** [comment]
Added @starsinmypockets to sandbox https://github.com/GSA/datagov-deploy/pull/1496

**Comment by mogul** [comment]
Many items here are blocked by lack of a @gsa.gov email address; moving to blocked.

**Comment by adborden** [comment]
FYI, I requested GH access for @starsinmypockets

**Comment by mogul** [comment]
We're explicitly skipping over a few steps (team mailing lists, bug bounty, and Uptrends alerts) since Paul won't be responsible for anything happening there, but we can add access in future if it makes sense.
