### ISSUE TITLE
Release 20200416

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1543]
### ...in the sandbox environment
We should skip running the inventory playbook (add instructions for that to the deployment process) here since there are environment deltas that we haven't resolved yet and we know it doesn't deploy cleanly. We can bring it back into the process as we address those deltas.
### ...in the staging environment
The Trend Micro agent installed is newer than the available .deb. Had to figure out how we got into this state. We should probably change the playbook to just make sure the Trend Micro agent is installed, not try to update it. Needs confirmation by looking at other hosts to see if the agent is updating itself.
### ...in the production environment
You might get an error such as `Permission denied Unable to connect to WSGI daemon process 'ckan' on '/var/run/apache2/wsgi.5116.0.0.sock`. First step is to reboot the host and see if this fixes the error. If this doesn't correct it then inspect the permissions for `/var/run/apache2` and change the folder permissions as needed.

## Tasks
- [x] update [release documentation](https://github.com/GSA/datagov-deploy/wiki/Releases#deploy-to-sandbox) and/or [README](https://github.com/GSA/datagov-deploy#usage) to include sandbox deployment work-arounds
- [x] Ensure we have Trendmicro resolved
- [x] inventory-2-8 "fix" https://github.com/GSA/datagov-deploy/issues/1552
- [x] pull in snyk hotfix (https://github.com/GSA/datagov-deploy/pull/1565)

**Comment by adborden** [comment]
@pjsharpe07 we should hold off on the production release until after the [database upgrade](https://github.com/GSA/datagov-deploy/issues/1548).
