### ISSUE TITLE
Write SSP narratives for the AC control family

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#1576]
## User Story

In order for data.gov components on cloud.gov to enter the GSA Assessment and Authorization (A&A) process, GSA OCISO representatives require System Security Plan (SSP) that includes narratives for the [control family](https://nvd.nist.gov/800-53/Rev4) referenced in the issue title.

### Acceptance Criteria
- [x] The [Data.gov FY20 SSP DRAFT (Cloud.gov)](https://docs.google.com/document/d/1WuoO419OV-SHiQU5k_IWZYsWbjPE_VXmj-jNMH0KDDI/edit) document has relevant and accurate content for all controls in the referenced family.

## Details

This will involve writing in the SSP narrative and spawning issues for implementing any missing but necessary monitoring, testing, policies, etc. The LATO materials generated for other TTS apps running on cloud.gov, eg TouchPoints, can be used as a reference.

Reference materials:
- TTS' [Before You Ship](https://before-you-ship.18f.gov/) guide
- [GSA LATO template for cloud.gov-hosted apps](https://docs.google.com/document/d/1tVbH39TFfvSaBbjWfLaR3GLOuvsLuhLFJ75xKowEV5c/edit)
- [SSP for Touchpoints, with which our ISSO will be familiar](https://docs.google.com/document/d/1RtMfKUOSPvYtG0XLIusYU-CJv4UM7Lv5UaBzhV6fzzo/edit?ts=5e459a17)
- [Source-of-truth for compliance docs](https://drive.google.com/drive/folders/0B5Pp9m0GlZnvNnRiWEpCZGZFQnM)

## Tasks/stories:
- [x] Fill out all control narratives
  - [x] Carry over relevant [P1+LATO control narratives](https://docs.google.com/spreadsheets/d/1hnDH3DSbRMBsi6SFpQb0ZvJTlDRC57hGT1RtXQb_aZA/edit#gid=1843719707&fvid=1294579545) under this control family from [the Touchpoints example](https://docs.google.com/document/d/1RtMfKUOSPvYtG0XLIusYU-CJv4UM7Lv5UaBzhV6fzzo/edit#heading=h.1v1yuxt)
  - [x] Ensure all [P1 (non-LATO) controls](https://docs.google.com/spreadsheets/d/1hnDH3DSbRMBsi6SFpQb0ZvJTlDRC57hGT1RtXQb_aZA/edit#gid=1843719707&fvid=2107946104) under this control family have a narrative
  - [x] Ensure all [P2 controls](https://docs.google.com/spreadsheets/d/1hnDH3DSbRMBsi6SFpQb0ZvJTlDRC57hGT1RtXQb_aZA/edit#gid=1843719707&fvid=1861982652) under this control family have a narrative
