### ISSUE TITLE
Spike 2d: Plan for an embedded, decoupled front end form 

### ISSUE THREAD

**Issue by estebanruseler** [GSA/data.gov#1735]
## User Story

As an agency user, I can easily add metadata and data that complies with the DCAT standard without having to be an expert in the schema or consult a lot of outside materials

## Acceptance Criteria
- [ ] Does existing API interface work the 2.5 API
  - Autocomplete data available from 2.5 API?
- [ ] USWDS basic form with a subset of the fields with inline errors
- [ ] Proof-of-concept implementation required-if-applicable fields
- [ ] Hiding/showing of fields based on previous answers

## Task-list
 - [ ] Get the existing app that we know works with CKAN 2.8 working with inventory app (for of CKAN 2.5) [Julie and Paul to pair]
 - [ ] Update the form so that it works as per the UX spec as much as possible, in particular, to validate that we do the requirements listed in the AC
 - [ ] Julie to look into the DKAN decoupled app to understand if it's a stand-alone app or can be embedded into CKAN, and more generally the work involved so that it works with CKAN's admin API.  

## Background
Julie produced an estimate to create a metadata / data entry form in CKAN which is 5 to 7 days. As we know we want to extend this form in the future (and CKAN's front-end is inflexible), we're looking into the feasibility of doing it via a decoupled embedded app (embedded to avoid needing an ATO). Datopian has an unpolished react app that works with the CKAN admin API and CA have a decoupled app for metadata entry (decoupled from DKAN). 

## Security Considerations

None for now as just a spike but we'll need to address this.

**Comment by estebanruseler** [comment]
Closed and added this to [datagov-ckan-multi/311](https://app.zenhub.com/workspaces/datagov-multi-tenant-ckan-5cf12b601437ff1e943f0aa2/issues/gsa/datagov-ckan-multi/311)

**Comment by estebanruseler** [comment]
Now closing...
