### ISSUE TITLE
Research 3d: Identify low-lift effort for a new evidence act compliance information

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#1757]
## User Story

In order to remove the dashboard and focus efforts on high-value delivery of the Data.gov mission, Data.gov wants  to create a maintainable, modern source of information (similar to the [dashboard](https://labs.data.gov/dashboard)) for OMB to report to GAO.

In order to provide essential information for Evidence Act compliance, OMB wants a single public location of information for reporting to GAO.

## Tasks
- [ ] investigate if a visual dashboard is essential, or if data files (e.g. JSON or CSV) is sufficient
- [x] investigate what information we can collect from the CKAN API instead of a crawl
- [ ] investigate if a dedicated nightly crawl can be eliminated
- [ ] investigate where this data could be permanently stored
- [ ] review findings with OMB
- [x] create stories for implementation

## Background
The dashboard consumes more effort from the Data.gov team than the value it is delivering to users. The audience for the Dashboard is unclear, we know OMB uses some of the dashboard functionality to prepare for GAO meetings.

[June 16th, 2020 conversation with OMB](https://docs.google.com/document/d/1nVmQgltnoKNHS2zefXkeyNovUQc3VBzL5bOzU963U8I/edit).

By focusing the information that Dashboard collects to the essentials for OMB, we can create a new solution with minimal effort. Hopefully this means:
- Eliminating the PHP application [GSA/project-open-data-dashboard](https://github.com/GSA/project-open-data-dashboard).
- Avoiding the need for a dedicated crawl, using the catalog API instead

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))
[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None for this research story. Any stories created from this work should identify any security considerations.

## Sketch
Catalog already provides some "meta" datasets about the catalog (e.g. [bulk metadata download](https://catalog.data.gov/dataset/data-gov-ckan-api/resource/96bf923e-e7ce-45f7-ad1f-47eb34178e95), [site statistics](https://catalog.data.gov/dataset/data-gov-statistics-parent)) which are implemented as a [CKAN extension](https://github.com/GSA/ckanext-geodatagov) and run regularly with cron. We could treat the Evidence Act compliance information in a similar way, a dataset available through catalog.data.gov (or inventory.data.gov). IMHO, it's an accident of history that dashboard crawl data is hidden under this "labs" feature with little documentation and visibility instead of being available in the catalog.

Perhaps a data file containing this compliance information is enough for OMBs needs. A static HTML/JS dashboard could pull this data file for visual rending. If the data file is sufficient, the dashboard could be implemented at a later date and would still be able to provide historic data would be available once we start collecting data for the dataset.

**Comment by jbrown-xentity** [comment]
Per Aaron and OMB conversation, the key items we need are:

- Does the Agency have a data.json (at the standard endpoint)?
- How many datasets are in the data.json?

Items that are currently on the Dashboard:

- Last modified date
- Number of datasets
- Is it a valid file?
- How many programs?
- How many bureaus?
- How many restricted/non-public/public datasets?
- How many downloads?
- Total URL's and valid URL's?
- Machine Readable downloads vs view downloads

**Comment by jbrown-xentity** [comment]
First pass at documenting current state, reason for desired changes, and other possible implementations that would require less management can be found [here](https://docs.google.com/document/d/1_q9qHwzSrd2_TzbTJkWqlvcibD6tWyoK3wYNHfy2Fx0/edit#).

**Comment by jbrown-xentity** [comment]
Next steps include building out a quick test script validating CKAN API usage for building a CSV, and possibly building out a dynamic representation of data from an inventory API as a static page (possibly resources.data.gov, in staging only?)

**Comment by pjsharpe07** [comment]
Current version of a simple crawl that produces a csv can be found [here](https://docs.google.com/document/d/1_q9qHwzSrd2_TzbTJkWqlvcibD6tWyoK3wYNHfy2Fx0/edit#heading=h.8oilp0lq56qd) along with some notes.

**Comment by adborden** [comment]
@pjsharpe07 can you include an example CSV output we can share with OMB?

**Comment by mogul** [comment]
(CSV is in the Google Drive link above.)

**Comment by mogul** [comment]
Unblocking until our sketch of how to proceed from here is complete.

**Comment by mogul** [comment]
Planning to discuss with Rebecca ahead of next Friday.

**Comment by mogul** [comment]
There appear to be no strong obstacles or objections to our proposed approach. We'll check with Phil as we go, but generally the research story can be concluded.

**Comment by nickumia-reisys** [comment]
Related to
- https://github.com/GSA/data.gov/issues/4354
