### ISSUE TITLE
[Onboard] christopher.macdermaid@gsa.gov

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#1851]
Welcome! [The Onboarding wiki](https://github.com/GSA/datagov-deploy/wiki/Onboarding-Offboarding) describes the onboarding process for new team members on Data.gov. You’ll learn mostly from pairing and interaction with your teammates but these are some handy resources to get you started.

Below are the tasks that will drive the onboarding process.

### Tasks for admin or onboarding buddy

- [x] Add team member to [TTS Slack](https://handbook.18f.gov/slack/#tts-staff) and #datagov-devsecops
- [x] Invite team member to [Data.gov calendar](https://calendar.google.com/calendar/r/settings/calendar/Z3NhLmdvdl9zcjZ0NG52YjRhOTNjNnNzdHRxYXAzbjZtMEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t) and events
  - Daily sync
  - Sprint planning
  - Retro
- [x] Add team member to Google Drive
  - [Data.gov](https://drive.google.com/drive/folders/0AMRwhrSyJ5R4Uk9PVA)
  - [DevSecOps](https://drive.google.com/drive/folders/1Ac1dUmzTLTsDv8A8TSyLzrXo1a7hm4NF)
- [x] Add team member to email lists
  - [Data.gov team list](https://groups.google.com/a/gsa.gov/forum/#!forum/datagovhelp)
  - [Inventory help list](https://groups.google.com/a/gsa.gov/forum/#!forum/inventory-help)
- [x] Make sure team member has 2FA enabled for their GitHub account and [request](https://github.com/GSA/GitHub-Administration/blob/master/README.md#requesting-access-to-the-gsa-organization) membership to GSA GitHub org
- [x] Add team member to [data-gov-support](https://github.com/orgs/GSA/teams/data-gov-support/members) GitHub team
- [x] Request TTS Bug Bounty access [#bug-bounty-partners](https://gsa-tts.slack.com/messages/C5JQCD9PH)
- [x] Add team member to Uptrends via [email](https://docs.google.com/spreadsheets/d/1Z9Zpr1mpx-65i_fH2VTbVofPtidpLZs5cnkO0Jz53Vc/edit#gid=0)
- [x] Add team member to [New Relic](https://newrelic.com) with permissions:
  - Alerts manager
  - APM manager
  - Infrastructure manager
  - Synthetics manager
- [x] Add team member to [Docker Hub](https://cloud.docker.com/orgs/datagov/teams)
- [x] Add team member to [Snyk](https://app.snyk.io/org/data.gov/manage/members)
- [x] Add team member as a SpaceDeveloper in the [`development`](https://dashboard.fr.cloud.gov/cloud-foundry/2oBn9LBurIXUNpfmtZCQTCHnxUM/organizations/90047c5d-337f-4802-bd48-2149a4265040/spaces/eab3d327-7d9f-423b-9838-753c26fdb5a0/users), [`staging`](https://dashboard.fr.cloud.gov/cloud-foundry/2oBn9LBurIXUNpfmtZCQTCHnxUM/organizations/90047c5d-337f-4802-bd48-2149a4265040/spaces/3e692cdd-6d26-41ea-9698-04903dc3f742/users), and [`management`](https://dashboard.fr.cloud.gov/cloud-foundry/2oBn9LBurIXUNpfmtZCQTCHnxUM/organizations/90047c5d-337f-4802-bd48-2149a4265040/spaces/9a1db116-0180-42be-8ffa-7944dcf6bf50/summary) spaces in cloud.gov.

       $ cf set-space-role <email> gsa-datagov <space> SpaceDeveloper

For new Project Management Office team members, follow these additional steps:

- [x] Add team member to Google Drive
  - ~~[CKAN Mutli](https://drive.google.com/drive/folders/0ALb0g1S27SJPUk9PVA)~~
- [x] ~~Add team member to email lists~~
  - ~~[Data.gov support list](https://groups.google.com/a/gsa.gov/forum/#!forum/datagov)~~
- [x] ~~Add team member to #datagov-pmo (PMO only)~~
- [x] Add team member to Data.gov slack channels
  - ~~#bug-bounty~~
  - ~~#bug-bounty-partners~~
  - #datagov-alerts
  - #datagov-ckan-multi
  - ~~#datagov-comms~~
  - #datagov-devsecops
  - #datagov-notifications
  - ~~#opp-data-analytics~~
- [x] ~~Add team member to [the GCP project](https://console.cloud.google.com/iam-admin/iam?project=tts-datagov)~~
- [x] ~~Add team member with OrgManager permissions in [the `gsa-datagov` organization](https://dashboard.fr.cloud.gov/cloud-foundry/2oBn9LBurIXUNpfmtZCQTCHnxUM/organizations/90047c5d-337f-4802-bd48-2149a4265040/users) on cloud.gov~~
- [x] ~~Add team member to [data-gov-admins](https://github.com/orgs/GSA/teams/data-gov-admin/members) GitHub team~~
- [x] Invite team member to calendar events
  - CKAN-multi project syncs
  - FGDC meeting
  - CKAN Gov Working group
- [x] ~~Promote team member to Admin in [New Relic](https://newrelic.com)~~

### Tasks for new team member

- [x] Ensure your GitHub account meets the criteria for [GSA GitHub org](https://github.com/GSA/GitHub-Administration/blob/master/README.md) (setup 2FA)
- [x] Read through the [required reading list](https://github.com/GSA/datagov-deploy/wiki/Onboarding-Offboarding#required-reading-list)
- [x] [Request access](https://docs.google.com/forms/d/e/1FAIpQLSetStmwqrbMWDz_WIlh1trjhP0PFCjKXHzshsJveYmtIvlG2Q/viewform) to Data.gov systems; select “Catalog Admin” for the system, and “Data.gov team member” for justification
- [x] Add yourself for [AWS sandbox access](https://github.com/GSA/datagov-infrastructure-live/tree/master/iam#new-users)
- [x] Request access to AWS OPP account from team member
- [x] Add your public SSH key to the Ansible vault
  - Clone the [datagov-deploy](https://github.com/GSA/datagov-deploy) repo
    locally
  - Follow the setup instructions for [development](https://github.com/GSA/datagov-deploy/blob/develop/README.md#development)
  - Checkout the `master` branch to make this change as a [hotfix](https://github.com/GSA/datagov-deploy/blob/develop/CONTRIBUTING.md#hotfixes)
  - Edit the [variables file](https://github.com/GSA/datagov-deploy/blob/develop/ansible/group_vars/all/vars.yml#L41-L138) and add your public SSH key
  - Review [documentation](https://github.com/GSA/datagov-deploy/wiki/gsa-vpn) on how to access/setup environment for staging and production access.
- [x] Enable MFA for [HackerOne](https://hackerone.com/settings/auth)
- [x] Join [Open Data](https://digital.gov/communities/open-data/) community list

**Comment by jbrown-xentity** [comment]
@mogul @adborden we are part way through access, but I don't have the necessary permissions for the following invites:

- [x] New Relic invite and role setup
- [x] Docker Hub
- [x] HackerOne (application and Slack channel), is this even necessary for Chris?

Could someone send out these invites and :heavy_check_mark: when done?

Adding SSH key blocked pending resolution of [current development](https://github.com/GSA/datagov-deploy/pull/1869)

**Comment by jbrown-xentity** [comment]
@mogul @adborden I do not have the requisite permissions for setting up Chris to have [AWS sandbox console access](https://github.com/GSA/datagov-infrastructure-live/tree/master/iam#new-users). He has already added himself and I have confirmed his account, can one of you **run through those admin console/password setup steps** please?

**Comment by adborden** [comment]
I'll can run through these.

**Comment by adborden** [comment]
@chris-macdermaid ping me in slack when you are available for the credentials hand-off.

**Comment by chris-macdermaid** [comment]
I've completed the onboarding tasks.
