### ISSUE TITLE
Write SSB narratives for the RA control family

### ISSUE THREAD

**Issue by mogul** [GSA/data.gov#2050]
## User Story

In order for data.gov components on cloud.gov to enter the GSA Assessment and Authorization (A&A) process, GSA OCISO representatives require System Security Plan (SSP) that includes narratives for the [control family](https://nvd.nist.gov/800-53/Rev4) referenced in the issue title.

### Acceptance Criteria
- [ ] The [SSB FY20 SSP DRAFT (Cloud.gov)](https://docs.google.com/document/d/15bP07LtTXY2gvNHlM_reehTp4_k3tMZh/edit#) document has relevant and accurate content for all controls in the referenced family.

## Details

This will involve writing in the SSP narrative and spawning issues for implementing any missing but necessary monitoring, testing, policies, etc.

Reference materials:
- TTS' [Before You Ship](https://before-you-ship.18f.gov/) guide
- [GSA LATO template for cloud.gov-hosted apps](https://docs.google.com/document/d/1tVbH39TFfvSaBbjWfLaR3GLOuvsLuhLFJ75xKowEV5c/edit)
- [draft SSP for the rest of data.gov on cloud.gov](https://docs.google.com/document/d/1WuoO419OV-SHiQU5k_IWZYsWbjPE_VXmj-jNMH0KDDI/edit#heading=h.gjdgxs)
- [Source-of-truth for compliance docs](https://drive.google.com/drive/folders/0B5Pp9m0GlZnvNnRiWEpCZGZFQnM)

## Tasks/stories:
- [ ] Fill out all control narratives
- [ ] Verify with a subject-matter expert
