### ISSUE TITLE
Current six-month roadmap for Data.gov

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#2061]
## User Story

As Data.gov PMO, we want a document that shows six month plan for major goals for program.

## Acceptance Criteria

- [x] Draft roadmap/plan
- [x] Data.gov PMO meet and collaborate
- [x] Continue to update on monthly basis

## Background
We have other versions of this but simplifying in a table

https://docs.google.com/document/d/19XRBlQbjKMcJJtKA0xkl6F6GJ7AqaToMFCBc-DchSUE/edit?usp=sharing
for Data.gov PMO only

**Comment by hkdctol** [comment]
There's a version we have been using since August, will mark this done for now.
