### ISSUE TITLE
Use geo search from upstream spatial extension

### ISSUE THREAD

**Issue by avdata99** [GSA/data.gov#2440]
Attempt to replace issue #2418.

## Feature/what we're after
Start using [geo-search from `ckanext-spatial` extension](https://docs.ckan.org/projects/ckanext-spatial/en/latest/spatial-search.html#spatial-search-widget) and stop using [our (not documented) custom table](https://github.com/GSA/catalog.data.gov/tree/master/tools/locations-table)

## Anticipated/hypothesized benefits
- We can stop maintaining our [custom search function](https://github.com/GSA/ckanext-geodatagov/blob/master/ckanext/geodatagov/logic.py#L18:L18).
- We have a documented process to update the locations data periodically

## Measurements/metrics
- We are able to search by location names or using the map in the UI

## References/background
In ckanext-spatial you can [index your geo data](https://docs.ckan.org/projects/ckanext-spatial/en/latest/spatial-search.html#geo-indexing-your-datasets) and then [search by location](https://docs.ckan.org/projects/ckanext-spatial/en/latest/spatial-search.html#spatial-search-widget)

We will need to fix our [spatial extra field validation issue](https://github.com/GSA/datagov-ckan-multi/issues/332) before doing this.

## Tasks
 - [x] Validate the feature at spatial extension cover our custom feature
    - [ ] Our geo search allows searching by name (e.g. _california_). Analyze to improve spatial extension whit this feature.
 - [ ] Discover how to get the data and define a process to update this periodically
 - [ ] Apply the new search and remove code from GeoDataGov extension

**Comment by avdata99** [comment]
Notes:
 - CKAN version does not allow to search by location _name_ (e.g. _California_). Is just the ability to search inside a map. This feature uses the `spatial` extra field in datasets. 
 - Our version allows text search
