### ISSUE TITLE
Responsive layout tweaks for dataset page on catalog-next

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#2466]
Organization information should move to the footer?
Maybe the logos are too large?
Too much vertical whitespace between informational elements?

<img width="703" alt="Screen Shot 2020-11-20 at 2 45 41 PM" src="https://user-images.githubusercontent.com/509703/99857005-1af30400-2b3f-11eb-8a68-506c17e587a7.png">

<img width="704" alt="Screen Shot 2020-11-20 at 2 49 02 PM" src="https://user-images.githubusercontent.com/509703/99857211-948af200-2b3f-11eb-8509-16914fa22cc6.png">

## How to reproduce

1. https://catalog-next.data.gov/dataset/fy-2019-federal-real-property-profile-data-for-civilian-agencies
1. Adjust window size to ~770px

## Expected behavior

Dataset description and information is visible above the fold.

## Actual behavior

Organization information takes up too much of the screen.

## Tasks
- [x] Set max width to logos so that it won't take too much space from screen
- [x] Remove the extra white spaces between the sections
- [x] Set the with to fit the screen size on smaller screens so that the horizontal scroll won't appear

**Comment by kmanaseryan** [comment]
Current look:
https://www.loom.com/share/11b45b8cf4d04bc9a9243a5917e65edc

New changes:
https://www.loom.com/share/fca456910dd145e2b33d10419b669f40 


There is one big white space left between "Date" and "Downloads & Resources" sections, but it looks we have some extra empty `<section></section>` element, which need to discuss with the team.

**Comment by hkdctol** [comment]
Reviewed and confirmed
