### ISSUE TITLE
Implement catalog header without relying on Wordpress

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/data.gov#3537]
## User Story

In order to get off wordpress, data.gov admins want catalog header to be handled outside of wordpress.

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [x] GIVEN wordpress (data.gov) is not available \
  WHEN a user visits catalog \
  THEN the standard header is shown \

## Background

ckanext-datagovtheme currently hits a wordpress api to get the header (see [here](https://github.com/GSA/ckanext-datagovtheme/blob/main/ckanext/datagovtheme/helpers.py#L330-L450)). Since this won't exist, we'll either need to create another endpoint or move to another way to get the header HTML.
We have a default/backup JSON structure [here](https://github.com/GSA/ckanext-datagovtheme/blob/main/ckanext/datagovtheme/data/dynamic_menu/menu.json). This file is probably out of date.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
None, public HTML

## Sketch

- Decide on a way to handle HTML creation/editing (static data.gov repo? Handle in catalog? somewhere else?)
- Copy header HTML and styling for future use
- Place in retrievable location
- Use CKAN config options to retrieve necessary info and build appropriate header.

## Tasks
- [x] First make sure there is a static file that keep the memu working without relying on Wordpress
- [ ] Make the static menu easy to edit or configurable.

**Comment by jbrown-xentity** [comment]
Turns out we already have an "offline" way to handle this. If needed, we could take on this work later and just replace the current `menu.json` file with the latest version...

**Comment by adborden** [comment]
I'm looking at the [linked code for get_dynamic_menu](https://github.com/GSA/ckanext-datagovtheme/blob/main/ckanext/datagovtheme/helpers.py#L330-L450) but I'm not seeing a fetch to www.data.gov. It looks like the code always starts with the included static menu.json.

**Comment by adborden** [comment]
@FuhuXia confirmed that is looks like we've already removed the dependency on www.data.gov. I'm going to remove this as a blocker for the Federalist migration.

Additional [history on the need for a dynamic menu](https://gsa-tts.slack.com/archives/C2N85536E/p1637728137021600?thread_ts=1637714206.020500&cid=C2N85536E) from @FuhuXia :
> Some context to help anyone to understand the purpose of this menu thing. **Wordpress** has some navigations that including data as one of the tab. such as [this one](https://www.data.gov/ocean/). The data tab to leads to **Catalog** app on [this page](https://catalog.data.gov/dataset?groups=ocean9585#topic=ocean_navigation). We tries to make the menu on **Catalog** looks same as **Wordpress** ones, so that user does not lose track which tabs they are on. In order to do so, we have to keep the Catalog menu in-sync with Wordpress. Back to old days, the menu change quite often, sometime weekly.

**Comment by adborden** [comment]
Putting this in New to re-triage.

**Comment by mogul** [comment]
Remaining work: Make it easy to edit and maintain the header in a post-Wordpress world (eg by factoring the header out of both the static side and the extension into a shared theme repo).

**Comment by nickumia-reisys** [comment]
This is sort of already implemented, but is superseded by work related to
- https://github.com/GSA/data.gov/issues/4181
