### ISSUE TITLE
[Onboard] Reid.Hewitt@gsa.gov

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#4249]
Welcome! [The Onboarding wiki](https://github.com/gsa/data.gov/wiki/Onboarding-Offboarding) describes the onboarding process for new team members on Data.gov. You’ll learn mostly from pairing and interaction with your teammates but these are some handy resources to get you started.

Below are the tasks that will drive the onboarding process.

### Tasks for admin or onboarding buddy

- [x] Review the rest of the checklist below before starting to work through it. Any step that does not seem relevant or necessary for the kind of work that the person onboarding will be doing should have a `-` in the checkbox and `~` around the line so it's clear that we will not be granting that particular kind of access for this person.
- [x] Add team member to [TTS Slack](https://handbook.18f.gov/slack/#tts-staff)
  - #datagov-alerts
  - #datagov-devsecops
  - #datagov-notifications
- [x] Invite team member to [Data.gov calendar](https://calendar.google.com/calendar/r/settings/calendar/Z3NhLmdvdl9zcjZ0NG52YjRhOTNjNnNzdHRxYXAzbjZtMEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t) and events
  - Daily sync
  - Sprint planning
  - Retro
- [x] Add team member to Google Drive
  - [Data.gov](https://drive.google.com/drive/folders/0AMRwhrSyJ5R4Uk9PVA)
  - [DevSecOps](https://drive.google.com/drive/folders/1Ac1dUmzTLTsDv8A8TSyLzrXo1a7hm4NF)
- [x] Add team member to email lists
  - [Data.gov team list](https://groups.google.com/a/gsa.gov/forum/#!forum/datagovhelp)
  - [Inventory help list](https://groups.google.com/a/gsa.gov/forum/#!forum/inventory-help)
- [x] Make sure team member has 2FA enabled for their GitHub account and [request](https://github.com/GSA/GitHub-Administration/blob/master/README.md#requesting-access-to-the-gsa-organization) membership to GSA GitHub org
- [x] Add team member to a Data.gov GitHub team [data-gov-support](https://github.com/orgs/GSA/teams/data-gov-support/members)
~- [ ] Request TTS Bug Bounty access from @bugbounty-admins in [#bug-bounty](https://gsa-tts.slack.com/archives/C0X2FMJ86)~
- [x] Add team member to [New Relic](https://account.newrelic.com/accounts/1601367/users) with permissions:
  - Alerts manager
  - APM manager
  - Infrastructure manager
  - Synthetics manager
- [x] Add team member to [Snyk](https://app.snyk.io/org/data.gov/manage/members)
- [x] Add team member to [Data.gov Google Analytics](https://analytics.google.com/analytics/web/#/a42145528w85560911p88728213/admin/suiteusermanagement/account) account
- [x] Add team member as a SpaceDeveloper in the [`development`](https://dashboard.fr.cloud.gov/cloud-foundry/2oBn9LBurIXUNpfmtZCQTCHnxUM/organizations/90047c5d-337f-4802-bd48-2149a4265040/spaces/eab3d327-7d9f-423b-9838-753c26fdb5a0/users), [`staging`](https://dashboard.fr.cloud.gov/cloud-foundry/2oBn9LBurIXUNpfmtZCQTCHnxUM/organizations/90047c5d-337f-4802-bd48-2149a4265040/spaces/3e692cdd-6d26-41ea-9698-04903dc3f742/users), and [`management`](https://dashboard.fr.cloud.gov/cloud-foundry/2oBn9LBurIXUNpfmtZCQTCHnxUM/organizations/90047c5d-337f-4802-bd48-2149a4265040/spaces/9a1db116-0180-42be-8ffa-7944dcf6bf50/summary) spaces in cloud.gov.
  - `$ cf set-space-role <email> gsa-datagov <space> SpaceDeveloper`
- [x] Add team member to the SSB AWS accounts \
      Make a PR on [the Terraform file controlling access](https://github.com/18F/aws-admin/blob/main/terraform/datagov-iam.tf) to add the new person and include them in the appropriate user_groups.
- [x] Request Federalist access by posting in [#federalist-support](https://gsa-tts.slack.com/archives/C1NUUGTT5) with the new member's GitHub username.
- [x] Once member had logged into Login.gov, add them to the [data.gov team](https://dashboard.int.identitysandbox.gov/teams/174).
- [x] Add team member as form manager to any Data.gov [Touchpoints](https://touchpoints.app.cloud.gov/)

~For new Project Management Office team members, follow these additional steps:~

~- [ ] Add team member to Google Drive~
  ~- [CKAN Mutli](https://drive.google.com/drive/folders/0ALb0g1S27SJPUk9PVA)~
~- [ ] Add team member to email lists~
  ~- [Data.gov support list](https://groups.google.com/a/gsa.gov/forum/#!forum/datagov)~
~- [ ] Add team member to #datagov-pmo-private~
~- [ ] Add team member to additional slack channels~
  - ~#bug-bounty~
  - ~#bug-bounty-partners~
  - ~#datagov-comms~
  - ~#sol-data-analytics~
~- [ ] Add team member to [the GCP project](https://console.cloud.google.com/iam-admin/iam?project=tts-datagov)~
~- [ ] Add team member with OrgManager permissions in [the `gsa-datagov` organization](https://dashboard.fr.cloud.gov/cloud-foundry/2oBn9LBurIXUNpfmtZCQTCHnxUM/organizations/90047c5d-337f-4802-bd48-2149a4265040/users) on cloud.gov~
~- [ ] Add team member to [data-gov-admins](https://github.com/orgs/GSA/teams/data-gov-admin/members) GitHub team~
~- [ ] Invite team member to calendar events~
~- [ ] Promote team member to Admin in [New Relic](https://account.newrelic.com/accounts/1601367/users)~
~- [ ] Add team member as an Owner to PyPI packages:~
  - ~[ckanext-dcat-usmetadata](https://pypi.org/project/ckanext-dcat-usmetadata/)~

### Tasks for new team member

- [x] Log into [Login.gov dashboard](https://dashboard.int.identitysandbox.gov/)
- [x] Ensure your GitHub account meets the criteria for [GSA GitHub org](https://github.com/GSA/GitHub-Administration/blob/master/README.md) (setup 2FA)
- [x] Read through the [required reading list](https://github.com/gsa/data.gov/wiki/Onboarding-Offboarding#required-reading-list)
- [x] [Request access](https://docs.google.com/forms/d/e/1FAIpQLSetStmwqrbMWDz_WIlh1trjhP0PFCjKXHzshsJveYmtIvlG2Q/viewform) to Data.gov systems; select “Catalog Admin” for the system, and “Data.gov team member” for justification. <ins>This step requires a PIV card. </ins>
- [x] Join [Open Data](https://digital.gov/communities/open-data/) community list
- [x] Request access to the [Digital Analytics Program](https://digital.gov/guides/dap/gaining-access-to-dap-data/)
- [x] setup [ckan harvester](https://github.com/ckan/ckanext-harvest)
- [x] setup [catalog](https://github.com/gsa/catalog.data.gov#requirements) and run locally 
- [x] review [metadata schema overviews](https://resources.data.gov/resources/podm-field-mapping/)

**Comment by rshewitt** [comment]
Logged into login.gov. 

![Image](https://user-images.githubusercontent.com/92057378/228068180-ae3531bd-b15a-4b2d-a7d3-38c10a0c2f01.png)

**Comment by rshewitt** [comment]
Having an issue requesting access to the "Catalog Admin" system. I'm following this step in the google form ( see attached picture ). After navigating to the login page of [catalog.data.gov](https://catalog.data.gov/dataset) and signing in i'm prompted to enter my auth app code but I receive the error "That one-time code is invalid. Try again or request a new code". This happens no matter the code. 

![Image](https://user-images.githubusercontent.com/92057378/228071310-f3048bc3-92bc-4a1c-99a2-3bb2e3dafb73.png)

**Comment by hkdctol** [comment]
@rshewitt Catalog and Inventory Admin require login.gov with a PIV card as the 2FA. I think it will be a while before you get your PIV card.

**Comment by rshewitt** [comment]
understood. I should have paid closer attention to the comment indicating I need to  "us[e] a PIV card".

**Comment by rshewitt** [comment]
In regards to the required readings, some of them are quite long such as [Data.gov System Security Plan (SSP) FY21](https://docs.google.com/document/d/1WuoO419OV-SHiQU5k_IWZYsWbjPE_VXmj-jNMH0KDDI/edit) (1058 pages) and [Supplemental Service Broker System Security Plan (SSP) FY21](https://docs.google.com/document/d/1GxhYwcR1F26RvgQdXuglYDIeRqQ69x4xzpLJ-FkU9_w/edit#heading=h.gjdgxs) (353 pages). Are there certain sections I should focus more attention on?

**Comment by rshewitt** [comment]
I don't have access to [Data.gov Contingency Plan procedures](https://github.com/GSA/datagov-incident-response/blob/master/CONTINGENCY.md) using my gsa email.

**Comment by hkdctol** [comment]
Requested access for CP plan. On SSP's, I would read the first sections 1-12 (the front parts before you get to all the controls). The controls are worth skimming.

**Comment by jbrown-xentity** [comment]
@rshewitt , can you login to this: https://dashboard.int.identitysandbox.gov/teams/174? This is how you should have access to change/add login.gov setup for our applications in staging and dev, and a request can promote them to prod.

**Comment by rshewitt** [comment]
@jbrown-xentity yes I can. 

![Image](https://user-images.githubusercontent.com/92057378/229189728-d93a556a-1b8b-4a74-9e8f-9434cfd0d03b.png)

**Comment by rshewitt** [comment]
@btylerburton confirm access to AWS. this serves more as a record/reminder for me.

**Comment by rshewitt** [comment]
Confirmation of catalog running on local. Thanks @jbrown-xentity 

![Image](https://user-images.githubusercontent.com/92057378/229909787-2f0e4c4b-25d2-4226-9c96-d19dd2ca452e.png)

**Comment by rshewitt** [comment]
Confirmation of PIV card pickup

![Image](https://user-images.githubusercontent.com/92057378/230953641-7086fbf3-24b7-471c-b8c2-e37a63b3c4e6.png)

**Comment by rshewitt** [comment]
solr setup locally

![Image](https://user-images.githubusercontent.com/92057378/231245786-b98faf6f-6c0a-46a6-a2d7-fb3003ff3d91.png)

**Comment by rshewitt** [comment]
Running CKAN locally but no harvest jobs created. looking into it. 

![Image](https://user-images.githubusercontent.com/92057378/231266829-c2bb1068-6dd5-4685-8a70-39f232fd6764.png)

**Comment by jbrown-xentity** [comment]
Reading and getting up to speed shortlist: https://docs.google.com/spreadsheets/d/1hYm9A5ZnaKYCT34k996Fc1cW_ySIEw1R-7NsdFokw2E/edit#gid=0

**Comment by rshewitt** [comment]
started harvester job on test data

![Image](https://user-images.githubusercontent.com/92057378/231527000-14e23e3c-6cb6-4162-9248-a6e29309f471.png)

**Comment by rshewitt** [comment]
PIV card picked up. Next step is filling out google form for further access.

**Comment by rshewitt** [comment]
ordered PIV card reader. should be arriving 05/02.

**Comment by rshewitt** [comment]
Unable to use PIV card to login. It seems like the only remaining course of action is to delete my account. 
![Image](https://user-images.githubusercontent.com/92057378/235797271-fce68889-c247-4da3-9e7c-4a7d86f71977.png)

**Comment by rshewitt** [comment]
Requested access to data.gov system.

![Image](https://github.com/GSA/data.gov/assets/92057378/bfcfe96e-1b10-4909-b9a2-233b621ae047)
