### ISSUE TITLE
O+M 04-07-2023

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/data.gov#4268]
As part of day-to-day operation of Data.gov, there are many [Operation and Maintenance (O&M) responsibilities](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities). Instead of having the entire team watching notifications and risking some notifications slipping through the cracks, we have created an [O&M Triage role](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#om-triage-rotation). One person on the team is assigned the Triage role which rotates each sprint. _This is not meant to be a 24/7 responsibility, only East Coast business hours. If you are unavailable, please note when you will be unavailable in Slack and ask for someone to take on the role for that time._

## Miscs
-   Watch for user email requests
-   Watch in [#datagov-alerts](https://gsa-tts.slack.com/archives/C4RGAM1Q8) and [Vulnerable dependency notifications (daily email reports)](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#vulnerable-dependency-notifications-daily-email-reports) for critical alerts.
-   Monitor and improve [Data.gov O&M Dashboard](https://onenr.io/0LREMrzdrRa)

## Acceptance criteria
You are responsible for all [O&M responsibilities](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities) this week. We've highlighted a few so they're not forgotten. You can copy each checklist into your daily report.

## Daily Checklist
Check Deployments
- [ ] Catalog
- [ ] Inventory

Check Restarts
- [ ] Catalog
- [ ] Inventory

Check [Snyk Scans](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#automated-dependency-updates-ad-hoc-github-prs)
- [ ] Catalog
- [ ] Inventory

Check Catalog Auto Tasks
> **Note**
> You will need to update the chart values manually. Click the Action link in each issue and grab the values from `monitor task output` and `check runtime`.

- [ ] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848)
- [ ] [Tracking Update](https://github.com/GSA/catalog.data.gov/issues/847)

Check [Harvesting Emails](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#harvest-job-report-daily-email-report)
- [ ] Catalog

Other
- [ ] [New Relic Alerts](https://alerts.newrelic.com/accounts/1601367/incidents) Triaged
- [ ] Triage DMARC Report from Google

## Weekly Checklist
- [ ] [Audit Log](https://docs.google.com/spreadsheets/d/1z6lqmyNxC7s5MiTt9f6vT41IS2DLLJl4HwEqXvvft40/edit) (more info on [AU-3 and AU-6 Log auditing](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#au-3-and-au-6-log-auditing))
- [ ] Check [Catalog Solr](https://github.com/GSA/data.gov/wiki/Operation-and-Maintenance-Responsibilities#solr)
- [ ] [Catalog Dupe Check](https://github.com/GSA/data.gov/wiki/Operation-and-Maintenance-Responsibilities#duplicate-check)
- [ ] [Invicti Scan](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#netsparker-compliance-scan-report-from-isso)

**Comment by hkdctol** [comment]
We will try one week shifts. Let's check in at daily sync on Friday 4/7.

**Comment by Jin-Sun-tts** [comment]
## Friday 03/31 
Check Deployments
- [x] Catalog
- [x] Inventory

Check Restarts
- [x] Catalog
- [x] Inventory

Check [Snyk Scans](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#automated-dependency-updates-ad-hoc-github-prs)
- [x] Catalog
- [x] Inventory

Check Catalog Auto Tasks
- [x] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848): 33507 re-indexed today

![Screen Shot 2023-03-31 at 2 12 13 PM](https://user-images.githubusercontent.com/104456257/229197839-03a109ba-fe46-43bd-a805-bf7fc1f8e3e7.png)

- [x] [Tracking Update](https://github.com/GSA/catalog.data.gov/issues/847): 43566 updated today

![Screen Shot 2023-03-31 at 2 13 21 PM](https://user-images.githubusercontent.com/104456257/229198107-01198f84-32ae-4c04-b1bc-d998d6a1f857.png)

- Updated the graphic with number and time.
- Added new month for April, 

Check [Harvesting Emails](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#harvest-job-report-daily-email-report)
- [x] Catalog: 55 harvest job error emails received at 10AMEST (will check again in the later afternoon)

Other
- [x] [New Relic Alerts](https://alerts.newrelic.com/accounts/1601367/incidents) Triaged: there are two on staging:

![Screen Shot 2023-03-31 at 2 04 18 PM](https://user-images.githubusercontent.com/104456257/229196402-c15ed125-b12a-4122-9623-bcc776920085.png)

- [x] Triage DMARC Report from Google: 

![Screen Shot 2023-03-31 at 2 15 16 PM](https://user-images.githubusercontent.com/104456257/229198448-12af12b7-1d3b-487c-9636-431d474c61a2.png)


## Weekly Checklist
- [x] [Audit Log](https://docs.google.com/spreadsheets/d/1z6lqmyNxC7s5MiTt9f6vT41IS2DLLJl4HwEqXvvft40/edit) (more info on [AU-3 and AU-6 Log auditing](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#au-3-and-au-6-log-auditing))
- [x] Check [Catalog Solr](https://github.com/GSA/data.gov/wiki/Operation-and-Maintenance-Responsibilities#solr): There were memory warning earlier, but all green now.  
<img width="677" alt="Screen Shot 2023-03-31 at 1 59 49 PM" src="https://user-images.githubusercontent.com/104456257/229195665-c14ac42a-b6fb-4cdc-acf9-acf7030a6c9f.png">

- [x] [Catalog Dupe Check](https://github.com/GSA/data.gov/wiki/Operation-and-Maintenance-Responsibilities#duplicate-check)
![Screen Shot 2023-03-31 at 1 50 57 PM](https://user-images.githubusercontent.com/104456257/229195232-3fcfa1e7-cc3b-429c-8d87-8cbae384d8c2.png)

- [x] [Invicti Scan](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#netsparker-compliance-scan-report-from-isso): no report received.

**Comment by Jin-Sun-tts** [comment]
## Monday 04/03 

https://github.com/GSA/data.gov/tree/om-status-updates

![Screen Shot 2023-04-03 at 10 55 23 AM](https://user-images.githubusercontent.com/104456257/229547879-fa7b9683-9290-4f8f-b325-b27ac0bdf440.png)


Check Catalog Auto Tasks
- [x] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848):  4698 packages need to be updated/added to Solr

![Screen Shot 2023-04-03 at 11 19 19 AM](https://user-images.githubusercontent.com/104456257/229554225-27c4db32-4ffc-47d3-8688-d33cdee7f408.png)


- [x] [Tracking Update](https://github.com/GSA/catalog.data.gov/issues/847):  58192 package indexes to be rebuilt starting from 2023-03-31

![Screen Shot 2023-04-03 at 11 19 42 AM](https://user-images.githubusercontent.com/104456257/229554194-46adc4bf-09a1-4e69-bc62-1039c1ddedd3.png)



Check [Harvesting Emails](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#harvest-job-report-daily-email-report)
- [x] Catalog: By 5pm EST, total received 10 harvesting job error notification
- most of them are missing required fields like :

    - Identifier: https://data.cdc.gov/api/views/728v-5uaa; Title: trails_lines; 3 Error(s) Found. ### ERROR #1: 'programCode' is a required property;  ### ERROR #2: 'keyword' is a required property;  ### ERROR #3: 'description':'' is too short.
    - Identifier: https://healthdata.gov/api/views/9q39-eeqb; Title: Lyme Innovation & Health Equity; 2 Error(s) Found. ### ERROR #1: 'bureauCode' is a required property;  ### ERROR #2: 'programCode' is a required property.
    - Identifier: https://datadiscovery.nlm.nih.gov/api/views/a392-5wn4; Title: NLM Catalog; 1 Error(s) Found. ### ERROR #1: 'keyword' is a required property. 

- some of them are like:

    - Element not found: Identification Citation Originator
    - Transformation to ISO failed
    - Element not found: Metadata Reference Information Contact Address Type
    - Element not found: Metadata Reference Information Contact Address State
    - Element not found: Identification Citation Originator
    - Transformation to ISO failed
    - Element not found: Metadata Reference Information Contact Address Type
    - Element not found: Metadata Reference Information Contact Address State
    - Element not found: Metadata Reference Information Contact Address Type
    
Other
- [x] [New Relic Alerts](https://alerts.newrelic.com/accounts/1601367/incidents) Triaged: no critical issue on production.

![Screen Shot 2023-04-03 at 11 08 56 AM](https://user-images.githubusercontent.com/104456257/229551885-2fdc5638-c1c7-4ac2-8650-521a0b1b69fa.png)

![Screen Shot 2023-04-03 at 11 10 15 AM](https://user-images.githubusercontent.com/104456257/229551899-324ece7b-a72e-46ff-820d-ee0558e0fa67.png)

![Screen Shot 2023-04-03 at 11 22 35 AM](https://user-images.githubusercontent.com/104456257/229554956-ecc8cc1f-3427-4204-ac46-3053f74bc652.png)


- [x] Triage DMARC Report from Google: 

![Screen Shot 2023-04-03 at 11 07 16 AM](https://user-images.githubusercontent.com/104456257/229550931-91024a30-98de-4855-99b8-e08412e665f1.png)

**Comment by Jin-Sun-tts** [comment]
## Tuesday 04/04 

https://github.com/GSA/data.gov/

![Screen Shot 2023-04-04 at 9 40 15 AM](https://user-images.githubusercontent.com/104456257/229811288-8632ca25-59d4-4c62-ad19-e4ef9aae5d6e.png)


Check Catalog Auto Tasks
- [x] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848):  4698 packages need to be updated/added to Solr

![Screen Shot 2023-04-04 at 9 52 10 AM](https://user-images.githubusercontent.com/104456257/229814656-36957e03-a75a-4620-8807-3a177b7727f4.png)


- [x] [Tracking Update](https://github.com/GSA/catalog.data.gov/issues/847):  66683 package indexes to be rebuilt starting from 2023-04-01 00:00:00

![Screen Shot 2023-04-04 at 9 52 20 AM](https://user-images.githubusercontent.com/104456257/229814689-226ea488-c414-4cf9-8637-f6fec3e755b3.png)



Check [Harvesting Emails](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#harvest-job-report-daily-email-report)
- [x] Catalog: 
- no harvesting job reported yet at 10am EST
- 10 harvesting job reported yet at  5pm EST, most of them are related the missing required fields.

Other
- [x] [New Relic Alerts](https://alerts.newrelic.com/accounts/1601367/incidents) Triaged

2 or more locations failed on 'dashboard (production)' - resolved.

![Screen Shot 2023-04-04 at 10 15 38 AM](https://user-images.githubusercontent.com/104456257/229821229-cfda1e79-737c-48f1-a0f6-36b210a6f645.png)



- [x] Triage DMARC Report from Google: 

![Screen Shot 2023-04-04 at 10 14 38 AM](https://user-images.githubusercontent.com/104456257/229820944-3cdca6ce-71b4-47ae-b6c7-5a47471bc81c.png)

**Comment by Jin-Sun-tts** [comment]
## Wednesday 04/05 

https://github.com/GSA/data.gov/

![Screen Shot 2023-04-05 at 10 05 01 AM](https://user-images.githubusercontent.com/104456257/230115643-83576157-98b5-4bc8-bee6-7dd1799c49a7.png)



Check Catalog Auto Tasks
- [x] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848):  4698 packages need to be updated/added to Solr

![Screen Shot 2023-04-05 at 10 45 16 AM](https://user-images.githubusercontent.com/104456257/230117268-6d05b740-cbaf-4a85-a337-4abb6b14ff85.png)

- [x] [Tracking Update](https://github.com/GSA/catalog.data.gov/issues/847):  62393 package indexes to be rebuilt starting from 2023-04-02 00:00:00


![Screen Shot 2023-04-05 at 10 45 26 AM](https://user-images.githubusercontent.com/104456257/230117422-d575c807-360d-4aab-93f9-fe1058c354e9.png)


Check [Harvesting Emails](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#harvest-job-report-daily-email-report)
- [x] Catalog: 
- no harvesting job reported yet at 10am EST
- 11 harvesting job errors reported by 5pm EST

![Screen Shot 2023-04-05 at 4 53 10 PM](https://user-images.githubusercontent.com/104456257/230209297-8b9e7231-54a5-4519-bd69-a998ee36255f.png)

![Screen Shot 2023-04-05 at 4 52 58 PM](https://user-images.githubusercontent.com/104456257/230209308-f1431ede-209b-4b7a-9196-a470bbcc32f0.png)

![Screen Shot 2023-04-05 at 4 52 43 PM](https://user-images.githubusercontent.com/104456257/230209325-7a171ea6-ab9d-490c-be54-4cf6016035de.png)

Other
- [x] [New Relic Alerts](https://alerts.newrelic.com/accounts/1601367/incidents) Triaged

![Screen Shot 2023-04-05 at 10 51 09 AM](https://user-images.githubusercontent.com/104456257/230119042-294545c2-9f64-420e-b58b-7b4ccde05585.png)

![Screen Shot 2023-04-05 at 10 51 20 AM](https://user-images.githubusercontent.com/104456257/230119081-59935fcd-6526-486b-ba86-1dc16707605c.png)


- [x] Triage DMARC Report from Google: 

![Screen Shot 2023-04-05 at 10 53 42 AM](https://user-images.githubusercontent.com/104456257/230119817-c4a631da-a60d-48ed-a826-cf16e58b4817.png)

**Comment by Jin-Sun-tts** [comment]
## Thursday 04/06 

https://github.com/GSA/data.gov/

![Screen Shot 2023-04-06 at 1 00 48 PM](https://user-images.githubusercontent.com/104456257/230446412-79e367fd-581e-48e4-bb55-3b450153a671.png)


Check Catalog Auto Tasks
- [x] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848):  4697 packages need to be updated/added to Solr

![Screen Shot 2023-04-06 at 2 56 31 PM](https://user-images.githubusercontent.com/104456257/230470427-fa43f31c-d1b9-4086-9beb-773ebe4f1cf2.png)


- [x] [Tracking Update](https://github.com/GSA/catalog.data.gov/issues/847):  62150 package indexes to be rebuilt starting from 2023-04-03 00:00:00


![Screen Shot 2023-04-06 at 2 58 27 PM](https://user-images.githubusercontent.com/104456257/230470449-257dd63f-665e-4418-bbec-eb5bd2d3b308.png)


Check [Harvesting Emails](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#harvest-job-report-daily-email-report)
- [x] Catalog: 
- no harvesting job reported yet at 10am EST
- 9 harvesting job reported yet at  4pm EST, most of them are related the missing required fields.

Other
- [x] [New Relic Alerts](https://alerts.newrelic.com/accounts/1601367/incidents) Triaged

![Screen Shot 2023-04-06 at 2 59 41 PM](https://user-images.githubusercontent.com/104456257/230470734-b6971b41-243b-47bb-82e8-29cc92363cfb.png)


- [x] Triage DMARC Report from Google: 

![Screen Shot 2023-04-06 at 3 02 38 PM](https://user-images.githubusercontent.com/104456257/230471292-c85d022b-70ec-4ac7-8cc2-e79e2f88ad9e.png)

**Comment by Jin-Sun-tts** [comment]
## Friday 04/07

https://github.com/GSA/data.gov/

![Screen Shot 2023-04-07 at 9 57 36 AM](https://user-images.githubusercontent.com/104456257/230621744-c9802d70-deeb-48ee-a69a-30baeb9ace40.png)

Check Catalog Auto Tasks
- [x] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848):  10628 packages need to be updated/added to Solr

![Screen Shot 2023-04-07 at 10 04 12 AM](https://user-images.githubusercontent.com/104456257/230622086-f647bac4-b00d-40a3-926f-dee001d35908.png)


- [x] [Tracking Update](https://github.com/GSA/catalog.data.gov/issues/847):  55589 package indexes to be rebuilt starting from 2023-04-04 00:00:00

![Screen Shot 2023-04-07 at 10 06 26 AM](https://user-images.githubusercontent.com/104456257/230622379-edd74b85-f425-4080-83e3-ff1d35fa70a6.png)


Check [Harvesting Emails](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#harvest-job-report-daily-email-report)
- [x] Catalog: 
- 10amEST: 63 harvesting job errors reported since 4pm EST yesterday. 

![Screen Shot 2023-04-07 at 10 10 44 AM](https://user-images.githubusercontent.com/104456257/230623123-a27b23de-c312-43ea-b507-c96167a26229.png)

![Screen Shot 2023-04-07 at 10 10 32 AM](https://user-images.githubusercontent.com/104456257/230623135-0b3268a9-04b7-4333-bd85-a9023dc97963.png)
![Screen Shot 2023-04-07 at 10 10 13 AM](https://user-images.githubusercontent.com/104456257/230623159-f6f144b7-a676-4c79-b3e0-3e4c4b5980f2.png)
![Screen Shot 2023-04-07 at 10 10 02 AM](https://user-images.githubusercontent.com/104456257/230623167-ddb6214b-2b03-438d-a351-f4e3cf80d2e6.png)
![Screen Shot 2023-04-07 at 10 09 51 AM](https://user-images.githubusercontent.com/104456257/230623181-6c005bdf-d54e-455a-a491-81d722111a17.png)

![Screen Shot 2023-04-07 at 10 09 39 AM](https://user-images.githubusercontent.com/104456257/230623199-e0e6038b-e128-4086-9068-23dbd5f337a4.png)


Other
- [x] [New Relic Alerts](https://alerts.newrelic.com/accounts/1601367/incidents) Triaged

![Screen Shot 2023-04-07 at 9 57 04 AM](https://user-images.githubusercontent.com/104456257/230621817-a32618ca-2573-40a5-9474-6bf4c05779f9.png)


![Screen Shot 2023-04-07 at 4 16 17 PM](https://user-images.githubusercontent.com/104456257/230673416-244989bc-3ef6-4261-86f6-387c688ccd5b.png)


- [x] Triage DMARC Report from Google: 

![Screen Shot 2023-04-07 at 10 08 22 AM](https://user-images.githubusercontent.com/104456257/230622725-d49e6969-539f-4da7-9b57-2da90f0026d1.png)


## Weekly Checklist
- [x] [Audit Log](https://docs.google.com/spreadsheets/d/1z6lqmyNxC7s5MiTt9f6vT41IS2DLLJl4HwEqXvvft40/edit) (more info on [AU-3 and AU-6 Log auditing](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#au-3-and-au-6-log-auditing))
- [x] Check [Catalog Solr](https://github.com/GSA/data.gov/wiki/Operation-and-Maintenance-Responsibilities#solr): 
-  The leader and three follower are all green.  


- [x] [Catalog Dupe Check](https://github.com/GSA/data.gov/wiki/Operation-and-Maintenance-Responsibilities#duplicate-check)

![Screen Shot 2023-04-07 at 10 34 57 AM](https://user-images.githubusercontent.com/104456257/230626696-dc1df7fa-d6a3-4f73-b0c9-45afabe332a2.png)


- [x] [Invicti Scan](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#netsparker-compliance-scan-report-from-isso): no report received.
