### ISSUE TITLE
O+M 2023-06-02

### ISSUE THREAD

**Issue by Jin-Sun-tts** [GSA/data.gov#4338]
As part of day-to-day operation of Data.gov, there are many [Operation and Maintenance (O&M) responsibilities](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities). Instead of having the entire team watching notifications and risking some notifications slipping through the cracks, we have created an [O&M Triage role](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#om-triage-rotation). One person on the team is assigned the Triage role which rotates each sprint. _This is not meant to be a 24/7 responsibility, only East Coast business hours. If you are unavailable, please note when you will be unavailable in Slack and ask for someone to take on the role for that time._

## Miscs
-   Watch for user email requests
-   Watch in [#datagov-alerts](https://gsa-tts.slack.com/archives/C4RGAM1Q8) and [Vulnerable dependency notifications (daily email reports)](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#vulnerable-dependency-notifications-daily-email-reports) for critical alerts.
-   Monitor and improve [Data.gov O&M Dashboard](https://onenr.io/0LREMrzdrRa)

## Acceptance criteria
You are responsible for all [O&M responsibilities](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities) this week. We've highlighted a few so they're not forgotten. You can copy each checklist into your daily report.

## Daily Checklist
Check Production State/Actions
- [ ] [README](https://github.com/GSA/data.gov)
> **Note: Catalog Auto Tasks**
> You will need to update the chart values manually. Click the Action link in each issue and grab the values from `monitor task output` and `check runtime`.
- [ ] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848)
- [ ] [Tracking Update](https://github.com/GSA/catalog.data.gov/issues/847)
- [ ] Check [Harvesting Emails](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#harvest-job-report-daily-email-report)
- [ ] [New Relic Alerts](https://alerts.newrelic.com/accounts/1601367/incidents) Triaged
- [ ] Triage DMARC Report from Google

## Weekly Checklist
- [ ] [Audit Log](https://docs.google.com/spreadsheets/d/1z6lqmyNxC7s5MiTt9f6vT41IS2DLLJl4HwEqXvvft40/edit) (more info on [AU-3 and AU-6 Log auditing](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#au-3-and-au-6-log-auditing))
- [ ] Check [Catalog Solr](https://github.com/GSA/data.gov/wiki/Operation-and-Maintenance-Responsibilities#solr)
- [ ] [Catalog Dupe Check](https://github.com/GSA/data.gov/wiki/Operation-and-Maintenance-Responsibilities#duplicate-check)
- [ ] [Invicti Scan](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#netsparker-compliance-scan-report-from-isso)

**Comment by Jin-Sun-tts** [comment]
## Tuesday 05/30 

https://github.com/GSA/data.gov/

![Screen Shot 2023-05-30 at 10 29 54 AM](https://github.com/GSA/data.gov/assets/104456257/6c875764-b759-44e4-bcc2-b235609ac57b)

![Screen Shot 2023-05-30 at 12 30 45 PM](https://github.com/GSA/data.gov/assets/104456257/35e33a29-5c42-4b49-800b-c7b356774652)


Check Catalog Auto Tasks
- [x] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848):   packages need to be updated/added to Solr

![Screen Shot 2023-05-30 at 10 26 27 AM](https://github.com/GSA/data.gov/assets/104456257/86cf8f81-11e4-4d8f-a69a-4446c5bc1e7f)


- [x] [Tracking Update](https://github.com/GSA/catalog.data.gov/issues/847):  92671 package indexes to be rebuilt starting from 2023-05-28 00:00:00

![Screen Shot 2023-05-30 at 4 38 35 PM](https://github.com/GSA/data.gov/assets/104456257/985096a8-373f-46b6-8bbd-51436d69417f)

Check [Harvesting Emails](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#harvest-job-report-daily-email-report)
- [x] Catalog: 
- no harvesting job reported yet at 11am EST
- 10 harvesting job errors reported by 5pm EST, most of them are identifier missing related.

Other
- [x] [New Relic Alerts](https://alerts.newrelic.com/accounts/1601367/incidents) Triaged

- [x] Triage DMARC Report from Google: 

![Screen Shot 2023-05-30 at 12 53 48 PM](https://github.com/GSA/data.gov/assets/104456257/0b06fe84-74cd-47f7-9a9a-e2665cb87846)

**Comment by Jin-Sun-tts** [comment]
## Wednesday 05/31 

https://github.com/GSA/data.gov/

![Screen Shot 2023-05-31 at 11 09 03 AM](https://github.com/GSA/data.gov/assets/104456257/34dc6881-3d29-4337-9cea-48c6002b6fc7)

Check Catalog Auto Tasks
- [x] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848):   
        1 packages need to be removed from Solr
        8291 packages need to be updated/added to Solr

![Screen Shot 2023-05-31 at 12 57 55 PM](https://github.com/GSA/data.gov/assets/104456257/d85b6c5f-b637-49f6-aa0b-011e6aa7ef19)


- [x] [Tracking Update](https://github.com/GSA/catalog.data.gov/issues/847):  104112 package indexes to be rebuilt starting from 2023-05-28 00:00:00

![Screen Shot 2023-05-31 at 12 56 42 PM](https://github.com/GSA/data.gov/assets/104456257/47f80a80-a9ba-4a83-beda-76e227f68b74)

Check [Harvesting Emails](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#harvest-job-report-daily-email-report)
- [x] Catalog: 
- no harvesting job reported yet at 11am EST


Other
- [x] [New Relic Alerts](https://alerts.newrelic.com/accounts/1601367/incidents) 

![Screen Shot 2023-06-01 at 10 57 04 AM](https://github.com/GSA/data.gov/assets/104456257/df366128-6f3b-4e9c-9062-40721741d562)


- [x] Triage DMARC Report from Google:

**Comment by Jin-Sun-tts** [comment]
## Thursday 06/01 

https://github.com/GSA/data.gov/

![Screen Shot 2023-06-01 at 9 41 21 AM](https://github.com/GSA/data.gov/assets/104456257/0013f155-3eee-47ce-ad54-df147e09327f)


Check Catalog Auto Tasks
- [x] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848):  
       176 packages need to be removed from Solr
       8188 packages need to be updated/added to Solr 

![Screen Shot 2023-06-01 at 10 42 56 AM](https://github.com/GSA/data.gov/assets/104456257/2e3010dc-efe6-4bd3-924a-cdea0c8c99f2)

- [x] [Tracking Update](https://github.com/GSA/catalog.data.gov/issues/847): 90867 package indexes to be rebuilt starting from 2023-05-29 00:00:00

Check [Harvesting Emails](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#harvest-job-report-daily-email-report)
- [x] Catalog: 
- no harvesting job reported yet at 10am EST


Other
- [x] [New Relic Alerts](https://alerts.newrelic.com/accounts/1601367/incidents) 

- [x] Triage DMARC Report from Google:

**Comment by Jin-Sun-tts** [comment]
## Friday 06/02 

https://github.com/GSA/data.gov/
![Screen Shot 2023-06-02 at 9 29 15 AM](https://github.com/GSA/data.gov/assets/104456257/a2dbb20b-e421-4fda-89a3-0efa3a4d8bc9)


Check Catalog Auto Tasks
- [x] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848):  
        27 packages need to be removed from Solr
        23911 packages need to be updated/added to Solr

![Screen Shot 2023-06-02 at 9 35 31 AM](https://github.com/GSA/data.gov/assets/104456257/a6d7d983-f328-4a31-a82f-55460e7e8605)


- [x] [Tracking Update](https://github.com/GSA/catalog.data.gov/issues/847): 
        88294 package indexes to be rebuilt starting from 2023-05-30 00:00:00

![Screen Shot 2023-06-02 at 9 39 16 AM](https://github.com/GSA/data.gov/assets/104456257/c1623eea-779f-41bb-ac9b-ecf770a4cf2b)


Check [Harvesting Emails](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#harvest-job-report-daily-email-report)
- [x] Catalog: 
- 19 harvesting job errors reported yet at 9am E
![Screen Shot 2023-06-02 at 9 41 42 AM](https://github.com/GSA/data.gov/assets/104456257/f3fa5e08-0ee1-4457-9e5f-97ffef1f1493)
ST
![Screen Shot 2023-06-02 at 9 41 10 AM](https://github.com/GSA/data.gov/assets/104456257/7ead25f3-b92f-48b0-ba96-cea4eda3a5e6)

![Screen Shot 2023-06-02 at 9 41 21 AM](https://github.com/GSA/data.gov/assets/104456257/75c23553-2bd1-4fc0-b1d6-cec52609bfec)
![Screen Shot 2023-06-02 at 9 41 31 AM](https://github.com/GSA/data.gov/assets/104456257/dad14aa6-28f7-497a-b751-1312f8e3c466)


Other
- [x] [New Relic Alerts](https://alerts.newrelic.com/accounts/1601367/incidents) 


![Screen Shot 2023-06-02 at 9 43 16 AM](https://github.com/GSA/data.gov/assets/104456257/9959ddf2-dfac-4832-a6d2-9e3cfcc8977d)


- [x] Triage DMARC Report from Google: 


## Weekly Checklist
- [x] [Audit Log](https://docs.google.com/spreadsheets/d/1z6lqmyNxC7s5MiTt9f6vT41IS2DLLJl4HwEqXvvft40/edit) (more info on [AU-3 and AU-6 Log auditing](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#au-3-and-au-6-log-auditing))
- [x] Check [Catalog Solr](https://github.com/GSA/data.gov/wiki/Operation-and-Maintenance-Responsibilities#solr)
- [x] [Catalog Dupe Check](https://github.com/GSA/data.gov/wiki/Operation-and-Maintenance-Responsibilities#duplicate-check)

![Screen Shot 2023-06-02 at 4 36 41 PM](https://github.com/GSA/data.gov/assets/104456257/1996a9b2-b762-4682-a9cb-3e32d2d26e40)
