### ISSUE TITLE
Research current JSON-LD and HTML meta tag usage

### ISSUE THREAD

**Issue by dlennox24** [GSA/data.gov#4360]
## User Story

The current JSON-LD and metatag injection may have areas that could be improved. Ensuring robust page metadata will improve our SEO and general web discoverability. 

## Acceptance Criteria

- [ ] GIVEN the current JSON-LD and metatag state
THEN research what tags have been used and where we need to improve the structure and/or content of the tags

## Sketch

- [ ] Perform discovery into the current implementation of JSON-LD/metatags
- [ ] Determine where there are opportunities for improvements
- [ ] Create suggestions and follow-up tickets for those improvements

**Comment by robert-bryson** [comment]
Probably do this before https://github.com/GSA/data.gov/issues/4307 as it will inform the later.

**Comment by gujral-rei** [comment]
@robert-bryson, can you please add/update progress or blockers to this ticket?

**Comment by robert-bryson** [comment]
Spoke with Dan a bit on this. I have a better understanding of the ask here: in short add JSON-LD for the metadata tags used for the link previews. I also have a good example from the work he did on GeoPlatform to target.

**Comment by robert-bryson** [comment]
PR at https://github.com/GSA/ckanext-datagovtheme/pull/195. Appears to be working ([link](https://catalog-dev.data.gov/dataset/fy2021-federal-real-property-profile-summary-data-by-installation-name)):

![Image](https://github.com/GSA/data.gov/assets/91547795/10c00092-38e8-416f-bd67-d66cf25fe935)
