### ISSUE TITLE
New Data.gov vision/roadmap document

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#4390]
## User Story

In order to guide day-to-day work and to provide transparency, Data.gov team needs to develop a new vision/roadmap document.

## Acceptance Criteria

- [x] GIVEN a new team member in Data.gov or personnel in TTS, or a member of the public with interest in Data.gov status and future,
THEN there is a publicly available roadmap and vision document that provides basic understanding of mission and current/future work.
  

## Background

We have created various parts of this, collected in #4354 but need a new updated, concise document.

## Sketch

- [x] Create draft
- [x] Collaborate/review by team and any other stakeholders who should review
- [ ] Finalize and publish, make publicly available

**Comment by hkdctol** [comment]
Initial draft https://docs.google.com/document/d/1N3q6PQooi037OwRQArnfbttImcuqFwSk7DbJNMnLkic/edit?usp=sharing

**Comment by hkdctol** [comment]
Discussed on 8/9 - next step is add additional level of detail to each of the high level tasks in roadmap.

**Comment by hkdctol** [comment]
Closing this and will create a new ticket for publishing on home page.

**Comment by nickumia** [comment]
@btylerburton Maybe this is the document I was referring to?
