### ISSUE TITLE
O+M 2022-08-11

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#4417]
As part of day-to-day operation of Data.gov, there are many [Operation and Maintenance (O&M) responsibilities](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities). Instead of having the entire team watching notifications and risking some notifications slipping through the cracks, we have created an [O&M Triage role](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#om-triage-rotation). One person on the team is assigned the Triage role which rotates each sprint. _This is not meant to be a 24/7 responsibility, only East Coast business hours. If you are unavailable, please note when you will be unavailable in Slack and ask for someone to take on the role for that time._

Check the [O&M Rotation Schedule](https://docs.google.com/spreadsheets/d/1cF73HkzFuQth3z9voLfVO1Cc4kjBd6ecHGE2gkj5LCc/edit?usp=sharing) for future planning.

## Miscs
-   Watch for user email requests
-   Watch in [#datagov-alerts](https://gsa-tts.slack.com/archives/C4RGAM1Q8) and [Vulnerable dependency notifications (daily email reports)](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#vulnerable-dependency-notifications-daily-email-reports) for critical alerts.
-   Monitor and improve [Data.gov O&M Dashboard](https://onenr.io/0LREMrzdrRa)

## Acceptance criteria
You are responsible for all [O&M responsibilities](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities) this week. We've highlighted a few so they're not forgotten. You can copy each checklist into your daily report.

## Daily Checklist
Check Production State/Actions
- [ ] [README](https://github.com/GSA/data.gov)
> **Note: Catalog Auto Tasks**
> You will need to update the chart values manually. Click the Action link in each issue and grab the values from `monitor task output` and `check runtime`.
- [ ] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848)
- [ ] Check [Harvesting Emails](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#harvest-job-report-daily-email-report)
- [ ] [New Relic Alerts](https://alerts.newrelic.com/accounts/1601367/incidents) Triaged
- [ ] Triage DMARC Report from Google

## Weekly Checklist
- [ ] [Audit Log](https://docs.google.com/spreadsheets/d/1z6lqmyNxC7s5MiTt9f6vT41IS2DLLJl4HwEqXvvft40/edit) (more info on [AU-3 and AU-6 Log auditing](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#au-3-and-au-6-log-auditing))
- [ ] [Tracking Update](https://github.com/GSA/catalog.data.gov/issues/847)
- [ ] Check [Catalog Solr](https://github.com/GSA/data.gov/wiki/Operation-and-Maintenance-Responsibilities#solr)
- [ ] [Catalog Dupe Check](https://github.com/GSA/data.gov/wiki/Operation-and-Maintenance-Responsibilities#duplicate-check)
- [ ] [Invicti Scan](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#netsparker-compliance-scan-report-from-isso)

**Comment by Jin-Sun-tts** [comment]
## Monday 08/07 

https://github.com/GSA/data.gov/

Check Catalog Auto Tasks
- [x] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848):   
         5 packages need to be removed from Solr
1102 packages need to be updated/added to Solr
1422 packages without harvest_object need to be mannually deleted
Finished 907s


- [x] [Tracking Update](https://github.com/GSA/catalog.data.gov/issues/847):  2023-08-06T07:41:56.32+0000 [APP/TASK/ckangeodatagovtracking-update-5775349677-1/0] OUT 2023-08-06 07:41:56,322 INFO  [ckanext.geodatagov] 269107 package indexes to be rebuilt starting from 2023-07-28 00:00:00

Did not finished without 6 hours. https://github.com/GSA/catalog.data.gov/actions/runs/5775349677


[Egress Check Failed#1027](https://github.com/GSA/catalog.data.gov/issues/1027)
![Screenshot 2023-08-07 at 11 51 30 AM](https://github.com/GSA/data.gov/assets/104456257/805d5535-855e-4fcb-b93f-6e4b5fadc983)

Fix monitor logs script: https://github.com/GSA/catalog.data.gov/pull/1028


Check [Harvesting Emails](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#harvest-job-report-daily-email-report)
- [x] Catalog: 
- 7 harvesting job reported  at 11am EST

https://github.com/GSA/catalog.data.gov/actions/runs/5781819276/job/15667525439
2023-08-07T06:37:52.87+0000 [APP/TASK/ckangeodatagovcheck-stuck-jobs-5781819276-1/0] OUT 2023-08-07 06:37:52,878 INFO  [ckanext.geodatagov] **total 105 stuck harvest jobs**
![Screenshot 2023-08-07 at 10 46 52 AM](https://github.com/GSA/data.gov/assets/104456257/50a7aa79-cdfe-4901-a1bc-c8f663f3a533)

Scaling catalog-fetch to 30 instances at 200M ,  and re-harvested some job, most stuck jobs finished. 
![Screenshot 2023-08-07 at 12 20 18 PM](https://github.com/GSA/data.gov/assets/104456257/7ebd258e-e96a-4333-919a-2992436e20ad)

manually stop/rerun the harvest job for above stuck job "Environmental Dataset Gateway FGDC CSDGM "

**Comment by Jin-Sun-tts** [comment]
## Tuesday 08/08 

https://github.com/GSA/data.gov/
![Screenshot 2023-08-08 at 12 59 37 PM](https://github.com/GSA/data.gov/assets/104456257/d64c161d-fed7-4510-bfb3-112925a33875)


Check Catalog Auto Tasks
- [x] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848):   
         0 packages need to be removed from Solr
1574 packages need to be updated/added to Solr
1422 packages without harvest_object need to be mannually deleted
Finished 989s
![Screenshot 2023-08-08 at 11 38 33 AM](https://github.com/GSA/data.gov/assets/104456257/229c1450-141e-40be-8bea-7a8e7d37face)




After the fix monitor logs script: https://github.com/GSA/catalog.data.gov/pull/1028, it works for all checks.
![Screenshot 2023-08-08 at 11 28 35 AM](https://github.com/GSA/data.gov/assets/104456257/b2ac16e7-9089-483c-b1a4-c1918bff993e)


Check [Harvesting Emails](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#harvest-job-report-daily-email-report)
- [x] Catalog: 
- 11 harvesting job reported  at 11am EST

There is no harvester stuck jobs anymore.
![Screenshot 2023-08-08 at 11 32 35 AM](https://github.com/GSA/data.gov/assets/104456257/3ddb73c1-b376-4146-8ffb-ee43255b5530)

**Comment by Jin-Sun-tts** [comment]
## Wednesday 08/09

https://github.com/GSA/data.gov/

Check Catalog Auto Tasks
- [x] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848):   
         0 packages need to be removed from Solr
101 packages need to be updated/added to Solr
1422 packages without harvest_object need to be mannually deleted
Finished 557s


Check [Harvesting Emails](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#harvest-job-report-daily-email-report)
- [x] Catalog: 
- 4 harvesting job reported  at 11am EST

Checked catalog, inventory production, works fine.

Also checked Solr leader and followers, all work as normal.

There were some alert in datagov-alerts channel:

<img width="463" alt="Screenshot 2023-08-09 at 4 27 20 PM" src="https://github.com/GSA/data.gov/assets/104456257/a71ab474-0daa-41da-a4a4-c4b3a45d5d97">

<img width="518" alt="Screenshot 2023-08-09 at 4 27 07 PM" src="https://github.com/GSA/data.gov/assets/104456257/a770952d-746d-4ada-bd2a-e76e54e2e4ef">

<img width="511" alt="Screenshot 2023-08-09 at 4 26 56 PM" src="https://github.com/GSA/data.gov/assets/104456257/bb102e5a-4c13-452e-8e91-7ad696f9ecfb">

They all were closed within 4-19 minutes except last one closed on 4:08pmEST, duration was 53 min.

**Comment by Jin-Sun-tts** [comment]
## Thursday 08/10 

https://github.com/GSA/data.gov/
![Screenshot 2023-08-10 at 12 51 19 PM](https://github.com/GSA/data.gov/assets/104456257/11d1b7ec-9362-4c68-bd92-0a24b045ddf5)

Check Catalog Auto Tasks
- [x] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848):   
0 packages need to be removed from Solr
42 packages need to be updated/added to Solr
1422 packages without harvest_object need to be mannually deleted
Finished 536s

Check [Harvesting Emails](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#harvest-job-report-daily-email-report)
- [x] Catalog: 
- No harvesting job errors reported  at 11:00am EST
 
Other
- [x] [New Relic Alerts](https://alerts.newrelic.com/accounts/1601367/incidents) 

Checked catalog, inventory production, works fine.

Also checked Solr leader and followers, all work as normal.

**Comment by nickumia-reisys** [comment]
Important Issue created:
- https://github.com/GSA-TTS/datagov-brokerpak-smtp/issues/30

**Comment by Jin-Sun-tts** [comment]
## Friday 08/11

https://github.com/GSA/data.gov/

Check Catalog Auto Tasks
- [x] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848):   
56 packages need to be removed from Solr
40 packages need to be updated/added to Solr
1451 packages without harvest_object need to be mannually deleted
Finished 570s

Check [Harvesting Emails](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#harvest-job-report-daily-email-report)
- [x] Catalog: 
- 52 harvesting job error emails reported  at 9:05am EST
 
Other
- [x] [New Relic Alerts](https://alerts.newrelic.com/accounts/1601367/incidents) 

![Screenshot 2023-08-11 at 10 34 37 AM](https://github.com/GSA/data.gov/assets/104456257/86bf9de4-1cff-4388-bfea-f706d4b01733)

![Screenshot 2023-08-11 at 10 35 08 AM](https://github.com/GSA/data.gov/assets/104456257/8ab9319a-79b7-4641-b338-433e9ce5b238)


Checked catalog, inventory production, works fine.

Also checked Solr leader and followers, all work as normal.

## Weekly Checklist
- [x] [Audit Log](https://docs.google.com/spreadsheets/d/1z6lqmyNxC7s5MiTt9f6vT41IS2DLLJl4HwEqXvvft40/edit) (more info on [AU-3 and AU-6 Log auditing](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#au-3-and-au-6-log-auditing))
- [x] [Tracking Update](https://github.com/GSA/catalog.data.gov/issues/847) - Done on Monday 08/07
- [x] Check [Catalog Solr](https://github.com/GSA/data.gov/wiki/Operation-and-Maintenance-Responsibilities#solr)
- [x] [Catalog Dupe Check](https://github.com/GSA/data.gov/wiki/Operation-and-Maintenance-Responsibilities#duplicate-check)

<img width="1120" alt="Screenshot 2023-08-11 at 3 35 15 PM" src="https://github.com/GSA/data.gov/assets/104456257/1568ec28-8407-427d-8870-8d747c556492">

Run de-dup for above organizations.
