### ISSUE TITLE
O+M 2023-09-29

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#4468]
As part of day-to-day operation of Data.gov, there are many [Operation and Maintenance (O&M) responsibilities](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities). Instead of having the entire team watching notifications and risking some notifications slipping through the cracks, we have created an [O&M Triage role](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#om-triage-rotation). One person on the team is assigned the Triage role which rotates each sprint. _This is not meant to be a 24/7 responsibility, only East Coast business hours. If you are unavailable, please note when you will be unavailable in Slack and ask for someone to take on the role for that time._

Check the [O&M Rotation Schedule](https://docs.google.com/spreadsheets/d/1cF73HkzFuQth3z9voLfVO1Cc4kjBd6ecHGE2gkj5LCc/edit?usp=sharing) for future planning.

## Acceptance criteria
You are responsible for all [O&M responsibilities](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities) this week. We've highlighted a few so they're not forgotten. You can copy each checklist into your daily report.

## Daily Checklist
- [ ] [Check Production State/Actions](https://github.com/GSA/data.gov#datagov-actions)
> **Note: Catalog Auto Tasks**
> You will need to update the chart values manually. Click the Action link in each issue and grab the values from `monitor task output` and `check runtime`.
- [ ] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848)
- [ ] Check [Harvesting Emails](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#harvest-job-report-daily-email-report)
- [ ] [New Relic Alerts](https://alerts.newrelic.com/accounts/1601367/incidents) Triaged
- [ ] Triage DMARC Report from Google

## Weekly Checklist
- [ ] [Audit Log](https://docs.google.com/spreadsheets/d/1z6lqmyNxC7s5MiTt9f6vT41IS2DLLJl4HwEqXvvft40/edit) (more info on [AU-3 and AU-6 Log auditing](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#au-3-and-au-6-log-auditing))
- [ ] [Tracking Update](https://github.com/GSA/catalog.data.gov/issues/847)
    - NOTE: This job will consistently timeout, but it is processing results ((more details)[https://github.com/GSA/data.gov/issues/4345])
- [ ] Check [Catalog Solr](https://github.com/GSA/data.gov/wiki/Operation-and-Maintenance-Responsibilities#solr)
- [ ] [Catalog Dupe Check](https://github.com/GSA/data.gov/wiki/Operation-and-Maintenance-Responsibilities#duplicate-check)

## Monthly Checklist
- [ ] [Invicti Scan](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#netsparker-compliance-scan-report-from-isso)

## Reference
-   Watch for user email requests
-   Watch in [#datagov-alerts](https://gsa-tts.slack.com/archives/C4RGAM1Q8) and [Vulnerable dependency notifications (daily email reports)](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#vulnerable-dependency-notifications-daily-email-reports) for critical alerts.
-   Monitor and improve [Data.gov O&M Dashboard](https://onenr.io/0LREMrzdrRa)
-   Update and revise [Data.gov O&M Tasks](https://docs.google.com/document/d/1SVkY7SUhkcu6IAXIyuVo-s_E_Z400Is1JG9v5rbI7mI/edit?usp=sharing)

**Comment by Jin-Sun-tts** [comment]
## Monday 09/25 

https://github.com/GSA/data.gov/

Check Catalog Auto Tasks

- [x] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848):   
0 packages need to be removed from Solr
152 packages need to be updated/added to Solr
225 packages without harvest_object need to be mannually deleted
Finished 529s


- [x] [Tracking Update](https://github.com/GSA/catalog.data.gov/issues/847): 
2023-09-24T07:40:53.92+0000 [APP/TASK/ckangeodatagovtracking-update-6288764933-1/0] OUT 2023-09-24 07:40:53,926 INFO  [ckanext.geodatagov] 135537 package indexes to be rebuilt starting from 2023-09-15 00:00:00



Check [Harvesting Emails](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#harvest-job-report-daily-email-report)
- [x] Catalog: 
- 9 harvesting job reported  at 11am EST

Other
- [x] [New Relic Alerts](https://alerts.newrelic.com/accounts/1601367/incidents) 

Checked catalog, inventory production, works fine.

Also checked Solr leader and followers, all work as normal.

**Comment by Jin-Sun-tts** [comment]
## Tuesday 09/26 

https://github.com/GSA/data.gov/

Check Catalog Auto Tasks

- [x] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848):   
0 packages need to be removed from Solr
3 packages need to be updated/added to Solr
225 packages without harvest_object need to be mannually deleted
Finished 514s


Check [Harvesting Emails](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#harvest-job-report-daily-email-report)
- [x] Catalog: 
- 7 harvesting job reported  at 1:30pm EST

**Other**
- [x] [New Relic Alerts](https://alerts.newrelic.com/accounts/1601367/incidents) 

Checked catalog, inventory production, works fine.

Also checked Solr leader and followers, all work as normal.

- [x] Added user as Editor in Inventory

three users in opm [#538](https://github.com/GSA/datagov-account-management/issues/538) [#539](https://github.com/GSA/datagov-account-management/issues/539) [#540](https://github.com/GSA/datagov-account-management/issues/540)
one user in Ntia [#541](https://github.com/GSA/datagov-account-management/issues/541)

**Comment by Jin-Sun-tts** [comment]
## Wednesday 09/27 

https://github.com/GSA/data.gov/

Check Catalog Auto Tasks

- [x] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848):   
0 packages need to be removed from Solr
2 packages need to be updated/added to Solr
225 packages without harvest_object need to be mannually deleted
Finished 492s


Check [Harvesting Emails](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#harvest-job-report-daily-email-report)
- [x] Catalog: 
- 10 harvesting job reported  at 2:00pm EST

**Other**
- [x] [New Relic Alerts](https://alerts.newrelic.com/accounts/1601367/incidents) 
double checked the new formatted login information (either from API or saml)  is logged in the log


Checked catalog, inventory production, works fine.

Also checked Solr leader and followers, all work as normal.

- [x] Added user as Editor in Inventory

one user in DOL [#425](https://github.com/GSA/datagov-account-management/issues/425)

**Comment by Jin-Sun-tts** [comment]
## Thursday 09/28 

https://github.com/GSA/data.gov/

Check Catalog Auto Tasks

- [x] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848):   
0 packages need to be removed from Solr
2 packages need to be updated/added to Solr
226 packages without harvest_object need to be mannually deleted
Finished 484s


Check [Harvesting Emails](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#harvest-job-report-daily-email-report)
- [x] Catalog: 
- 6 harvesting job reported  at 1:56pm EST
most of them are related identifier, keyword missing errors.

**Other**
- [x] [New Relic Alerts](https://alerts.newrelic.com/accounts/1601367/incidents) 


Checked catalog, inventory production, works fine.

Also checked Solr leader and followers, all work as normal.

- [x]  issues:

[Automated CKAN Job Error Condition#1085](https://github.com/GSA/catalog.data.gov/issues/1085)
harvester run failed in all three environments: memory_in_mb exceeds organization memory quota
[ckan harvester run - prod](https://github.com/GSA/catalog.data.gov/actions/runs/6329318176/job/17189365801#logs)


[Egress Check Failed#1086](https://github.com/GSA/catalog.data.gov/issues/1086)
[catalog-admin - development - BadDomainTest](https://github.com/GSA/catalog.data.gov/actions/runs/6318109245/job/17156575036#logs)
2023-09-26T20:52:15.14+0000 [APP/TASK/egress-check-6318109245-2/0] ERR bash: line 1: BadDomainTest: command not found

**Comment by Jin-Sun-tts** [comment]
## Friday 09/29

https://github.com/GSA/data.gov/

Check Catalog Auto Tasks
- [x] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848):   
0 packages need to be removed from Solr
1 packages need to be updated/added to Solr
232 packages without harvest_object need to be mannually deleted
Finished 486s

Check [Harvesting Emails](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#harvest-job-report-daily-email-report)
- [x] Catalog: 
- 96 harvesting job error emails reported  at 12:20am EST
 
Other
- [x] [New Relic Alerts](https://alerts.newrelic.com/accounts/1601367/incidents) 


Checked catalog, inventory production, works fine.

Also checked Solr leader and followers, all work as normal.

## Weekly Checklist
- [x] [Audit Log](https://docs.google.com/spreadsheets/d/1z6lqmyNxC7s5MiTt9f6vT41IS2DLLJl4HwEqXvvft40/edit) (more info on [AU-3 and AU-6 Log auditing](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#au-3-and-au-6-log-auditing))
- [x] [Tracking Update](https://github.com/GSA/catalog.data.gov/issues/847) - Done on Monday 09/25
- [x] Check [Catalog Solr](https://github.com/GSA/data.gov/wiki/Operation-and-Maintenance-Responsibilities#solr)
- [x] [Catalog Dupe Check](https://github.com/GSA/data.gov/wiki/Operation-and-Maintenance-Responsibilities#duplicate-check)
![Screenshot 2023-09-29 at 1 05 33 PM](https://github.com/GSA/data.gov/assets/104456257/764a2832-89da-4eb9-9595-398579bb74c6)

Run de-dup for above organizations.
