### ISSUE TITLE
O+M 2023-10-27

### ISSUE THREAD

**Issue by Jin-Sun-tts** [GSA/data.gov#4507]
As part of day-to-day operation of Data.gov, there are many [Operation and Maintenance (O&M) responsibilities](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities). Instead of having the entire team watching notifications and risking some notifications slipping through the cracks, we have created an [O&M Triage role](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#om-triage-rotation). One person on the team is assigned the Triage role which rotates each sprint. _This is not meant to be a 24/7 responsibility, only East Coast business hours. If you are unavailable, please note when you will be unavailable in Slack and ask for someone to take on the role for that time._

Check the [O&M Rotation Schedule](https://docs.google.com/spreadsheets/d/1cF73HkzFuQth3z9voLfVO1Cc4kjBd6ecHGE2gkj5LCc/edit?usp=sharing) for future planning.

## Acceptance criteria
You are responsible for all [O&M responsibilities](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities) this week. We've highlighted a few so they're not forgotten. You can copy each checklist into your daily report.

## Daily Checklist
- [ ] [Check Production State/Actions](https://github.com/GSA/data.gov#datagov-actions)
> **Note: Catalog Auto Tasks**
> You will need to update the chart values manually. Click the Action link in each issue and grab the values from `monitor task output` and `check runtime`.
- [ ] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848)
- [ ] Check [Harvesting Emails](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#harvest-job-report-daily-email-report)
- [ ] [New Relic Alerts](https://alerts.newrelic.com/accounts/1601367/incidents) Triaged
- [ ] Triage DMARC Report from Google

## Weekly Checklist
- [ ] [Audit Log](https://docs.google.com/spreadsheets/d/1z6lqmyNxC7s5MiTt9f6vT41IS2DLLJl4HwEqXvvft40/edit) (more info on [AU-3 and AU-6 Log auditing](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#au-3-and-au-6-log-auditing))
- [ ] [Tracking Update](https://github.com/GSA/catalog.data.gov/issues/847)
    - NOTE: This job will consistently timeout, but it is processing results ((more details)[https://github.com/GSA/data.gov/issues/4345])
- [ ] Check [Catalog Solr](https://github.com/GSA/data.gov/wiki/Operation-and-Maintenance-Responsibilities#solr)
- [ ] [Catalog Dupe Check](https://github.com/GSA/data.gov/wiki/Operation-and-Maintenance-Responsibilities#duplicate-check)

## Monthly Checklist
- [ ] [Invicti Scan](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#netsparker-compliance-scan-report-from-isso)

## Reference
-   Watch for user email requests
-   Watch in [#datagov-alerts](https://gsa-tts.slack.com/archives/C4RGAM1Q8) and [Vulnerable dependency notifications (daily email reports)](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#vulnerable-dependency-notifications-daily-email-reports) for critical alerts.
-   Monitor and improve [Data.gov O&M Dashboard](https://onenr.io/0LREMrzdrRa)
-   Update and revise [Data.gov O&M Tasks](https://docs.google.com/document/d/1SVkY7SUhkcu6IAXIyuVo-s_E_Z400Is1JG9v5rbI7mI/edit?usp=sharing)

**Comment by Jin-Sun-tts** [comment]
## Monday 10/23 

https://github.com/GSA/data.gov/
![Screenshot 2023-10-23 at 1 02 10 PM](https://github.com/GSA/data.gov/assets/104456257/1b9c4ee7-b4aa-4260-8e9b-af8a084654f0)

Check Catalog Auto Tasks

- [x] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848):   
0 packages need to be removed from Solr
1173 packages need to be updated/added to Solr
186 packages without harvest_object need to be mannually deleted
Finished 588s


- [x] [Tracking Update](https://github.com/GSA/catalog.data.gov/issues/847): 
2023-10-23T07:39:17.47+0000 [APP/TASK/ckangeodatagovtracking-update-6610117038-1/0] OUT 2023-10-23 07:39:17,470 INFO  [ckanext.geodatagov] 5883 package indexes to be rebuilt starting from 2023-10-20 00:00:00


Check [Harvesting Emails](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#harvest-job-report-daily-email-report)
- [x] Catalog: 

Other
- [x] [New Relic Alerts](https://alerts.newrelic.com/accounts/1601367/incidents) 

Two issues found from New Relic logs:

- [catalog web proxy error for url http://www.google-analytics.com/collect#4508](https://github.com/GSA/data.gov/issues/4508)
We have added [www.google-analytics.com](http://www.google-analytics.com/) to the allow list, see the https://github.com/GSA/data.gov/pull/4509.

    But in the [ckanext-googleanalytics code,](https://github.com/ckan/ckanext-googleanalytics/blob/master/ckanext/googleanalytics/utils.py#L79-L87) HTTP instead of HTTPS is used. We need convince ckan upstream to use HTTPS.

- [disable new dataset creation on catalog#4161](https://github.com/GSA/data.gov/issues/4161)
anything starts with /dataset/new is blocked as in /dataset/new-hampshire-and-southern-maine-ocean-uses-atlas.

Checked catalog, inventory production, works fine.

Also checked Solr leader and followers, all work as normal.

**Comment by Jin-Sun-tts** [comment]
Snyk vulnerabilities check failed at synk test 

`Running setup.py develop for ckanext_googleanalytics`

![Screenshot 2023-10-24 at 12 39 33 PM](https://github.com/GSA/data.gov/assets/104456257/f26e2c2b-c2de-4d69-843b-e21120171aaf)

above errors happened since Oct 4th which just after enable ckanext_googleanalytics

**Comment by nickumia** [comment]
@Jin-Sun-tts The error you posted is the same in this issue:
- https://github.com/GSA/data.gov/issues/4481

**Comment by Jin-Sun-tts** [comment]
Above snyk error were fixed, will double check tomorrow morning.

Check catalog auto tasks:
- [x] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848):   
0 packages need to be removed from Solr
883 packages need to be updated/added to Solr
190 packages without harvest_object need to be mannually deleted
Finished 628s

Check [Harvesting Emails](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#harvest-job-report-daily-email-report)
- [x] Catalog: 

Other
- [x] [New Relic Alerts](https://alerts.newrelic.com/accounts/1601367/incidents) 

The two issues found on Monday also be fixed and confirmed from New Relic log.

**Comment by Jin-Sun-tts** [comment]
https://github.com/GSA/catalog.data.gov/actions/workflows/snyk.yml

![Screenshot 2023-10-26 at 1 41 46 PM](https://github.com/GSA/data.gov/assets/104456257/b53a9ab9-0fb2-493a-a265-622dbbc75641)

**Comment by Jin-Sun-tts** [comment]
harvest run failed : https://github.com/GSA/catalog.data.gov/issues/1121

`2023-10-27T13:55:52.02+0000 [APP/TASK/ckanharvesterrun-6668092691-1/0] ERR ckan.lib.search.common.SearchIndexError: Solr returned an error: Solr responded with an error (HTTP 500): [Reason: Server error writing document id 7b08d7b851606bed7c34f955569a891c4c05cff9 to the index]`

after restarted solr leader,  harvester rebuild index works.

rerun db solr sync and tracking update after above rebuild index issue fixed.

**Comment by Jin-Sun-tts** [comment]
## Friday 10/23 

https://github.com/GSA/data.gov/

Check Catalog Auto Tasks

- [x] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848):   
87 packages need to be removed from Solr
880 packages need to be updated/added to Solr
225 packages without harvest_object need to be mannually deleted
Finished 826s

- [x] [Tracking Update](https://github.com/GSA/catalog.data.gov/issues/847): 
2023-10-27T16:40:20.87+0000 [APP/TASK/ckangeodatagovtracking-update-6664271318-2/0] OUT 2023-10-27 16:40:20,875 INFO  [ckanext.geodatagov] 6854 package indexes to be rebuilt starting from 2023-10-25 00:00:00
