### ISSUE TITLE
O+M 2023-12-01

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#4538]
As part of day-to-day operation of Data.gov, there are many [Operation and Maintenance (O&M) responsibilities](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities). Instead of having the entire team watching notifications and risking some notifications slipping through the cracks, we have created an [O&M Triage role](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#om-triage-rotation). One person on the team is assigned the Triage role which rotates each sprint. _This is not meant to be a 24/7 responsibility, only East Coast business hours. If you are unavailable, please note when you will be unavailable in Slack and ask for someone to take on the role for that time._

Check the [O&M Rotation Schedule](https://docs.google.com/spreadsheets/d/1cF73HkzFuQth3z9voLfVO1Cc4kjBd6ecHGE2gkj5LCc/edit?usp=sharing) for future planning.

## Acceptance criteria
You are responsible for all [O&M responsibilities](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities) this week. We've highlighted a few so they're not forgotten. You can copy each checklist into your daily report.

## Daily Checklist
- [ ] [Check Production State/Actions](https://github.com/GSA/data.gov#datagov-actions)
> **Note: Catalog Auto Tasks**
> You will need to update the chart values manually. Click the Action link in each issue and grab the values from `monitor task output` and `check runtime`.
- [ ] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848)
- [ ] Check [Harvesting Emails](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#harvest-job-report-daily-email-report)
- [ ] [New Relic Alerts](https://alerts.newrelic.com/accounts/1601367/incidents) Triaged
- [ ] Triage DMARC Report from Google

## Weekly Checklist
- [ ] [Audit Log](https://docs.google.com/spreadsheets/d/1z6lqmyNxC7s5MiTt9f6vT41IS2DLLJl4HwEqXvvft40/edit) (more info on [AU-3 and AU-6 Log auditing](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#au-3-and-au-6-log-auditing))
- [ ] [Tracking Update](https://github.com/GSA/catalog.data.gov/issues/847)
    - NOTE: This job will consistently timeout, but it is processing results ((more details)[https://github.com/GSA/data.gov/issues/4345])
- [ ] Check [Catalog Solr](https://github.com/GSA/data.gov/wiki/Operation-and-Maintenance-Responsibilities#solr)
- [ ] [Catalog Dupe Check](https://github.com/GSA/data.gov/wiki/Operation-and-Maintenance-Responsibilities#duplicate-check)

## Monthly Checklist
- [ ] [Invicti Scan](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#netsparker-compliance-scan-report-from-isso)

## Reference
-   Watch for user email requests
-   Watch in [#datagov-alerts](https://gsa-tts.slack.com/archives/C4RGAM1Q8) and [Vulnerable dependency notifications (daily email reports)](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#vulnerable-dependency-notifications-daily-email-reports) for critical alerts.
-   Monitor and improve [Data.gov O&M Dashboard](https://onenr.io/0LREMrzdrRa)
-   Update and revise [Data.gov O&M Tasks](https://docs.google.com/document/d/1SVkY7SUhkcu6IAXIyuVo-s_E_Z400Is1JG9v5rbI7mI/edit?usp=sharing)

**Comment by Jin-Sun-tts** [comment]
## Monday 11/27 

https://github.com/GSA/data.gov/
![Screenshot 2023-11-27 at 12 55 55 PM](https://github.com/GSA/data.gov/assets/104456257/0f2b97d3-fc32-4988-a401-61dfb02aaa2a)


Check Catalog Auto Tasks

- [x] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848):   
0 packages need to be removed from Solr
4123 packages need to be updated/added to Solr
252 packages without harvest_object need to be mannually deleted
Finished 988s


- [x] [Tracking Update](https://github.com/GSA/catalog.data.gov/issues/847): 
2023-11-27T07:38:10.79+0000 [APP/TASK/ckangeodatagovtracking-update-7001939114-1/0] OUT 2023-11-27 07:38:10,790 INFO  [ckanext.geodatagov] 5879 package indexes to be rebuilt starting from 2023-11-24 00:00:00


Check [Harvesting Emails](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#harvest-job-report-daily-email-report)
- [x] Catalog: 

Other
- [x] [New Relic Alerts](https://alerts.newrelic.com/accounts/1601367/incidents) 

Checked catalog, inventory production, works fine.

Also checked Solr leader and followers, all work as normal.

**Comment by Jin-Sun-tts** [comment]
![Screenshot 2023-11-27 at 2 37 20 PM](https://github.com/GSA/data.gov/assets/104456257/ef285bc2-d340-407e-af78-4b3468bb976f)
Will check with Bret for the datagov-brokerpack-solr and datagov-ssb. just ignore them for now. 
 
`resource.data.gov `:
change saas version
check and fix the expiration date for existing exceptions. 

`datagov-harvesting-logic:` - still in development phase. ignore

`inventory-app` : reported from requirements-dev.txt, exclude this file from snyk scan.

**Comment by Jin-Sun-tts** [comment]
## Wednesday 11/29 

https://github.com/GSA/data.gov/

Check Catalog Auto Tasks

- [x] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848):   
0 packages need to be removed from Solr
2483 packages need to be updated/added to Solr
252 packages without harvest_object need to be mannually deleted
Finished 713s

Check [Harvesting Emails](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#harvest-job-report-daily-email-report)
- [x] Catalog

Other
- [x] [New Relic Alerts](https://alerts.newrelic.com/accounts/1601367/incidents)

**Comment by Jin-Sun-tts** [comment]
## Thursday 11/30

https://github.com/GSA/data.gov/

Check Catalog Auto Tasks

- [x] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848):   
2 packages need to be removed from Solr
1794 packages need to be updated/added to Solr
252 packages without harvest_object need to be mannually deleted
Finished 566s

Check [Harvesting Emails](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#harvest-job-report-daily-email-report)
- [x] Catalog

Other
- [x] [New Relic Alerts](https://alerts.newrelic.com/accounts/1601367/incidents) 

- [x] Snyk vulnerability check :
  inventory-app: Bumps [cryptography](https://github.com/pyca/cryptography) from 41.0.5 to 41.0.6. 
  PR: https://github.com/GSA/inventory-app/pull/675

  resource.data.gov:  add two exceptions from https://app.snyk.io/org/data.gov/project/22700983-7a0f-49aa-b664-c3f0abc51588 
  PR: https://github.com/GSA/resources.data.gov/pull/642

**Comment by Jin-Sun-tts** [comment]
## Friday 12/01

https://github.com/GSA/data.gov/

Check Catalog Auto Tasks
- [x] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848):   
0 packages need to be removed from Solr
1608 packages need to be updated/added to Solr
252 packages without harvest_object need to be mannually deleted
Finished 835s

Check [Harvesting Emails](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#harvest-job-report-daily-email-report)
- [x] Catalog: 
 
Other
- [x] [New Relic Alerts](https://alerts.newrelic.com/accounts/1601367/incidents) 


Checked catalog, inventory production, works fine.
Also checked Solr leader and followers, all work as normal.

## Weekly Checklist
- [x] [Audit Log](https://docs.google.com/spreadsheets/d/1z6lqmyNxC7s5MiTt9f6vT41IS2DLLJl4HwEqXvvft40/edit) (more info on [AU-3 and AU-6 Log auditing](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#au-3-and-au-6-log-auditing))
- [x] [Tracking Update](https://github.com/GSA/catalog.data.gov/issues/847) - Done on Monday 09/25
- [x] Check [Catalog Solr](https://github.com/GSA/data.gov/wiki/Operation-and-Maintenance-Responsibilities#solr)
- [x] [Catalog Dupe Check](https://github.com/GSA/data.gov/wiki/Operation-and-Maintenance-Responsibilities#duplicate-check)

Run de-dup for above organizations. 

- [x] Snyk vulnerability check :
PR https://github.com/GSA/inventory-app/pull/676

**Comment by nickumia** [comment]
@Jin-Sun-tts You should close your issue 😛
