### ISSUE TITLE
O+M 2024-01-08

### ISSUE THREAD

**Issue by hkdctol** [GSA/data.gov#4581]
As part of day-to-day operation of Data.gov, there are many [Operation and Maintenance (O&M) responsibilities](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities). Instead of having the entire team watching notifications and risking some notifications slipping through the cracks, we have created an [O&M Triage role](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#om-triage-rotation). One person on the team is assigned the Triage role which rotates each sprint. _This is not meant to be a 24/7 responsibility, only East Coast business hours. If you are unavailable, please note when you will be unavailable in Slack and ask for someone to take on the role for that time._

Check the [O&M Rotation Schedule](https://docs.google.com/spreadsheets/d/1cF73HkzFuQth3z9voLfVO1Cc4kjBd6ecHGE2gkj5LCc/edit?usp=sharing) for future planning.

## Acceptance criteria
You are responsible for all [O&M responsibilities](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities) this week. We've highlighted a few so they're not forgotten. You can copy each checklist into your daily report.

## Daily Checklist
- [ ] [Check Production State/Actions](https://github.com/GSA/data.gov#datagov-actions)
> **Note: Catalog Auto Tasks**
> You will need to update the chart values manually. Click the Action link in each issue and grab the values from `monitor task output` and `check runtime`.
- [ ] [Check auto generated O&M tickets](https://github.com/orgs/GSA/projects/11?pane=issue&itemId=47716346) from no status column
- [ ] Check [Harvesting Emails](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#harvest-job-report-daily-email-report)
- [ ] [New Relic Alerts](https://alerts.newrelic.com/accounts/1601367/incidents) Triaged
- [ ] Triage DMARC Report from Google

## Weekly Checklist
- [ ] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848)
- [ ] [Audit Log](https://docs.google.com/spreadsheets/d/1z6lqmyNxC7s5MiTt9f6vT41IS2DLLJl4HwEqXvvft40/edit) (more info on [AU-3 and AU-6 Log auditing](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#au-3-and-au-6-log-auditing))
- [ ] [Tracking Update](https://github.com/GSA/catalog.data.gov/issues/847)
    - NOTE: This job will consistently timeout, but it is processing results ((more details)[https://github.com/GSA/data.gov/issues/4345])
- [ ] Check [Catalog Solr](https://github.com/GSA/data.gov/wiki/Operation-and-Maintenance-Responsibilities#solr)
- [ ] [Catalog Dupe Check](https://github.com/GSA/data.gov/wiki/Operation-and-Maintenance-Responsibilities#duplicate-check)

## Monthly Checklist
- [ ] [Invicti Scan](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#netsparker-compliance-scan-report-from-isso)

## ad-hoc checklist
- [ ] audit/review applications on cloud foundry and determine what can be stopped and/or deleted. 

## Reference
-   Watch for user email requests
-   Watch in [#datagov-alerts](https://gsa-tts.slack.com/archives/C4RGAM1Q8) and [Vulnerable dependency notifications (daily email reports)](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#vulnerable-dependency-notifications-daily-email-reports) for critical alerts.
-   Monitor and improve [Data.gov O&M Dashboard](https://onenr.io/0LREMrzdrRa)
-   Update and revise [Data.gov O&M Tasks](https://docs.google.com/document/d/1SVkY7SUhkcu6IAXIyuVo-s_E_Z400Is1JG9v5rbI7mI/edit?usp=sharing)

**Comment by Jin-Sun-tts** [comment]
## Monday 01/08 

![Image](https://github.com/GSA/data.gov/assets/104456257/62f2aff0-4d68-4a1c-8a63-d5cf252776eb)


- [x] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848):   
0 packages need to be removed from Solr
0 packages need to be updated/added to Solr
190 packages without harvest_object need to be mannually deleted
Finished 625s

After reset the New Relic license key (https://github.com/GSA/data.gov/issues/4580), all environments has the normal log back to New Relic.

**Comment by Jin-Sun-tts** [comment]
## Tuesday 01/09

harvester run failed on prod because of memory issue.  

![Image](https://github.com/GSA/data.gov/assets/104456257/2e1d275a-f407-4c9f-9f76-6db612bea15d)

cg-support solved this issue and confirmed it is cloud.gov platform level issue related. They are working on a statuspage update regarding this matter. 

## Wednesday 01/10

![Image](https://github.com/GSA/data.gov/assets/104456257/08d90bcd-1554-42fa-b20b-5d028f060599)

**Comment by Jin-Sun-tts** [comment]
## Thursday 01/11

![Screenshot 2024-01-11 at 1 03 54 PM](https://github.com/GSA/data.gov/assets/104456257/ce2ba3ff-b5bc-4f7e-bc75-d59a175156c0)
![Screenshot 2024-01-11 at 1 03 29 PM](https://github.com/GSA/data.gov/assets/104456257/723e3863-7230-4b1e-961d-a9348c7f6d56)

**Comment by Jin-Sun-tts** [comment]
## Friday 01/12

Snyk Vulnerabilities check - add new exceptions:
https://github.com/GSA/catalog.data.gov/pull/1201
https://github.com/GSA/inventory-app/pull/686

## Weekly Checklist
- [x] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848):   
0 packages need to be removed from Solr
1 packages need to be updated/added to Solr
190 packages without harvest_object need to be mannually deleted
Finished 590s
- [x] [Audit Log](https://docs.google.com/spreadsheets/d/1z6lqmyNxC7s5MiTt9f6vT41IS2DLLJl4HwEqXvvft40/edit) (more info on [AU-3 and AU-6 Log auditing](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#au-3-and-au-6-log-auditing))
- [x] [Tracking Update](https://github.com/GSA/catalog.data.gov/issues/847) 
2024-01-12T07:39:27.22+0000 [APP/TASK/ckangeodatagovtracking-update-7499224870-1/0] OUT 2024-01-12 07:39:27,221 INFO  [ckanext.geodatagov] 15840 package indexes to be rebuilt starting from 2024-01-09 00:00:00
- [x] Check [Catalog Solr](https://github.com/GSA/data.gov/wiki/Operation-and-Maintenance-Responsibilities#solr)
- [x] [Catalog Dupe Check](https://github.com/GSA/data.gov/wiki/Operation-and-Maintenance-Responsibilities#duplicate-check)
https://github.com/GSA/datagov-dedupe/actions/workflows/check_org_duplicates.yml
![Screenshot 2024-01-12 at 6 06 45 PM](https://github.com/GSA/data.gov/assets/104456257/3773096d-4d83-4236-9b2c-6d1b438fd6ae)
