### ISSUE TITLE
Use GTM to implement comprehensive file download tracking

### ISSUE THREAD

**Issue by tdlowden** [GSA/data.gov#4699]
## User Story

In order to track all the types of file downloads from data.gov, datagov team wants to use GTM to capture all applicable file extensions.

## Acceptance Criteria

- [x] GIVEN users are downloading files from data.gov in .csv, .rdf, .json and other formats
  WHEN a datagov team members logs into google analytics
  THEN those downloads should be avaialble in reporting
  AND therefore able to produce for agencies

## Background

on 4/10/24, Tim L turned on default file download tracking in GA, but unfortunately it only captures .csv downloads from our less-common file extensions that exist on the catalog

![Image](https://github.com/GSA/data.gov/assets/6556888/795bb5b9-2314-4945-8709-483ec2b3bf1b)

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

none

## Sketch

- [x] Research how this can be done via GTM (https://www.analyticsmania.com/post/track-file-downloads-with-google-analytics-4/)
- [x] Implement the GTM method 
- [x] Test the method to verify functionality
- [x] Publish GTM container
- [ ] Uncheck default file_download tracking in GA settings

**Comment by tdlowden** [comment]
Added new filename and file extension variables, a trigger we can edit to match RegEx link clicks matching extension values including .rdf and .json, then created a custom event that tracks extension, file name, link text and link URI!

Moving to `needs review` so tomorrow I can check if data is populating in GA correctly.

**Comment by tdlowden** [comment]
I can see tracking for xml, rdf, and json, among others! 

![Image](https://github.com/GSA/data.gov/assets/6556888/9a5191b5-97ed-4443-be9f-b887dffb2a0c)
