### ISSUE TITLE
Implement outbound link tracking in GA

### ISSUE THREAD

**Issue by tdlowden** [GSA/data.gov#4700]
## User Story

In order to better understand how many outbound links are being clicked on data.gov, datagov team wants to implement outbound link tracking in GA.

## Acceptance Criteria

- [ ] GIVEN many links on the data.gov catalog are to outside resources
  WHEN someone clicks on an outbound link on our sites
  THEN a record of that should be sent to our datagov GA account
  AND thus be made available to provide to agencies

## Background

The default outbound link tracking in GA will not accommodate for cross-domain tracking out-of-the-box. Because our intended user journey path is from data.gov to catalog.data.gov, if we just flipped the switch, we'd have tens of thousands of `outbound link clicks` that would be intended for our users. Tis would increase our event/hit count and possibly cause muddying of the data via sampling/cardinality.

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

None

## Sketch

- [x] Research the potential ramifications of setting up a cross-domain list
- [ ] Set up a cross-domain ignore list
- [x] Implement outbound link tracking 
- [x] Test and QA

**Comment by tdlowden** [comment]
Turns out that GA4 automatically accounts for cross-subdomain traffic by keeping the same first party cookie. therefore, there was no need to set up a cross-domain tracking with respect to referrals and skewed visitor counts.

That said, for outbound link tracking, it would still count a click from data.gov to catalog.data.gov as an outbound link click, so I implemented a solution that would recognize a click from data.gov as not outbound.

Unfortunately, that can only be implemented if all sites are using the same datastream (they are) _and GTM instance_ (which they currently are not). data.gov and resources.data.gov are currently firing a gtag directly from the HTML, rather than using GTM containers. So I have created #4709 as a corollary issue.

But, outbound link tracking should now be enabled for catalog! Moving to `needs review` to verify in the GA interface after processing tomorrow.

**Comment by tdlowden** [comment]
We've got outbound links. Right now, the whole of the data includes outbound clicks to csvs, zips, etc. We can tweak that in the future at collection or eliminate it from the reports in filters. 

![Image](https://github.com/GSA/data.gov/assets/6556888/55338397-2dd5-4db5-bb78-acbecd7e0dbe)
