### ISSUE TITLE
O+M 2024-04-22

### ISSUE THREAD

**Issue by Jin-Sun-tts** [GSA/data.gov#4705]
As part of day-to-day operation of Data.gov, there are many [Operation and Maintenance (O&M) responsibilities](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities). Instead of having the entire team watching notifications and risking some notifications slipping through the cracks, we have created an [O&M Triage role](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#om-triage-rotation). One person on the team is assigned the Triage role which rotates each sprint. _This is not meant to be a 24/7 responsibility, only East Coast business hours. If you are unavailable, please note when you will be unavailable in Slack and ask for someone to take on the role for that time._

Check the [O&M Rotation Schedule](https://docs.google.com/spreadsheets/d/1cF73HkzFuQth3z9voLfVO1Cc4kjBd6ecHGE2gkj5LCc/edit?usp=sharing) for future planning.

## Acceptance criteria
You are responsible for all [O&M responsibilities](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities) this week. We've highlighted a few so they're not forgotten. You can copy each checklist into your daily report.

## Daily Checklist
- [ ] [Check Production State/Actions](https://github.com/GSA/data.gov#datagov-actions)
> **Note: Catalog Auto Tasks**
> You will need to update the chart values manually. Click the Action link in each issue and grab the values from `monitor task output` and `check runtime`.
- [ ] [Check auto generated O&M tickets](https://github.com/orgs/GSA/projects/11?pane=issue&itemId=47716346) from no status column
- [ ] Check [Harvesting Emails](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#harvest-job-report-daily-email-report)
- [ ] [New Relic Alerts](https://alerts.newrelic.com/accounts/1601367/incidents) Triaged
- [ ] Triage DMARC Report from Google

## Weekly Checklist
- [ ] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848)
- [ ] [Audit Log](https://docs.google.com/spreadsheets/d/1z6lqmyNxC7s5MiTt9f6vT41IS2DLLJl4HwEqXvvft40/edit) (more info on [AU-3 and AU-6 Log auditing](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#au-3-and-au-6-log-auditing))
- [ ] [Tracking Update](https://github.com/GSA/catalog.data.gov/issues/847)
    - NOTE: This job will consistently timeout, but it is processing results ((more details)[https://github.com/GSA/data.gov/issues/4345])
- [ ] Check [Catalog Solr](https://github.com/GSA/data.gov/wiki/Operation-and-Maintenance-Responsibilities#solr)
- [ ] [Catalog Dupe Check](https://github.com/GSA/data.gov/wiki/Operation-and-Maintenance-Responsibilities#duplicate-check)
- [ ] [Check user management requests](https://github.com/GSA/datagov-account-management/issues)

## Monthly Checklist
- [ ] [Invicti Scan](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#netsparker-compliance-scan-report-from-isso)

## ad-hoc checklist
- [ ] audit/review applications on cloud foundry and determine what can be stopped and/or deleted. 

## Reference
-   Watch for user email requests
-   Watch in [#datagov-alerts](https://gsa-tts.slack.com/archives/C4RGAM1Q8) and [Vulnerable dependency notifications (daily email reports)](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#vulnerable-dependency-notifications-daily-email-reports) for critical alerts.
-   Monitor and improve [Data.gov O&M Dashboard](https://onenr.io/0LREMrzdrRa)
-   Update and revise [Data.gov O&M Tasks](https://docs.google.com/document/d/1SVkY7SUhkcu6IAXIyuVo-s_E_Z400Is1JG9v5rbI7mI/edit?usp=sharing)

**Comment by Jin-Sun-tts** [comment]
DOE's /harvest/arm-data-json are down for two days

![Screenshot 2024-04-22 at 12 59 20 PM](https://github.com/GSA/data.gov/assets/104456257/1af76aad-f5ba-40bd-be6e-ed1ff31209f5)

**Comment by Jin-Sun-tts** [comment]
## Tuesday 04/23 

https://github.com/GSA/data.gov/

![Image](https://github.com/GSA/data.gov/assets/104456257/cf121f6d-cdd3-41b8-8239-f74e8373fa36)

rerun the failed commit job, it succeeded. 


### Check Catalog Auto Tasks

Check [Harvesting Emails](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#harvest-job-report-daily-email-report)

Update: Could not access the DOE site for this harvest source : https://www.archive.arm.gov/data/,  but the job finished without error today. Looks like their server goes up and down. 

- [x] Catalog: 

- [x] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848):   
0 packages need to be removed from Solr
0 packages need to be updated/added to Solr
429 packages without harvest_object need to be mannually deleted
Finished 520s


#### Checked catalog, inventory production, works fine.

#### Also checked Solr leader and followers, all work as normal.

**Comment by Jin-Sun-tts** [comment]
## Tuesday 04/23 

https://github.com/GSA/data.gov/

![Screenshot 2024-04-25 at 9 45 55 AM](https://github.com/GSA/data.gov/assets/104456257/122a1552-5ce6-4a20-ba1e-8f49a1debf1a)

### Check Catalog Auto Tasks

Check [Harvesting Emails](https://github.com/gsa/data.gov/wiki/Operation-and-Maintenance-Responsibilities#harvest-job-report-daily-email-report)

```
Harvest Source: NASA Data.json
Organization: nasa-gov
Created: 2024-04-24 16:52:45.861624
Finished: 2024-04-24 16:54:02.582310
    - Error loading json content: not enough values to unpack (expected 2, got 0).
    - ProxyError getting json source: HTTPSConnectionPool(host='[data.nasa.gov](http://data.nasa.gov/)', port=443): Max retries exceeded with url: /data.json (Caused by ProxyError('Unable to connect to proxy', RemoteDisconnected('Remote end closed connection without response'))).
```

**The error occurred on April 23, 2024, but it was success on April 22, 2024. This issue has occurred intermittently in the past, indicating possible issue in resource availability**


```
Harvest Source: DOI EDI
Organization: doi-gov
Created: 2024-04-24 16:52:45.119525
Finished: 2024-04-24 16:53:46.331441
    - Error loading json content: not enough values to unpack (expected 2, got 0).
    - HTTPError getting json source: 504 Server Error: Gateway Time-out for url: https://datainventory.doi.gov/data.json.
   
```
**The job run on April 24, 2024, at 5:23 PM was successful. This connection error had not occurred previously.**

- [x] Catalog: 

- [x] [DB-Solr Sync](https://github.com/GSA/catalog.data.gov/issues/848):   
0 packages need to be removed from Solr
0 packages need to be updated/added to Solr
429 packages without harvest_object need to be mannually deleted
Finished 555s


#### Checked catalog, inventory production, works fine.

#### Also checked Solr leader and followers, all work as normal.

**Comment by FuhuXia** [comment]
As one user pointed out, harvester /harvest/energy-json appears to be using a wrong URL. The current https://www.energy.gov/sites/default/files/2023-04/pdl040323.json is frozen at 2023-04 time frame. A dynamic URL  https://www.energy.gov/data.json seems to be the correct URL, it redirects to the current year current month.
@hkdctol
