### ISSUE TITLE
HTML meta tag content should be escaped

### ISSUE THREAD

**Issue by btylerburton** [GSA/data.gov#4793]
## User Story

In order to ensure a dataset's markup is valid, datagovteam wants to escape the content put into the <meta> tags.

Results of HTML validator scan should report no errors: https://validator.w3.org/nu/?doc=https%3A%2F%2Fcatalog.data.gov%2Fdataset%2Fdob-now-build-elevator-permit-applications

<img width="1217" alt="Screenshot 2024-06-12 at 11 45 17 AM" src="https://github.com/GSA/data.gov/assets/104455281/b833ae5b-7dfd-40a3-b774-116af562da1f">

## Acceptance Criteria

[ACs should be clearly demoable/verifiable whenever possible. Try specifying them using [BDD](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications).]

- [ ] GIVEN [a contextual precondition] \
  [AND optionally another precondition] \
  WHEN [a triggering event] happens \
  THEN [a verifiable outcome] \
  [AND optionally another verifiable outcome]

## Background

Bad html markup is causing issues with google search console. 

Example: https://catalog.data.gov/dataset/dob-now-build-elevator-permit-applications

<img width="1286" alt="Screenshot 2024-06-12 at 11 41 06 AM" src="https://github.com/GSA/data.gov/assets/104455281/0f35664f-3bee-4c40-9d9d-b8cb4bf01133">

## Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

## Sketch

- [ ] Escape content placed into meta tags
- [ ] Publish new pages
- [ ] Confirm results of HTML validator (https://validator.w3.org) don't throw any new errors

**Comment by btylerburton** [comment]
URLs have been sanitized, but string literals still need to be escaped...

`<meta property="og:description" content="{{ h.literal.escape(notes) }}">`

produces: 

`<meta property="og:description" content="The "Watershed Boundary Dataset (WBD)" from The National Map (TNM) defines the perimeter of drainage areas formed by the terrain and other landscape characteristics. The...">`

CKAN defines a string escape helper below but it seems to have no effect.

https://docs.ckan.org/en/2.10/theming/template-helper-functions.html?highlight=helper#ckan.lib.helpers.literal
