### ISSUE TITLE
dashboard-web and crm-web are unable to authenticate via Max.gov

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#527]
The latest deploy to dashboard-web includes a simplesamlphp upgrade and max.gov authentication no longer works. We opened an issue with maxsupport.

![screenshot from 2018-11-30 18-35-49](https://user-images.githubusercontent.com/509703/49396610-77f51580-f6ee-11e8-9aa2-63be1fceeb5d.png)

The updated simplesamlphp moves some of the endpoints around, which means we have to regenerate the SP metadata and submit it to MAX.gov for them to update their systems. I documented some of the details on the [wiki](https://github.com/GSA/datagov-deploy/wiki/MAX.gov-SAML2-authentication).

Unfortunately, the nginx config doesn't route the `/simplesaml` endpoints correctly, so there is no way to access the simplesaml admin where you can generate the metadata. 

Another complication, there may be some custom modifications made to simplesaml at deploy time through ansible. This should be removed if possible, and any change submitted upstream if necessary,

**Tasks**
- [x] update nginx config for dashboard and crm to allow simplesaml admin access
- [x] check the upgrade notes for [1.16](https://simplesamlphp.org/docs/stable/simplesamlphp-upgrade-notes-1.16) and [1.17](https://simplesamlphp.org/docs/stable/simplesamlphp-upgrade-notes-1.17) for any other config changes
- [x] asses the purpose of our [patches](https://github.com/GSA/datagov-deploy/blob/1ba1b07c5fafbf1a72b0de25540496cde5db9982/ansible/roles/software/crm/crm-deploy/tasks/main.yml#L65-L79), determine if necessary and how to adopt them to 1.17
- [ ] move saml configuration to applications, update configuration to specify local path to saml configuration
- [ ] generate SP for local development, [submit to MAX.gov](https://community.max.gov/pages/viewpage.action?pageId=1109066197)
- [x] generate the SP metadata, and [submit to MAX.gov](https://community.max.gov/pages/viewpage.action?pageId=1109066197)
- [x] Update [wiki](https://github.com/GSA/datagov-deploy/wiki/MAX.gov-SAML2-authentication#simplesaml-php-applications) for any changes

**Comment by adborden** [comment]
This isn't an issue for dashboard, but is a major issue for CRM. we should check that it affects CRM first before rolling out CRM.

**Comment by adborden** [comment]
This also affects CRM. I submitted updated metadata to the MAX.gov team for staging. Once updated, we can verify that this is resolved on staging.

**Comment by adborden** [comment]
Also, we do some patching in the playbook :( We should get rid of this.

https://github.com/GSA/datagov-deploy/blob/d2e77e876545251d96607378a47d599b7ebd9349/ansible/roles/software/crm/crm-deploy/tasks/main.yml#L65-L79

**Comment by adborden** [comment]
Updated description with details of the issues, how to upgrade properlly.

**Comment by adborden** [comment]
Still blocked. When authenticating, The SMS screen appears, and the verification code is sent, but after entering the verification code, MAX 404s, breaking the authentication flow. Waiting on MAX for more information.

**Comment by adborden** [comment]
MAX resolved the issue and this work has been merged.
