### ISSUE TITLE
Revitalize main data.gov repo with updated README and issue triage

### ISSUE THREAD

**Issue by JJediny** [GSA/data.gov#538]
https://github.com/GSA/data.gov

Has a large backlog of issues, and outdated README.
- [ ] Update README to reflect current repos and other links
- [ ] Review/consolidate similar issues and close out orginal issues for better tracking
- [ ] Make communication channels very clear for (feature-requests/technical issues/bugs/outages, bug bounty/security, etc)

**Comment by hkdctol** [comment]
This epic has been entered into github projects board https://github.com/orgs/GSA/projects/11/views/4

**Comment by jbrown-xentity** [comment]
This has been cleaned up and resolved; always iterative improvement to do but closing this.
