### ISSUE TITLE
Migrate from end of life Ubuntu 14.04

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#571]
Ubuntu 14.04 support ends [April 2019](https://www.ubuntu.com/about/release-cycle). We should move to Ubuntu 16.04 or 18.04. The latest 18.04 is preferred, but we should consider what kind of support exists for it.

Things to consider:
1. Availability of security benchmarks
1. Existing hardening roles
1. GSA GEAR
1. Third-party ansible role support

## Plan for rollout

1. Provision a bionic environment in sandbox for testing.
1. Begin refactoring roles, adding bionic to the molecule test suite where possible (in progress).
1. For each role, provision hosts in both staging and production. Once roles are working in staging, we can rollout to production. We can process roles in this order:
   1. jumpbox
   1. solr
   1. crm-web
   1. dashboard-web
   1. wordpress-web
   1. inventory-web
   1. pycsw
   1. catalog-web
   1. catalog-harvester
1. Decommission Ubuntu trusty hosts.

Note: jekyll-web should not be upgraded, we are moving static sites to Federalist so the jekyll-web hosts will no longer be needed.

### Tested in sandbox
- [x] jumpbox
- [x] solr
- [x] crm-web
- [x] dashboard-web
- [x] wordpress-web
- [x] inventory-web
- [x] pycsw
- [x] catalog-web
- [x] catalog-harvester

### Deployed to production
- [x] jumpbox
- [x] solr
- [x] crm-web
- [x] dashboard-web
- [x] wordpress-web
- [ ] inventory-web
- [ ] pycsw
- [ ] catalog-web
- [ ] catalog-harvester
- [x] data-strategy deployed to federalist
- [x] data-federation deployed to federalist
- [x] sdg deployed to federalist

**Comment by adborden** [comment]
@JJediny pointed out some baselines exist https://dev-sec.io/baselines/

**Comment by adborden** [comment]
> Ubuntu 14.04 will transition to Extended Security Maintenance (ESM) on **Thursday, April 25th, 2019**

https://lists.ubuntu.com/archives/ubuntu-announce/2019-March/000241.html

**Comment by adborden** [comment]
@JJediny i updated the plan in the description.

**Comment by mogul** [comment]
With the procurement and deployment of Ubuntu Advantage in #1682 the immediate need to stem the accruing security and compliance hazards has been met while leaving 14.04 in service. We'll be migrating to a more recent Ubuntu as a side effect of other Epics, eg the move to cloud.gov.
