### ISSUE TITLE
Create S3 buckets for sandbox environments

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#765]
## User Story
As a developer, I need [datagov-infrastructure-modules](https://github.com/GSA/datagov-infrastructure-modules) to create S3 buckets for inventory so that the [s3filestore](https://github.com/GSA/ckanext-s3filestore) extension works correctly.

## Acceptance Criteria
- [ ] GIVEN the s3filestore extension is enabled in inventory 
  WHEN app starts 
  THEN the app can correctly store dataset resources on S3
- [ ] GIVEN the s3filestore extension is enabled in catalog
  WHEN app starts 
  THEN the app can correctly store dataset resources on S3
- [ ] GIVEN the dashboard is configured to use S3
  WHEN the dashboard app starts 
  THEN the app can correctly store crawled JSON in S3

## Tasks
- [ ] S3 bucket and IAM user is created by terraform
- [ ] S3 bucket is configured correctly for public access

**Comment by nickumia-reisys** [comment]
No more sandbox.  No more FCS.
- https://github.com/GSA/data.gov/issues/3710
