### ISSUE TITLE
Setup Jenkins instance in mgmt

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#811]
## User Story
As a developer, I want a Jenkins instance setup in the mgmt vpc so that I have a place I can start implementing CI/CD checks against staging and production environments.

## Acceptance Criteria
- [x] GIVEN I run the jenkins.yml playbook
  WHEN I open my browser to https://ci-datagov.mgmt-ocsit.bsp.gsa.gov/
  THEN I see the Jenkins login screen

## Tasks
- [x] Re-provision jenkins and jumpbox in mgmt (RITM0799652)
- [x] [FCR](https://github.com/GSA/datagov-deploy/wiki/Firewall-Change-Requests) to update jumpbox IP address (RITM0802723 CHG0287665)
- [x] [FCR](https://github.com/GSA/datagov-deploy/wiki/Firewall-Change-Requests) to allow HTTP/HTTPS to mgmt web group (RITM0802773 CHG0287673
- [x] FCR to allow TCP/22 from Jenkins to all environments (RITM0807030)
- [x] Move Jenkins to MGMT subnet (RITM0807026)
- [x] [DNS](https://github.com/GSA/datagov-deploy/wiki/DNS) request to add ci.data.gov CNAME Netscaler (RITM0799653)
- [x] [DNS](https://github.com/GSA/datagov-deploy/wiki/DNS) request to add TXT record for Digicert verification (RITM0804234)
- [x] [DNS](https://github.com/GSA/datagov-deploy/wiki/DNS) request to add CAA record for Digicert authorization (RITM0807819)
- [x] Updated production [site certificate](https://github.com/GSA/datagov-deploy/wiki/TLS-SSL-Certificates) with ci.data.gov (RITM0799822)
- [x] New internal site certificate for ci-datagov.mgmt-ocsit.bsp.gsa.gov (RITM0809654)
- [x] Internal security scan (RITM0808732)
- [x] FCS request to add Jenkins instance to Netscaler (RITM0810496)
- [x] Updated [host certificate](https://github.com/GSA/datagov-deploy/wiki/TLS-SSL-Certificates) for mgmt (RITM0799823)
- [x] Add any additional configuration to Ansible (secrets)
- [x] [Manual setup](https://github.com/GSA/datagov-deploy#jenkins-configuration) for Jenkins credentials and CI

**Comment by adborden** [comment]
I just updated the story description. Moving to New so that we can re-groom it.

**Comment by adborden** [comment]
- [x] Created RITM0799652 to re-provision mgmt jumpbox and jenkins

**Comment by adborden** [comment]
Pinged FCS on the open tickets.

**Comment by adborden** [comment]
DNS TXT record for DigiCert is in place.

**Comment by adborden** [comment]
Have a call with SecOps on Monday to debug the firewall issue.

**Comment by adborden** [comment]
SecOps said that the subnet for the Jenkins instance (Prod-web) doesn't match the policy. I decided that the right thing to do was to move the Jenkins instance to the correct Mgmt-web subnet(s) (RITM0807026) instead of updating the Mgmt-web policy to point to Prod-web subnets.

I also opened a new FCR to allow SSH traffic from the Jenkins instance to all data.gov subnets (RITM0807030). Note that we are sort-of co-opting the Mgmt-web subnet/policy for Jenkins. Since MGMT is unused, this seems like the right shortcut to take instead of creating new subnets and policies for Jenkins when we are unlikely do do anything else with MGMT before the ATO expires.

SecOps also gave me a list of the [existing subnets](https://docs.google.com/document/d/19PwTE6rFay5fghAYcNjKCkeLM4OfZG7TqZ4lAL9hZpA/edit#) for reference.

**Comment by adborden** [comment]
GSA marked the site certificate ticket as resolved without including the fixed certificate, so I've also followed up on that.

**Comment by adborden** [comment]
DigiCert is now requiring a CAA record. I've opened RITM0807819 to create this. I also opened https://github.com/GSA/datagov-deploy/issues/2690 to remind us to do this when we move applications to cloud.gov. Currently their certificates are issued by letsencrypt.org.

**Comment by adborden** [comment]
I also opened RITM0807835 to allow ACM to issue certificates for Federalist domains.

**Comment by adborden** [comment]
Pivoting a bit, focusing on an internal deployment at ci-datagov.mgmt-ocsit.bsp.gsa.gov.

I opened the final ticket with FCS to create an ALB for ci-datagov.mgmt-ocsit.bps.gsa.gov RITM0810496.

**Comment by adborden** [comment]
🎉  the netscaler change is in place and https://ci-datagov.mgmt-ocsit.bsp.gsa.gov/ is alive!

😢  unfortunately we're still unable to deploy because of [docker](https://github.com/GSA/datagov-deploy/issues/2708). Without docker hub credentials, we're hitting the docker API limit within the FCS network. Even after working around that, I'm running into network forwarding errors ("[Warning] IPv4 forwarding is disabled. Networking will not work.") and we should not be enabling IP forwarding. The right thing to do here is to remove docker.

**Comment by adborden** [comment]
I added the credentials described in the [README](https://github.com/GSA/datagov-deploy#jenkins-configuration) with the exception of the mgmt and production SSH key. I was hoping to see staging working before adding those.
