### ISSUE TITLE
Identify and remove obsolete content on www.data.gov

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#977]
## User Story

In order to ensure information on the main data.gov site is useful and accurate
we want to review all the existing content and remove obsolete content.

## Details

We haven't been paying much attention to this content and there's a lot of stuff that's abandoned and/or shouldn't be there. This is a first-pass clean up to clear that content debt.

## Acceptance Criteria

- [x] GIVEN I am reviewing the list of "delete" content on a staging deployment \
  WHEN I visit the URL for any "delete" line \
  THEN I get a 404 response
- [x] We review the remaining content and determine if additional content (re-)design is necessary to keep the site relevant \
  IF SO, create an issue for that \
  OTHERWISE there is a production DB dump in Google Drive \
  AND the deletions are effective in production
- [x] Approved blog post describing changes to site
- [x] WHEN I look at the top of the data.gov site \
 THEN I do NOT see links for "Impact" and "Applications" \
 AND I DO see links for "Resources" and "Strategy" that go to the respective sites

## Tasks
- [x] Create a list of all content found on the site 
- [x] Review the list and mark with with "keep" or "delete" depending on the state of the content
- [x] Check with external content owners to see if they care/want to make updates
- [x] Maybe automate the deletion process since it's high volume and will have to be repeated for production?
- [x] Capture a snapshot of the production database for retention/review purposes
- [x] Remove any "delete" content from Wordpress

**Comment by mogul** [comment]
Hyon is checking with agency partners to get consensus on how to archive/remove the obsolete content.

**Comment by hkdctol** [comment]
I have finished review and agency communication.

https://docs.google.com/spreadsheets/d/1ZohmuI28lsO5HMG5h7NqkEpkynJ6w-3xPdW3RZyYXr0/edit#gid=1850827333

is the document to work off of for next steps

**Comment by hkdctol** [comment]
The spreadsheet deletes topics except for Agriculture, Climate, Energy, Local Government, Maritime and Ocean. It also deletes Applications and Impact. Perhaps we'd replace those two to link to resources.data.gov and strategy.data.gov instead? With the headings being RESOURCES and STRATEGY?

**Comment by mogul** [comment]
Most records are cleared in staging; @hkdctol to review what it looks like there before we move onto making the same changes in production.

**Comment by hkdctol** [comment]
Results of staging review:

The topics that should remain are Agriculture, Climate, Ecosystem, Energy, Local Government, Maritime and Ocean. (I see Consumer still has content but I don't think it needs to be retained). Should we retain the current view, or should it be pull down only from Topics?

On the blog (link from footer) on staging I see older blog posts. We would want to keep the more current blog posts in production (has 2019 entries and older)

We don't need Impact or Applications sections. Should we replace with just a link to Resources and Strategy pages?

On the Developers page (we are keeping), there's a Challenges tab that we are deleting so we would want to remove the navigation to Challenges in that section.

**Comment by hkdctol** [comment]
@ydave-reisys 

on staging, let's try the pull down on topics, with remaining topics

on blogs, let's keep up to page 4 in production, which is a 2015 entry, the rest can be archived

in staging, can we substitute impact and applications navigation to go to resources and strategy

**Comment by mogul** [comment]
@hkdctol is going to make sure @philipashlock puts 👀 on this before we roll out to production, and have a blog post noting the change before we roll it out.

**Comment by hkdctol** [comment]
@philipashlock can you provide feedback on https://wordpress-datagov.dev-ocsit.bsp.gsa.gov/ specifically replacing Impact and Applications tabs with links to resources.data.gov and strategy.data.gov

**Comment by hkdctol** [comment]
@philipashlock pinging on above--do you have any issues with putting links to resources and strategy on top level navigation on main data.gov https://wordpress-datagov.dev-ocsit.bsp.gsa.gov/

**Comment by philipashlock** [comment]
@hkdctol Yeah, I'm supportive of swapping out those two top level nav links. Although I think it might make sense to style them differently and maybe separate them or put them both on the far right of the nav bar to help denote that they go to separate websites which don't share the same nav or site design since they're behavior is different than all the the other links and you can't easily get back to this view without hitting the back button in the browser. 

I'd be ok still rolling out the update without making those changes, but we should try to factor that issue in soon.

**Comment by mogul** [comment]
@adborden is going to investigate whether there's any bulk way to associate stuff intended to be removed (in the spreadsheet above) with identifiers in the Wordpress API that would make this quick work.

One idea to be investigated: Yaditi changed the "removed" stuff to the draft state in staging. Can we query for stuff in the draft state in staging to get a list of what should be changed to the draft state in production?

**Comment by mogul** [comment]
Aaron's got a process for identifying IDs for content to be removed, though there are still some things that will need to be managed by hand.

**Comment by mogul** [comment]
The blog post has been approved. Now just need our process for making the changes live worked out.

**Comment by hkdctol** [comment]
Under TTS blog post review process it is approved and just has to be on editorial calendar for five days. So we can make the changes and publish next Friday, or if need to do earlier we'd just have to coordinate with TTS Outreach.

**Comment by adborden** [comment]
Have a couple scripts that grab Ids from the URL and then generates some wp CLI commands to update those posts to drafts (in which case they are no longer publicly visible) or deletes them via an environment variable.

https://gist.github.com/adborden/eb8b498c8b9554ede10734d2ad82c25a

**Comment by adborden** [comment]
Scheduled this work for Thursday afternoon to go out with the blog post on Friday.

**Comment by adborden** [comment]
Content has been marked as [draft in production](https://drive.google.com/open?id=1sM_gwb8FFp5fMZ1rees9uvAeiT3TWLAN).

**Comment by adborden** [comment]
I forgot to take a database snapshot before marking the posts as draft :facepalm: I took a snapshot https://drive.google.com/open?id=13-fH-3by9M0tD1LJbBrRQgugTBPqidQT, and using the log above we can reconstruct if we need to.

**Comment by mogul** [comment]
Since the content went to draft rather than being deleted, it's probably fine. The main reason for the backup was to ensure we could still get to the content if we needed to, not so we could reverse the change wholesale.

**Comment by hkdctol** [comment]
There is one more task remaining - with smaller number of topics being retained, change Topics pull down to limited list (see https://wordpress-datagov.dev-ocsit.bsp.gsa.gov/) of Agriculture, Climate, Ecosystems, Energy, Local Government, Maritime and Ocean; then delete current "Browse Topics" section on the front page.

**Comment by adborden** [comment]
Removed these from the Topics menu:
- Consumer
- Education
- Finance
- Health
- Manufacturing
- Public Safety
- Science & Research

**Comment by adborden** [comment]
@hkdctol since there are 7 categories remaining, it ends up being one complete row. Here's what it looks like on my local development environment:

![screencapture-localhost-8000-2020-05-11-19_01_44](https://user-images.githubusercontent.com/509703/81630285-0d073e00-93ba-11ea-999f-0b51a5b1c680.png)

Would you prefer to list the 7 as above, or should we just remove the Browse Topics entirely?

**Comment by hkdctol** [comment]
@adborden I think it makes sense to remove Browse Topics section entirely.

**Comment by adborden** [comment]
After deploying this, I did have to invalidate the cache in AWS.
