### ISSUE TITLE
[Onboard] bret.mogilefsky@gsa.gov

### ISSUE THREAD

**Issue by adborden** [GSA/data.gov#999]
Welcome! [The Onboarding wiki](https://github.com/GSA/datagov-deploy/wiki/Onboarding-Offboarding) describes the onboarding process for new team members on Data.gov. You’ll learn mostly from pairing and interaction with your teammates but these are some handy resources to get you started.

Below are the tasks that will drive the onboarding process.

### Tasks for admin or onboarding buddy

- [x] Add team member to [TTS Slack](https://handbook.18f.gov/slack/#tts-staff)
- [x] Add team member to #datagov-pmo (PMO only)
- [x] Add team member to Data.gov slack channels
  - [x] #bug-bounty
  - [x] #bug-bounty-partners
  - [x] #datagov-alerts
  - [x] #datagov-ckan-multi
  - [x] #datagov-comms
  - [x] #datagov-devsecops
  - [x] #datagov-notifications
  - [x] #opp-data-analytics
- [x] Invite team member to calendar events
  - Daily sync
  - Sprint planning
  - Retro
  - CKAN-multi project syncs
  - FGDC meeting
  - CKAN Gov Working group
- [x] Add new team member to email lists
  - [x] [Data.gov support list](https://groups.google.com/a/gsa.gov/forum/#!forum/datagov)
  - [x] [Data.gov team list](https://groups.google.com/a/gsa.gov/forum/#!forum/datagovhelp)
  - [x] inventory-help
- [x] Make sure team member has 2FA enabled for their GitHub account and [request](https://github.com/GSA/GitHub-Administration/blob/master/README.md#requesting-access-to-the-gsa-organization) membership to GSA GitHub org
- [x] Add team member to GitHub teams
  - [data-gov-admins](https://github.com/orgs/GSA/teams/data-gov-admin/members) (PMO only)
  - [data-gov-support](https://github.com/orgs/GSA/teams/data-gov-support/members) (non-PMO)
- [x] Add team member to shared Google Drives
  - Data.gov
  - CKAN multi
  - DevSecOps
- [x] Request TTS Bug Bounty access [#bug-bounty-partners](https://gsa-tts.slack.com/messages/C5JQCD9PH)
- [x] Share Ansible vault keys with team member
- [x] Add team member to Uptrends via [email](https://docs.google.com/spreadsheets/d/1Z9Zpr1mpx-65i_fH2VTbVofPtidpLZs5cnkO0Jz53Vc/edit#gid=0)
- [x] Add team member to [New Relic](https://newrelic.com)
- [x] Add team member to [Docker Hub](https://cloud.docker.com/orgs/datagov/teams)
- [x] Introduce team member at next TTS-Solutions meeting
- [x] Introduce new team member to OMB team
- [x] Introduce new team member to the Federal Geospatial Data Community
- [x] Introduce new team member to government Open Data community at monthly meeting
- [x] Add to Jira

### Tasks for new team member

- [x] Ensure your GitHub account meets the criteria for [GSA GitHub org](https://github.com/GSA/GitHub-Administration/blob/master/README.md) (setup 2FA)
- [x] Read through the [required reading list](https://github.com/GSA/datagov-deploy/wiki/Onboarding-Offboarding#reading-list)
- [x] [Request access](https://docs.google.com/forms/d/e/1FAIpQLSetStmwqrbMWDz_WIlh1trjhP0PFCjKXHzshsJveYmtIvlG2Q/viewform) to Data.gov systems; select “Catalog Admin” for the system, and “Data.gov team member” for justification
- [x] Add yourself for [AWS sandbox access](https://github.com/GSA/datagov-infrastructure-live/tree/master/iam#new-users)
- [x] Add yourself for [jumpbox access](https://github.com/GSA/datagov-deploy/blob/develop/ansible/group_vars/all/vault.yml)
- [x] Join the international [CKAN Government Working Group](https://docs.google.com/document/d/1d04ZmvSCjb3zhsIZW01wSkoRSzIiLyWen5Z8iwfzhIU/edit)
- [x] Join [Open Data](https://digital.gov/communities/open-data/) community list

**Comment by adborden** [comment]
Here's a PR with my checklist updates so far https://github.com/GSA/datagov-deploy/pull/1000

**Comment by mogul** [comment]
Finally had a chance to read the SSP. I have some questions for Aaron that I'll bring up in our next coworking session, but I think I can finally put this issue to bed.
